import json
filepath = 'core/static/tracks_data.js'
with open(filepath, 'r', encoding='utf-8') as f: content = f.read()
prefix = 'window.tracksData = '
pi = content.find(prefix); pc = content[:pi+len(prefix)]; js = content[pi+len(prefix):]
sf = ''
if js.strip().endswith(';'): js = js.strip()[:-1]; sf = ';'
data = json.loads(js)

# JAVA examples
java_ex = {
    "java_basics": [
        {"title":"Hello World Program","code":"public class Main {\n    public static void main(String[] args) {\n        System.out.println(\"Hello, World!\");\n    }\n}","output":"Hello, World!","explanation":"This is the simplest Java program. The main() method is the entry point. System.out.println() prints text followed by a new line."},
        {"title":"Printing Variables","code":"public class Main {\n    public static void main(String[] args) {\n        String name = \"Alice\";\n        int age = 25;\n        System.out.println(\"Name: \" + name);\n        System.out.println(\"Age: \" + age);\n    }\n}","output":"Name: Alice\nAge: 25","explanation":"We declare a String and int variable, then print them using string concatenation with the + operator."}
    ],
    "java_variables": [
        {"title":"Declaring Different Data Types","code":"public class Main {\n    public static void main(String[] args) {\n        int count = 10;\n        double price = 19.99;\n        char grade = 'A';\n        boolean isActive = true;\n        String message = \"Hello\";\n        \n        System.out.println(\"Count: \" + count);\n        System.out.println(\"Price: \" + price);\n        System.out.println(\"Grade: \" + grade);\n        System.out.println(\"Active: \" + isActive);\n        System.out.println(\"Message: \" + message);\n    }\n}","output":"Count: 10\nPrice: 19.99\nGrade: A\nActive: true\nMessage: Hello","explanation":"Each variable is declared with its type. int for whole numbers, double for decimals, char for single characters, boolean for true/false, and String for text."},
        {"title":"Type Casting","code":"public class Main {\n    public static void main(String[] args) {\n        int x = 10;\n        double y = x;  // automatic widening\n        System.out.println(\"int to double: \" + y);\n        \n        double a = 9.78;\n        int b = (int) a;  // manual narrowing\n        System.out.println(\"double to int: \" + b);\n    }\n}","output":"int to double: 10.0\ndouble to int: 9","explanation":"Widening (small to big type) happens automatically. Narrowing (big to small) requires explicit casting with (int) and loses the decimal part."}
    ],
    "java_operators": [
        {"title":"Arithmetic Operations","code":"public class Main {\n    public static void main(String[] args) {\n        int a = 15, b = 4;\n        System.out.println(\"Add: \" + (a + b));\n        System.out.println(\"Subtract: \" + (a - b));\n        System.out.println(\"Multiply: \" + (a * b));\n        System.out.println(\"Divide: \" + (a / b));\n        System.out.println(\"Modulus: \" + (a % b));\n    }\n}","output":"Add: 19\nSubtract: 11\nMultiply: 60\nDivide: 3\nModulus: 3","explanation":"Integer division (15/4) gives 3, not 3.75, because both operands are integers. Modulus (%) gives the remainder: 15 divided by 4 leaves remainder 3."},
        {"title":"Comparison and Logical Operators","code":"public class Main {\n    public static void main(String[] args) {\n        int age = 20;\n        boolean hasID = true;\n        \n        System.out.println(\"Is adult: \" + (age >= 18));\n        System.out.println(\"Can enter: \" + (age >= 18 && hasID));\n        System.out.println(\"Is teenager: \" + (age >= 13 && age < 18));\n    }\n}","output":"Is adult: true\nCan enter: true\nIs teenager: false","explanation":"Comparison operators return boolean values. The && (AND) operator requires both conditions to be true. Here age is 20, so >= 18 is true, and hasID is true, so both conditions pass."}
    ],
    "java_control_flow": [
        {"title":"if-else Decision Making","code":"public class Main {\n    public static void main(String[] args) {\n        int score = 75;\n        \n        if (score >= 90) {\n            System.out.println(\"Grade: A\");\n        } else if (score >= 80) {\n            System.out.println(\"Grade: B\");\n        } else if (score >= 70) {\n            System.out.println(\"Grade: C\");\n        } else {\n            System.out.println(\"Grade: F\");\n        }\n    }\n}","output":"Grade: C","explanation":"The program checks conditions from top to bottom. Score 75 fails >= 90 and >= 80, but passes >= 70, so it prints Grade C. Once a condition is true, the rest are skipped."},
        {"title":"Switch Statement","code":"public class Main {\n    public static void main(String[] args) {\n        String day = \"Wednesday\";\n        \n        switch (day) {\n            case \"Monday\":\n            case \"Tuesday\":\n            case \"Wednesday\":\n            case \"Thursday\":\n            case \"Friday\":\n                System.out.println(day + \" is a weekday\");\n                break;\n            default:\n                System.out.println(day + \" is a weekend\");\n        }\n    }\n}","output":"Wednesday is a weekday","explanation":"Multiple cases can share the same code block by stacking them. The break statement prevents fall-through to the next case. The default block handles any unmatched value."}
    ],
    "java_loops": [
        {"title":"for Loop - Print Numbers","code":"public class Main {\n    public static void main(String[] args) {\n        for (int i = 1; i <= 5; i++) {\n            System.out.println(\"Number: \" + i);\n        }\n    }\n}","output":"Number: 1\nNumber: 2\nNumber: 3\nNumber: 4\nNumber: 5","explanation":"The for loop starts i at 1, checks if i <= 5 before each iteration, and increments i by 1 after each iteration. It runs 5 times total."},
        {"title":"while Loop - Sum Until 100","code":"public class Main {\n    public static void main(String[] args) {\n        int sum = 0;\n        int num = 1;\n        \n        while (sum + num <= 100) {\n            sum += num;\n            num++;\n        }\n        \n        System.out.println(\"Sum: \" + sum);\n        System.out.println(\"Last number added: \" + (num - 1));\n    }\n}","output":"Sum: 91\nLast number added: 13","explanation":"The while loop keeps adding numbers (1+2+3+...) until the sum would exceed 100. It stops at 91 because adding 14 would make it 105."}
    ],
    "java_arrays": [
        {"title":"Array Operations","code":"public class Main {\n    public static void main(String[] args) {\n        int[] scores = {85, 92, 78, 95, 88};\n        \n        // Find maximum\n        int max = scores[0];\n        for (int s : scores) {\n            if (s > max) max = s;\n        }\n        \n        System.out.println(\"Scores: 85, 92, 78, 95, 88\");\n        System.out.println(\"Max score: \" + max);\n        System.out.println(\"Array length: \" + scores.length);\n    }\n}","output":"Scores: 85, 92, 78, 95, 88\nMax score: 95\nArray length: 5","explanation":"We use a for-each loop to iterate through the array and track the maximum value. The .length property gives the number of elements."}
    ],
    "java_strings": [
        {"title":"String Methods","code":"public class Main {\n    public static void main(String[] args) {\n        String text = \"  Hello, Java World!  \";\n        \n        System.out.println(\"Original: '\" + text + \"'\");\n        System.out.println(\"Trimmed: '\" + text.trim() + \"'\");\n        System.out.println(\"Upper: \" + text.trim().toUpperCase());\n        System.out.println(\"Length: \" + text.trim().length());\n        System.out.println(\"Contains Java: \" + text.contains(\"Java\"));\n        System.out.println(\"Replace: \" + text.trim().replace(\"Java\", \"C#\"));\n    }\n}","output":"Original: '  Hello, Java World!  '\nTrimmed: 'Hello, Java World!'\nUpper: HELLO, JAVA WORLD!\nLength: 18\nContains Java: true\nReplace: Hello, C# World!","explanation":"String methods return new strings (originals are unchanged because strings are immutable). trim() removes whitespace, toUpperCase() converts case, contains() checks for substrings."}
    ],
    "java_methods": [
        {"title":"Creating and Using Methods","code":"public class Main {\n    static int multiply(int a, int b) {\n        return a * b;\n    }\n    \n    static boolean isEven(int num) {\n        return num % 2 == 0;\n    }\n    \n    static void greet(String name) {\n        System.out.println(\"Hello, \" + name + \"!\");\n    }\n    \n    public static void main(String[] args) {\n        greet(\"Alice\");\n        System.out.println(\"5 x 3 = \" + multiply(5, 3));\n        System.out.println(\"Is 4 even? \" + isEven(4));\n        System.out.println(\"Is 7 even? \" + isEven(7));\n    }\n}","output":"Hello, Alice!\n5 x 3 = 15\nIs 4 even? true\nIs 7 even? false","explanation":"We define three methods: multiply returns an int, isEven returns a boolean, and greet returns void (nothing). Each method has a clear purpose and can be called multiple times with different arguments."}
    ],
    "java_oop_basics": [
        {"title":"Creating a Class and Object","code":"class Dog {\n    String name;\n    int age;\n    \n    Dog(String name, int age) {\n        this.name = name;\n        this.age = age;\n    }\n    \n    void bark() {\n        System.out.println(name + \" says: Woof!\");\n    }\n    \n    void info() {\n        System.out.println(name + \" is \" + age + \" years old\");\n    }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Dog d1 = new Dog(\"Buddy\", 3);\n        Dog d2 = new Dog(\"Max\", 5);\n        d1.bark();\n        d2.bark();\n        d1.info();\n    }\n}","output":"Buddy says: Woof!\nMax says: Woof!\nBuddy is 3 years old","explanation":"The Dog class is a blueprint with fields (name, age) and methods (bark, info). The constructor initializes fields when creating objects. d1 and d2 are separate objects with their own data."}
    ],
    "java_inheritance": [
        {"title":"Inheriting from a Parent Class","code":"class Animal {\n    String name;\n    Animal(String name) { this.name = name; }\n    void eat() { System.out.println(name + \" is eating\"); }\n}\n\nclass Cat extends Animal {\n    Cat(String name) { super(name); }\n    void meow() { System.out.println(name + \" says: Meow!\"); }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Cat c = new Cat(\"Whiskers\");\n        c.eat();   // inherited from Animal\n        c.meow();  // defined in Cat\n    }\n}","output":"Whiskers is eating\nWhiskers says: Meow!","explanation":"Cat extends Animal, so it inherits the eat() method and name field. super(name) calls the parent constructor. Cat also adds its own meow() method."}
    ],
    "java_polymorphism": [
        {"title":"Method Overriding","code":"class Shape {\n    void draw() { System.out.println(\"Drawing a shape\"); }\n}\nclass Circle extends Shape {\n    void draw() { System.out.println(\"Drawing a circle: O\"); }\n}\nclass Square extends Shape {\n    void draw() { System.out.println(\"Drawing a square: []\"); }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Shape s1 = new Circle();\n        Shape s2 = new Square();\n        s1.draw();\n        s2.draw();\n    }\n}","output":"Drawing a circle: O\nDrawing a square: []","explanation":"Both s1 and s2 are declared as Shape, but they hold Circle and Square objects. At runtime, Java calls the correct overridden draw() method for each actual object type. This is polymorphism."}
    ],
    "java_interfaces": [
        {"title":"Implementing an Interface","code":"interface Playable {\n    void play();\n    void stop();\n}\n\nclass MusicPlayer implements Playable {\n    public void play() { System.out.println(\"Playing music...\"); }\n    public void stop() { System.out.println(\"Music stopped.\"); }\n}\n\nclass VideoPlayer implements Playable {\n    public void play() { System.out.println(\"Playing video...\"); }\n    public void stop() { System.out.println(\"Video stopped.\"); }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Playable p1 = new MusicPlayer();\n        Playable p2 = new VideoPlayer();\n        p1.play();\n        p2.play();\n        p1.stop();\n    }\n}","output":"Playing music...\nPlaying video...\nMusic stopped.","explanation":"The Playable interface defines the contract (play and stop). Both MusicPlayer and VideoPlayer implement it differently. We can treat both as Playable, allowing flexible code."}
    ],
    "java_exceptions": [
        {"title":"Handling Exceptions","code":"public class Main {\n    public static void main(String[] args) {\n        try {\n            int[] nums = {1, 2, 3};\n            System.out.println(nums[5]); // error!\n        } catch (ArrayIndexOutOfBoundsException e) {\n            System.out.println(\"Error: Index out of bounds!\");\n            System.out.println(\"Message: \" + e.getMessage());\n        } finally {\n            System.out.println(\"This always runs.\");\n        }\n        System.out.println(\"Program continues...\");\n    }\n}","output":"Error: Index out of bounds!\nMessage: Index 5 out of bounds for length 3\nThis always runs.\nProgram continues...","explanation":"Accessing index 5 in a 3-element array throws an exception. The catch block handles it gracefully instead of crashing. The finally block runs regardless. The program continues normally after."}
    ],
    "java_collections": [
        {"title":"ArrayList and HashMap","code":"import java.util.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        // ArrayList\n        ArrayList<String> fruits = new ArrayList<>();\n        fruits.add(\"Apple\");\n        fruits.add(\"Banana\");\n        fruits.add(\"Cherry\");\n        System.out.println(\"Fruits: \" + fruits);\n        System.out.println(\"First: \" + fruits.get(0));\n        \n        // HashMap\n        HashMap<String, Integer> ages = new HashMap<>();\n        ages.put(\"Alice\", 25);\n        ages.put(\"Bob\", 30);\n        System.out.println(\"Ages: \" + ages);\n        System.out.println(\"Alice's age: \" + ages.get(\"Alice\"));\n    }\n}","output":"Fruits: [Apple, Banana, Cherry]\nFirst: Apple\nAges: {Alice=25, Bob=30}\nAlice's age: 25","explanation":"ArrayList stores ordered elements that can grow dynamically. HashMap stores key-value pairs for fast lookup. Unlike arrays, collections resize automatically and provide powerful built-in methods."}
    ],
    "java_generics": [
        {"title":"Generic Class","code":"class Box<T> {\n    T item;\n    void set(T item) { this.item = item; }\n    T get() { return item; }\n}\n\npublic class Main {\n    public static void main(String[] args) {\n        Box<String> stringBox = new Box<>();\n        stringBox.set(\"Hello Generics\");\n        System.out.println(\"String Box: \" + stringBox.get());\n        \n        Box<Integer> intBox = new Box<>();\n        intBox.set(42);\n        System.out.println(\"Integer Box: \" + intBox.get());\n    }\n}","output":"String Box: Hello Generics\nInteger Box: 42","explanation":"The Box class uses a type parameter T. When we create Box<String>, T becomes String. When we create Box<Integer>, T becomes Integer. One class works safely with any type."}
    ],
    "java_streams": [
        {"title":"Stream Operations","code":"import java.util.*;\nimport java.util.stream.*;\n\npublic class Main {\n    public static void main(String[] args) {\n        List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5, 6, 7, 8, 9, 10);\n        \n        List<Integer> evens = nums.stream()\n            .filter(n -> n % 2 == 0)\n            .collect(Collectors.toList());\n        System.out.println(\"Even numbers: \" + evens);\n        \n        int sum = nums.stream()\n            .reduce(0, Integer::sum);\n        System.out.println(\"Sum: \" + sum);\n    }\n}","output":"Even numbers: [2, 4, 6, 8, 10]\nSum: 55","explanation":"Stream's filter() keeps only elements matching the condition. reduce() combines all elements into one value. Streams use lambda expressions for concise, readable data processing."}
    ],
    "java_advanced": [
        {"title":"Multithreading","code":"public class Main {\n    public static void main(String[] args) {\n        Thread t1 = new Thread(() -> {\n            for (int i = 1; i <= 3; i++)\n                System.out.println(\"Thread 1: \" + i);\n        });\n        Thread t2 = new Thread(() -> {\n            for (int i = 1; i <= 3; i++)\n                System.out.println(\"Thread 2: \" + i);\n        });\n        t1.start();\n        t2.start();\n    }\n}","output":"Thread 1: 1\nThread 1: 2\nThread 2: 1\nThread 1: 3\nThread 2: 2\nThread 2: 3","explanation":"Two threads run concurrently. The exact output order may vary because threads execute independently. Lambda expressions create Runnable implementations concisely. start() begins execution in a new thread."}
    ],
    "java_interview": [
        {"title":"Common Interview: String Reversal","code":"public class Main {\n    static String reverse(String str) {\n        StringBuilder sb = new StringBuilder(str);\n        return sb.reverse().toString();\n    }\n    \n    static boolean isPalindrome(String str) {\n        String reversed = reverse(str.toLowerCase());\n        return str.toLowerCase().equals(reversed);\n    }\n    \n    public static void main(String[] args) {\n        System.out.println(\"Reversed 'Hello': \" + reverse(\"Hello\"));\n        System.out.println(\"Is 'racecar' palindrome: \" + isPalindrome(\"racecar\"));\n        System.out.println(\"Is 'hello' palindrome: \" + isPalindrome(\"hello\"));\n    }\n}","output":"Reversed 'Hello': olleH\nIs 'racecar' palindrome: true\nIs 'hello' palindrome: false","explanation":"StringBuilder.reverse() efficiently reverses strings. A palindrome reads the same forwards and backwards. We convert to lowercase for case-insensitive comparison. These are classic interview questions."}
    ]
}

# Apply Java examples
for k, examples in java_ex.items():
    if k in data['java']['content'] and 'structured' in data['java']['content'][k]:
        data['java']['content'][k]['structured']['examples'] = examples

nj = json.dumps(data, indent=2)
with open(filepath, 'w', encoding='utf-8') as f: f.write(pc + nj + sf)
print("Java examples updated for all 18 topics!")
