def run():
    from core.models import Question

    # Flush existing SQL questions to ensure exactly 40 hard ones
    Question.objects.filter(language='Sql').delete()

    sql_qna = [
        # Window Functions & Analytics (1-10)
        ("What does the DENSE_RANK() function do compared to RANK()?", "It explicitly skips numbers after ties.", "It does not skip numbers after ties.", "It averages the tie positions.", "It returns random ranks for ties.", "It does not skip numbers after ties."),
        ("How do you select the top 3 highest paid employees per department?", "GROUP BY dept, MIN(salary)", "GROUP BY dept LIMIT 3", "Using ROW_NUMBER() OVER(PARTITION BY dept ORDER BY salary DESC)", "Using RANK() OVER(ORDER BY salary DESC)", "Using ROW_NUMBER() OVER(PARTITION BY dept ORDER BY salary DESC)"),
        ("Which clause is required when using aggregate functions over a sliding window frame?", "GROUP BY", "WINDOW", "PARTITION BY", "OVER", "OVER"),
        ("What is the default windowing frame in PostgreSQL if an ORDER BY is used in the OVER clause?", "RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW", "ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING", "RANGE BETWEEN CURRENT ROW AND UNBOUNDED FOLLOWING", "ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING", "RANGE BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW"),
        ("Which function computes the cumulative distribution of a value in a group?", "CUME_DIST()", "PERCENT_RANK()", "NTILE()", "CUMULATIVE_PERCENT()", "CUME_DIST()"),
        ("What will NTILE(4) do if applied to a partition of 6 rows?", "Throws a syntax error", "Assigns buckets 1,1,2,2,3,4", "Assigns buckets 1,1,2,2,3,3", "Assigns buckets 1,2,3,4,null,null", "Assigns buckets 1,1,2,2,3,4"),
        ("What is the primary difference between LEAD() and LAG()?", "LAG returns the preceding row, LEAD returns the subsequent", "LEAD returns the preceding row, LAG returns the subsequent", "They perform the exact same function depending on ORDER BY direction", "LAG is standard ANSI SQL, LEAD is PostgreSQL specific", "LAG returns the preceding row, LEAD returns the subsequent"),
        ("How is the FIRST_VALUE() function evaluated?", "Over the entire partition regardless of the window frame", "Respecting the window frame starting from the first unbounded preceding", "Only within the bounds of a GROUP BY segment", "By returning the alphabetically lowest string", "Respecting the window frame starting from the first unbounded preceding"),
        ("Can Window functions be used in a WHERE clause?", "Yes, universally", "Only if the database is strictly ANSI SQL compliant", "No, they operate and are evaluated after the WHERE clause", "Yes, but only with a subquery wrapper", "No, they operate and are evaluated after the WHERE clause"),
        ("In Oracle/SQL Server, what does the NTH_VALUE() function permit?", "Retrieving the N-th statistical median", "Retrieving an arbitrary row strictly within a specified window frame", "Selecting the Nth table column", "Multiplying values sequentially", "Retrieving an arbitrary row strictly within a specified window frame"),

        # Complex Joins & Set Operations (11-20)
        ("What is the result of a FULL OUTER JOIN when no matches are found in both tables?", "No rows are returned", "Cartesian Product", "Rows from both tables with NULLs in unmatched columns", "Throws a fatal referential integrity error", "Rows from both tables with NULLs in unmatched columns"),
        ("Explain the behavior of a NATURAL JOIN.", "It mandates an arbitrary JOIN syntax explicitly", "It implicitly joins identical column names without an ON clause", "It naturally ignores NULLs in the table", "It is synonymous with an INNER JOIN on primary keys only", "It implicitly joins identical column names without an ON clause"),
        ("When using UNION ALL vs UNION, which is typically faster and why?", "UNION ALL is faster because it does not deduplicate and sort", "UNION is faster because it applies an index scan", "UNION is faster because it handles smaller result sets securely", "UNION ALL is mathematically equivalent in time complexiy", "UNION ALL is faster because it does not deduplicate and sort"),
        ("What happens if you run an INTERSECT on two large tables?", "Returns all overlapping rows while deduplicating duplicates", "Returns a Cartesian combination of rows mathematically", "Returns all completely non-matching rows", "Always throws memory overflow error on tables >1GB", "Returns all overlapping rows while deduplicating duplicates"),
        ("Can a CROSS JOIN be implicitly created?", "No, ANSI strictly requires the CROSS JOIN declaration", "Yes, by separating tables with commas in the FROM clause without a WHERE", "Yes, but only in NoSQL databases", "Yes, by utilizing an INNER JOIN without an ORDER BY", "Yes, by separating tables with commas in the FROM clause without a WHERE"),
        ("How does a SELF JOIN practically differ from a standard JOIN?", "It necessitates table aliasing to prevent namespace conflicts", "It mathematically squares the temporal complexity", "It prohibits the usage of OUTER modifiers", "It ignores Primary Keys fundamentally", "It necessitates table aliasing to prevent namespace conflicts"),
        ("What is the fundamental constraint of the EXCEPT (or MINUS) operator?", "Both SELECT arrays must output identical column quantities and matching data types", "The right table must inherently carry a larger row count than the left", "It cannot be combined directly with a WHERE clause natively", "It is exclusively a MySQL proprietary syntactical function", "Both SELECT arrays must output identical column quantities and matching data types"),
        ("Which JOIN acts strictly as a filtering mechanism producing only rows in table A that match table B, returning distinct A rows?", "FULL OUTER JOIN", "SEMI JOIN (usually via EXISTS)", "ANTI JOIN (usually via NOT IN)", "NATURAL RIGHT JOIN", "SEMI JOIN (usually via EXISTS)"),
        ("If Table A has 5 rows and Table B has 4 rows, the maximum possible output of an INNER JOIN is:", "9 Rows", "4 Rows", "20 Rows", "5 Rows", "20 Rows"),
        ("What behavior dictates a LEFT JOIN matching multiple rows in the right table?", "The left row is duplicated for each right-side match", "A generic GROUP BY is instantiated to condense the results", "The SQL runtime crashes", "It throws a syntax parsing error automatically", "The left row is duplicated for each right-side match"),

        # Optimization & Indexing (21-30)
        ("What is the primary architectural difference between a Clustered and Non-Clustered Index?", "Clustered indexes alter the physical storage order of the rows", "Non-clustered indexes cannot hold more than one column", "Clustered indexes are slower on SELECT but faster on UPDATE", "There is no functional difference in Oracle databases", "Clustered indexes alter the physical storage order of the rows"),
        ("In B-Tree indexing algorithms, what does the factor of 'Selectivity' determine?", "The permission level of the SELECT query", "The uniqueness ratio of the column, influencing index effectiveness", "The algorithmic speed of the hard-drive memory sweep", "The total size of the index matrix in MBs", "The uniqueness ratio of the column, influencing index effectiveness"),
        ("Why does utilizing 'SELECT *' negatively impact database performance securely?", "It bypasses query covering indexes and triggers heavier I/O disk reads", "It randomly scrambles the return order", "It prevents caching of any type", "It triggers locking mechanisms on all connected tables universally", "It bypasses query covering indexes and triggers heavier I/O disk reads"),
        ("When might a database engine intentionally bypass an existing index?", "When the index is older than 24 hours", "When statistics indicate performing a Full Table Scan will be cheaper computationally", "When executing inside a stored procedure", "Never; if an index exists, it is universally mandatory", "When statistics indicate performing a Full Table Scan will be cheaper computationally"),
        ("What is a 'Covering Index' in query optimization?", "An index that conceals data from unauthorized roles", "An index that contains every column requested by the SELECT, avoiding table lookups", "A secondary index built on top of a clustered index exclusively", "An index dedicated to temporal tables", "An index that contains every column requested by the SELECT, avoiding table lookups"),
        ("How does applying a function to an indexed column (e.g., WHERE YEAR(date) = 2023) affect execution?", "It heavily accelerates the process", "It renders the standard B-Tree index unusable (causes a full scan)", "It automatically generates a computed column logically", "It caches the results seamlessly", "It renders the standard B-Tree index unusable (causes a full scan)"),
        ("What executes faster theoretically: EXISTS or IN for extensive subqueries?", "IN, because it caches the absolute list", "EXISTS, because it short-circuits evaluation once a match is identified", "They are universally optimized identically in all modern databases", "IN, because EXISTS requires Cartesian mathematics", "EXISTS, because it short-circuits evaluation once a match is identified"),
        ("Describe a 'Bookmark Lookup' or 'Key Lookup'.", "An efficient way to store physical disk addresses", "An expensive operation where the engine finds index matched rows, then seeks the table for missing columns", "A specific caching technique implemented by PostgreSQL servers", "An indexed view materialization factor", "An expensive operation where the engine finds index matched rows, then seeks the table for missing columns"),
        ("What does the EXPLAIN or EXPLAIN PLAN statement strictly provide?", "Executes the query and times the exact milliseconds", "Exposes the internal execution graph and algorithmic choices of the optimizer", "Optimizes the syntax string mathematically", "Truncates the table logically to predict memory consumption", "Exposes the internal execution graph and algorithmic choices of the optimizer"),
        ("In regards to normalization, what characterizes the 3rd Normal Form (3NF)?", "The removal of strictly transitively dependent non-key attributes", "The absolute elimination of all primary keys", "The conversion of numeric types to relational strings mathematically", "The merging of dimension tables into facts exclusively", "The removal of strictly transitively dependent non-key attributes"),

        # Advanced Traps & Syntax (31-40)
        ("What does the COALESCE() function formally do?", "Joins two tables logically without ON syntax", "Calculates statistical medians across arrays", "Returns the first non-NULL expression from an argumentative list", "Converts strings to standardized date objects natively", "Returns the first non-NULL expression from an argumentative list"),
        ("When parsing the logical processing order of a query, which clause is evaluated absolutely first?", "SELECT", "ORDER BY", "FROM", "WHERE", "FROM"),
        ("At what logical stage are column aliases generated and thus referable?", "Directly inside the WHERE clause natively", "Concurrently inside the GROUP BY block", "Before the query is parsed completely", "In the SELECT phase, rendering them usable only in ORDER BY (usually)", "In the SELECT phase, rendering them usable only in ORDER BY (usually)"),
        ("How does the TRUNCATE TABLE command intrinsically differ from DELETE?", "TRUNCATE fires individual row triggers extensively", "TRUNCATE is a DDL operation that resets the high-water mark and isn't typically logged per row", "DELETE cannot be rolled back logically in any transaction", "TRUNCATE requires a WHERE statement conditionally", "TRUNCATE is a DDL operation that resets the high-water mark and isn't typically logged per row"),
        ("What does the WITH clause (Common Table Expression / CTE) provide primarily?", "Absolute physical materialization of temporary tables on disk", "A readable, recursive, and temporarily isolated query result reference", "An automated looping mechanism for dynamic syntax generation", "Permanent metadata updates securely", "A readable, recursive, and temporarily isolated query result reference"),
        ("How can you uniquely prevent the Division By Zero error in complex T-SQL/PostgreSQL?", "WRAP with TRY_CATCH universally", "Use NULLIF(denominator, 0) universally to return NULL instead of a fatal error", "It is completely impossible to bypass", "Switch the execution to an INNER JOIN mapping exclusively", "Use NULLIF(denominator, 0) universally to return NULL instead of a fatal error"),
        ("What is the precise result of 'SELECT NULL = NULL'?", "TRUE", "FALSE", "Syntax Error", "UNKNOWN / NULL", "UNKNOWN / NULL"),
        ("Which function strictly returns strings concatenated logically mapped over multiple rows?", "STRING_AGG() / GROUP_CONCAT()", "CONCAT()", "COALESCE()", "MERGE()", "STRING_AGG() / GROUP_CONCAT()"),
        ("Explain the structural purpose of the HAVING clause.", "To pre-filter datasets prior to aggregations", "To filter datasets directly based strictly on aggregated mathematical functions", "To replace the WHERE clause entirely in subqueries universally", "To securely invoke indexing systems intelligently", "To filter datasets directly based strictly on aggregated mathematical functions"),
        ("What is the primary danger when utilizing Dynamic SQL (EXEC() or PREPARE)?", "Memory overflow from large syntax tables universally", "Significant vulnerabilities targeting SQL Injection if unprotected conceptually", "Permanent locking of clustered indexes absolutely", "Failure to utilize secondary databases logically", "Significant vulnerabilities targeting SQL Injection if unprotected conceptually"),
    ]

    objects = []
    for q in sql_qna:
        objects.append(
            Question(
                language='Sql',
                level='Advanced',
                question_text=q[0],
                option1=q[1], option2=q[2], option3=q[3], option4=q[4],
                correct_answer=q[5]
            )
        )
    Question.objects.bulk_create(objects)
    print("Successfully injected 40 Advanced SQL Multi-Choice Questions!")
