# Generated by Django 4.2.28 on 2026-03-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='activity_data',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='weak_topics',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='duration',
            field=models.CharField(default='1 Month', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpreference',
            name='learning_goal',
            field=models.CharField(default='General Learning', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpreference',
            name='study_time',
            field=models.CharField(default='1 Hour', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='level',
            field=models.CharField(max_length=50),
        ),
    ]
