# Generated by Django 4.2.28 on 2026-03-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_useractivity_user_userpreference_activity_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.CharField(default='Beginner', max_length=20),
            preserve_default=False,
        ),
    ]
