# Generated by Django 4.2.28 on 2026-03-20 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='activity_count',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='learning_goal',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='study_time',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='weak_topics',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='streak',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
