# Generated by Django 4.2.28 on 2026-03-20 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_remove_userpreference_activity_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='email',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='task_name',
        ),
        migrations.AddField(
            model_name='useractivity',
            name='task_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
