# Generated by Django 4.2.28 on 2026-04-25 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0009_aptitudequestion_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='task_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='activity_count',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='learning_goal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='study_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='weak_topics',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(default='Beginner', max_length=20),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
