# Generated by Django 4.2.28 on 2026-04-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_useractivity_email_useractivity_task_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aptitudequestion',
            old_name='question_text',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='aptitudequestion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='aptitudequestion',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='aptitudequestion',
            name='correct',
            field=models.CharField(default='A', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aptitudequestion',
            name='difficulty',
            field=models.CharField(default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='aptitudequestion',
            name='topic',
            field=models.CharField(default='General', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aptitudequestion',
            name='option_a',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aptitudequestion',
            name='option_b',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aptitudequestion',
            name='option_c',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aptitudequestion',
            name='option_d',
            field=models.TextField(),
        ),
    ]
