"""
Batch: C# (all 18 topics) — full textbook content with 3+ examples each
"""
import json, os
FILEPATH = os.path.join(os.path.dirname(__file__), '..', 'core', 'static', 'tracks_data.js')

def make_topic(intro, subtopics, key_concepts, examples, quiz, hands_on=None, problems=None):
    s = {"introduction": intro, "subtopics": subtopics, "key_concepts": key_concepts, "examples": examples}
    return {"structured": s, "concept_quiz": quiz, "hands_on": hands_on or {"title":"Try it!","description":"Practice the concept above.","hint":"Use the examples as a guide.","code":""}, "problem_solving": problems or []}

CSHARP_FIXES = {
    "cs_basics": make_topic(
        intro="<p><strong>C#</strong> (pronounced 'C-sharp') is a modern, object-oriented programming language developed by Microsoft as part of the <strong>.NET</strong> framework. Created by Anders Hejlsberg in 2000, C# combines the power of C++ with the simplicity of Java. It is the primary language for <strong>Unity game development</strong>, Windows desktop apps (WPF/WinForms), ASP.NET web backends, Xamarin mobile apps, and Azure cloud services. C# is statically typed, garbage-collected, and has evolved rapidly — adding async/await, LINQ, pattern matching, and records.</p>",
        subtopics=[
            {"title":"Program Structure","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>using System;\n\nclass Program {\n    static void Main(string[] args) {\n        Console.WriteLine(\"Hello, C#!\");\n    }\n}</pre><p>Every C# program has a <code>Main</code> method as the entry point. <code>using System;</code> imports the System namespace for <code>Console</code>.</p>"},
            {"title":"Modern C# (Top-Level Statements)","content":"<p>Since C# 9, you can write programs without the class/Main boilerplate:</p><pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>// Program.cs (C# 9+)\nConsole.WriteLine(\"Hello, Modern C#!\");</pre>"},
            {"title":"Data Types","content":"<p>Value types: <code>int</code>, <code>double</code>, <code>bool</code>, <code>char</code>, <code>decimal</code>. Reference types: <code>string</code>, arrays, classes. <code>var</code> enables type inference.</p><pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>int age = 25;\ndouble salary = 75000.50;\nbool isActive = true;\nstring name = \"Alice\";\nvar count = 42;  // compiler infers int</pre>"},
        ],
        key_concepts="<ul><li>C# runs on the <strong>.NET CLR</strong> (Common Language Runtime) — compiled to IL (Intermediate Language), then JIT-compiled to native code.</li><li><strong>Garbage collection</strong> — automatic memory management, no manual free().</li><li><strong>Namespaces</strong> organise code: <code>using System;</code>, <code>using System.Collections.Generic;</code></li><li><code>string</code> is a reference type but behaves like a value type (immutable).</li><li>C# is case-sensitive: <code>myVar</code> and <code>MyVar</code> are different.</li></ul>",
        examples=[
            {"title":"Hello World","code":"using System;\n\nclass Program {\n    static void Main() {\n        Console.WriteLine(\"Hello, World!\");\n        Console.WriteLine(\"C# version: \" + Environment.Version);\n    }\n}","output":"Hello, World!\nC# version: 8.0.0","explanation":"<p><code>Console.WriteLine</code> prints with a newline. <code>Environment.Version</code> shows the .NET runtime version.</p>"},
            {"title":"Variables & String Interpolation","code":"using System;\n\nclass Program {\n    static void Main() {\n        string name = \"Alice\";\n        int age = 25;\n        double gpa = 3.85;\n        \n        // String interpolation (C# 6+)\n        Console.WriteLine($\"{name} is {age} years old\");\n        Console.WriteLine($\"GPA: {gpa:F1}\");  // 1 decimal\n        \n        // Type inference with var\n        var message = \"Hello\";\n        Console.WriteLine($\"Type: {message.GetType()}\");\n    }\n}","output":"Alice is 25 years old\nGPA: 3.9\nType: System.String","explanation":"<p><code>$\"...\"</code> string interpolation is C#'s equivalent of Python f-strings — cleaner than concatenation.</p>"},
            {"title":"User Input & Parsing","code":"using System;\n\nclass Program {\n    static void Main() {\n        Console.Write(\"Enter your name: \");\n        string name = Console.ReadLine();\n        \n        Console.Write(\"Enter your age: \");\n        int age = int.Parse(Console.ReadLine());\n        \n        Console.WriteLine($\"Hello {name}, you'll be {age + 1} next year!\");\n    }\n}","output":"Enter your name: Bob\nEnter your age: 30\nHello Bob, you'll be 31 next year!","explanation":"<p><code>Console.ReadLine()</code> returns a string — use <code>int.Parse()</code> or <code>int.TryParse()</code> to convert to numbers safely.</p>"},
        ],
        quiz=[
            {"q":"What is the entry point of a C# program?","options":["start()","init()","Main()","Run()"],"answer":"Main()"},
            {"q":"Which keyword enables type inference in C#?","options":["auto","let","var","dynamic"],"answer":"var"},
            {"q":"C# runs on which runtime?","options":["JVM","V8","CLR (.NET)","CPython"],"answer":"CLR (.NET)"},
        ],
    ),
    "cs_variables": make_topic(
        intro="<p><strong>Variables</strong> in C# are strongly typed — every variable must have a declared type or use <code>var</code> for compiler inference. C# distinguishes between <strong>value types</strong> (stored on the stack: <code>int</code>, <code>double</code>, <code>bool</code>, <code>struct</code>) and <strong>reference types</strong> (stored on the heap: <code>string</code>, arrays, classes). Understanding this distinction is crucial for memory behaviour, equality checks, and performance in C#.</p>",
        subtopics=[
            {"title":"Value Types vs Reference Types","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>// Value types — copy on assignment\nint a = 10;\nint b = a;   // b is a copy\nb = 20;      // a is still 10\n\n// Reference types — share the same object\nint[] arr1 = {1, 2, 3};\nint[] arr2 = arr1;  // arr2 points to same array\narr2[0] = 99;       // arr1[0] is also 99!</pre>"},
            {"title":"Constants & Readonly","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>const double PI = 3.14159;    // compile-time constant\nreadonly int maxUsers = 100;  // runtime constant (set once)</pre>"},
            {"title":"Nullable Types","content":"<p>Value types can't normally be null. Add <code>?</code> to allow null: <code>int? age = null;</code> Use <code>??</code> (null-coalescing) for defaults: <code>int val = age ?? 0;</code></p>"},
        ],
        key_concepts="<ul><li><code>int</code>, <code>double</code>, <code>bool</code>, <code>char</code>, <code>struct</code> are value types (copied on assignment).</li><li><code>string</code>, arrays, classes are reference types (shared reference).</li><li><code>const</code> is compile-time; <code>readonly</code> can be set in constructor.</li><li><code>int?</code> is nullable int — can hold null. <code>??</code> provides default for null.</li><li><code>default(T)</code> gives the default value: 0 for int, null for reference types.</li></ul>",
        examples=[
            {"title":"Type Sizes & Ranges","code":"using System;\n\nclass Program {\n    static void Main() {\n        Console.WriteLine($\"int:    {sizeof(int)} bytes, range: {int.MinValue} to {int.MaxValue}\");\n        Console.WriteLine($\"long:   {sizeof(long)} bytes\");\n        Console.WriteLine($\"float:  {sizeof(float)} bytes\");\n        Console.WriteLine($\"double: {sizeof(double)} bytes\");\n        Console.WriteLine($\"char:   {sizeof(char)} bytes\");\n        Console.WriteLine($\"bool:   {sizeof(bool)} byte\");\n    }\n}","output":"int:    4 bytes, range: -2147483648 to 2147483647\nlong:   8 bytes\nfloat:  4 bytes\ndouble: 8 bytes\nchar:   2 bytes\nbool:   1 byte","explanation":"<p>C# char is 2 bytes (Unicode/UTF-16), unlike C's 1-byte char. This supports international characters natively.</p>"},
            {"title":"Nullable & Null-Coalescing","code":"using System;\n\nclass Program {\n    static void Main() {\n        int? temperature = null;\n        Console.WriteLine($\"Temp: {temperature ?? -999}\");  // -999 (default)\n        \n        temperature = 72;\n        Console.WriteLine($\"Temp: {temperature ?? -999}\");  // 72\n        \n        Console.WriteLine($\"Has value: {temperature.HasValue}\");  // True\n        Console.WriteLine($\"Value: {temperature.Value}\");          // 72\n    }\n}","output":"Temp: -999\nTemp: 72\nHas value: True\nValue: 72","explanation":"<p><code>int?</code> wraps int in <code>Nullable&lt;int&gt;</code>. The <code>??</code> operator returns the left side if non-null, otherwise the right side.</p>"},
            {"title":"Value vs Reference Behaviour","code":"using System;\n\nclass Program {\n    static void Main() {\n        // Value type: independent copy\n        int x = 10;\n        int y = x;\n        y = 99;\n        Console.WriteLine($\"x={x}, y={y}\");  // x=10, y=99\n        \n        // Reference type: shared object\n        int[] a = {1, 2, 3};\n        int[] b = a;\n        b[0] = 999;\n        Console.WriteLine($\"a[0]={a[0]}, b[0]={b[0]}\");  // both 999\n    }\n}","output":"x=10, y=99\na[0]=999, b[0]=999","explanation":"<p>Value types copy values; reference types copy the reference (address). Modifying <code>b</code> affects <code>a</code> because they point to the same array.</p>"},
        ],
        quiz=[
            {"q":"In C#, string is a:","options":["Value type","Reference type","Primitive type","Struct type"],"answer":"Reference type"},
            {"q":"What does the ?? operator do?","options":["Null check","Provides default if null","Pattern matching","Type casting"],"answer":"Provides default if null"},
        ],
    ),
    "cs_operators": make_topic(
        intro="<p>C# provides a comprehensive set of operators: arithmetic (<code>+</code>, <code>-</code>, <code>*</code>, <code>/</code>, <code>%</code>), comparison (<code>==</code>, <code>!=</code>, <code>&lt;</code>, <code>&gt;</code>), logical (<code>&&</code>, <code>||</code>, <code>!</code>), null-conditional (<code>?.</code>, <code>??</code>), and pattern matching operators. C# also supports operator overloading — you can define how <code>+</code> or <code>==</code> works for your custom classes.</p>",
        subtopics=[
            {"title":"Arithmetic & Comparison","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>int a = 17, b = 5;\nConsole.WriteLine(a / b);   // 3 (integer division)\nConsole.WriteLine(a % b);   // 2 (remainder)\nConsole.WriteLine(a / (double)b); // 3.4 (float division)\n\nbool result = (a > b) && (b > 0);  // true</pre>"},
            {"title":"Null-Conditional & Null-Coalescing","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>string name = null;\nint? length = name?.Length;     // null (no crash!)\nint safeLen = name?.Length ?? 0; // 0\n\n// Null-coalescing assignment (C# 8+)\nname ??= \"Default\";  // assigns only if null</pre>"},
        ],
        key_concepts="<ul><li><code>?.</code> null-conditional: short-circuits to null if left side is null.</li><li><code>??</code> null-coalescing: provides a default value for null expressions.</li><li><code>??=</code> assigns only if the variable is null (C# 8+).</li><li><code>is</code> operator: pattern matching — <code>if (obj is string s)</code> tests and casts in one step.</li></ul>",
        examples=[
            {"title":"Arithmetic & Type Casting","code":"using System;\n\nclass Program {\n    static void Main() {\n        int a = 17, b = 5;\n        Console.WriteLine($\"{a} / {b} = {a / b}\");           // 3\n        Console.WriteLine($\"{a} / {b} = {(double)a / b}\");   // 3.4\n        Console.WriteLine($\"{a} % {b} = {a % b}\");           // 2\n        \n        // Compound assignment\n        a += 3;  // a = 20\n        a *= 2;  // a = 40\n        Console.WriteLine($\"a = {a}\");\n    }\n}","output":"17 / 5 = 3\n17 / 5 = 3.4\n17 % 5 = 2\na = 40","explanation":"<p>Integer division truncates. Cast to <code>double</code> for decimal results.</p>"},
            {"title":"Null-Safety Operators","code":"using System;\n\nclass Program {\n    static void Main() {\n        string text = null;\n        \n        // Without null-conditional: would crash\n        // int len = text.Length;  // NullReferenceException!\n        \n        // Safe approaches:\n        int? len = text?.Length;             // null\n        int safeLen = text?.Length ?? 0;     // 0\n        \n        text ??= \"Hello\";                   // assigns because text is null\n        Console.WriteLine($\"Text: {text}, Length: {text.Length}\");\n    }\n}","output":"Text: Hello, Length: 5","explanation":"<p><code>?.</code> prevents NullReferenceException — C#'s most common runtime error. <code>??=</code> assigns only when null.</p>"},
            {"title":"Pattern Matching with 'is'","code":"using System;\n\nclass Program {\n    static void Describe(object obj) {\n        if (obj is int n)\n            Console.WriteLine($\"Integer: {n * 2}\");\n        else if (obj is string s)\n            Console.WriteLine($\"String: {s.ToUpper()}\");\n        else if (obj is null)\n            Console.WriteLine(\"null value\");\n        else\n            Console.WriteLine($\"Other: {obj.GetType()}\");\n    }\n    \n    static void Main() {\n        Describe(42);\n        Describe(\"hello\");\n        Describe(null);\n        Describe(3.14);\n    }\n}","output":"Integer: 84\nString: HELLO\nnull value\nOther: System.Double","explanation":"<p><code>is</code> pattern matching tests the type and declares a typed variable in one step — much cleaner than casting.</p>"},
        ],
        quiz=[
            {"q":"What does ?. do in C#?","options":["Checks equality","Accesses member only if not null","Converts type","Creates nullable"],"answer":"Accesses member only if not null"},
            {"q":"Which operator assigns only if the variable is null?","options":["??","?.","??=","?:"],"answer":"??="},
        ],
    ),
    "cs_control": make_topic(
        intro="<p>C# control flow statements determine program execution paths: <code>if</code>/<code>else</code>, <code>switch</code> (including modern pattern-matching switch expressions), and the ternary operator. C# 8+ introduced <strong>switch expressions</strong> — a powerful, concise alternative to traditional switch statements that supports pattern matching, making complex conditional logic readable and type-safe.</p>",
        subtopics=[
            {"title":"if / else if / else","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>int score = 85;\nif (score >= 90) Console.WriteLine(\"A\");\nelse if (score >= 80) Console.WriteLine(\"B\");\nelse if (score >= 70) Console.WriteLine(\"C\");\nelse Console.WriteLine(\"F\");</pre>"},
            {"title":"Switch Expressions (C# 8+)","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>string grade = score switch {\n    >= 90 => \"A\",\n    >= 80 => \"B\",\n    >= 70 => \"C\",\n    _     => \"F\"   // default\n};\nConsole.WriteLine(grade);</pre>"},
        ],
        key_concepts="<ul><li>Switch expressions (C# 8+) are concise, return values directly, and support pattern matching.</li><li>Traditional switch requires <code>break;</code> (no fall-through allowed in C#, unlike C).</li><li>C# switch supports strings, enums, and pattern matching — more flexible than C/Java.</li></ul>",
        examples=[
            {"title":"Grade Calculator","code":"using System;\n\nclass Program {\n    static void Main() {\n        int score = 82;\n        string grade = score switch {\n            >= 90 => \"A - Excellent\",\n            >= 80 => \"B - Good\",\n            >= 70 => \"C - Average\",\n            >= 60 => \"D - Below Average\",\n            _     => \"F - Fail\"\n        };\n        Console.WriteLine($\"Score: {score} -> {grade}\");\n    }\n}","output":"Score: 82 -> B - Good","explanation":"<p>Switch expressions return a value directly — no need for a variable and break statements.</p>"},
            {"title":"Day of Week (Traditional Switch)","code":"using System;\n\nclass Program {\n    static void Main() {\n        DayOfWeek today = DateTime.Now.DayOfWeek;\n        \n        switch (today) {\n            case DayOfWeek.Saturday:\n            case DayOfWeek.Sunday:\n                Console.WriteLine($\"{today}: Weekend!\");\n                break;\n            default:\n                Console.WriteLine($\"{today}: Workday\");\n                break;\n        }\n    }\n}","output":"Friday: Workday","explanation":"<p>Enum-based switch with grouped cases (Saturday and Sunday share the same body).</p>"},
            {"title":"Ternary & Null-Coalescing","code":"using System;\n\nclass Program {\n    static void Main() {\n        int age = 20;\n        string status = (age >= 18) ? \"Adult\" : \"Minor\";\n        Console.WriteLine($\"Age {age}: {status}\");\n        \n        string name = null;\n        string display = name ?? \"Anonymous\";\n        Console.WriteLine($\"User: {display}\");\n    }\n}","output":"Age 20: Adult\nUser: Anonymous","explanation":"<p>Ternary for inline conditionals; <code>??</code> for null fallback — both reduce boilerplate.</p>"},
        ],
        quiz=[
            {"q":"C# switch requires 'break' because:","options":["Fall-through is not allowed","It's optional","It ends the program","It returns a value"],"answer":"Fall-through is not allowed"},
            {"q":"Switch expressions were introduced in:","options":["C# 6","C# 7","C# 8","C# 10"],"answer":"C# 8"},
        ],
    ),
    "cs_loops": make_topic(
        intro="<p>C# provides four loop constructs: <code>for</code> (counter-based), <code>foreach</code> (iteration over collections), <code>while</code> (condition-first), and <code>do-while</code> (body-first). The <code>foreach</code> loop is the most idiomatic C# loop — it works with any <code>IEnumerable</code> type (arrays, lists, dictionaries, LINQ queries) and is the preferred way to iterate collections.</p>",
        subtopics=[
            {"title":"for & foreach","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>// for loop\nfor (int i = 0; i < 5; i++)\n    Console.Write($\"{i} \");  // 0 1 2 3 4\n\n// foreach — idiomatic C# iteration\nstring[] fruits = {\"Apple\", \"Banana\", \"Cherry\"};\nforeach (string fruit in fruits)\n    Console.WriteLine(fruit);</pre>"},
            {"title":"while & do-while","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>int n = 5;\nwhile (n > 0) {\n    Console.Write($\"{n} \");\n    n--;\n}\n// 5 4 3 2 1\n\ndo {\n    Console.Write(\"Runs at least once\");\n} while (false);</pre>"},
        ],
        key_concepts="<ul><li><code>foreach</code> works with any <code>IEnumerable</code> — arrays, List, Dictionary, LINQ results.</li><li><code>break</code> exits the loop; <code>continue</code> skips to next iteration.</li><li>Avoid modifying a collection inside <code>foreach</code> — causes <code>InvalidOperationException</code>.</li></ul>",
        examples=[
            {"title":"Foreach with Collections","code":"using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        var scores = new Dictionary<string, int> {\n            {\"Alice\", 95}, {\"Bob\", 87}, {\"Charlie\", 92}\n        };\n        \n        foreach (var pair in scores)\n            Console.WriteLine($\"{pair.Key}: {pair.Value}\");\n    }\n}","output":"Alice: 95\nBob: 87\nCharlie: 92","explanation":"<p><code>foreach</code> iterates key-value pairs in a Dictionary. <code>var</code> infers <code>KeyValuePair&lt;string, int&gt;</code>.</p>"},
            {"title":"FizzBuzz","code":"using System;\n\nclass Program {\n    static void Main() {\n        for (int i = 1; i <= 15; i++) {\n            if (i % 15 == 0) Console.WriteLine(\"FizzBuzz\");\n            else if (i % 3 == 0) Console.WriteLine(\"Fizz\");\n            else if (i % 5 == 0) Console.WriteLine(\"Buzz\");\n            else Console.WriteLine(i);\n        }\n    }\n}","output":"1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz","explanation":"<p>Classic interview problem: test divisibility order matters — check 15 before 3 and 5.</p>"},
            {"title":"Sum with While Loop","code":"using System;\n\nclass Program {\n    static void Main() {\n        int sum = 0, i = 1;\n        while (i <= 100) {\n            sum += i;\n            i++;\n        }\n        Console.WriteLine($\"Sum 1..100 = {sum}\");\n    }\n}","output":"Sum 1..100 = 5050","explanation":"<p>Accumulator pattern with while loop. Result matches Gauss's formula: n*(n+1)/2.</p>"},
        ],
        quiz=[
            {"q":"Which loop is best for iterating collections in C#?","options":["for","while","foreach","do-while"],"answer":"foreach"},
            {"q":"What happens if you modify a list inside foreach?","options":["Nothing","InvalidOperationException","Skips elements","Adds duplicates"],"answer":"InvalidOperationException"},
        ],
    ),
    "cs_methods": make_topic(
        intro="<p><strong>Methods</strong> in C# are functions defined inside classes. They support <code>ref</code> (pass by reference), <code>out</code> (return multiple values), <code>params</code> (variable arguments), default parameter values, named arguments, and method overloading (same name, different parameter types). C# also supports <strong>expression-bodied members</strong> (<code>=></code>) for concise one-line methods and <strong>local functions</strong> (functions inside functions).</p>",
        subtopics=[
            {"title":"Method Syntax & Overloading","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>int Add(int a, int b) => a + b;\ndouble Add(double a, double b) => a + b;  // overloaded\nint Add(int a, int b, int c) => a + b + c; // overloaded</pre>"},
            {"title":"ref, out, and params","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>void Swap(ref int a, ref int b) { int t=a; a=b; b=t; }\n\nbool TryDivide(int a, int b, out double result) {\n    if (b == 0) { result = 0; return false; }\n    result = (double)a / b;\n    return true;\n}\n\nint Sum(params int[] nums) => nums.Sum();</pre>"},
        ],
        key_concepts="<ul><li><code>ref</code>: pass by reference — caller and method share the same variable.</li><li><code>out</code>: method must assign a value — used for returning multiple values.</li><li><code>params</code>: accepts variable number of arguments as an array.</li><li>Expression-bodied syntax <code>=></code> works for single-expression methods, properties, and indexers.</li></ul>",
        examples=[
            {"title":"Method Overloading","code":"using System;\n\nclass Calculator {\n    public int Add(int a, int b) => a + b;\n    public double Add(double a, double b) => a + b;\n    public int Add(int a, int b, int c) => a + b + c;\n}\n\nclass Program {\n    static void Main() {\n        var calc = new Calculator();\n        Console.WriteLine(calc.Add(3, 4));        // 7\n        Console.WriteLine(calc.Add(1.5, 2.5));    // 4.0\n        Console.WriteLine(calc.Add(1, 2, 3));     // 6\n    }\n}","output":"7\n4\n6","explanation":"<p>Method overloading: same name, different parameter lists. The compiler picks the best match.</p>"},
            {"title":"ref and out Parameters","code":"using System;\n\nclass Program {\n    static void Swap(ref int a, ref int b) {\n        int temp = a; a = b; b = temp;\n    }\n    \n    static bool TryParse(string s, out int result) {\n        return int.TryParse(s, out result);\n    }\n    \n    static void Main() {\n        int x = 10, y = 20;\n        Console.WriteLine($\"Before: x={x}, y={y}\");\n        Swap(ref x, ref y);\n        Console.WriteLine($\"After:  x={x}, y={y}\");\n        \n        if (TryParse(\"42\", out int val))\n            Console.WriteLine($\"Parsed: {val}\");\n    }\n}","output":"Before: x=10, y=20\nAfter:  x=20, y=10\nParsed: 42","explanation":"<p><code>ref</code> passes by reference (modifies originals). <code>out</code> returns additional values from a method.</p>"},
            {"title":"params & Default Parameters","code":"using System;\n\nclass Program {\n    static int Sum(params int[] numbers) {\n        int total = 0;\n        foreach (int n in numbers) total += n;\n        return total;\n    }\n    \n    static string Greet(string name, string greeting = \"Hello\") {\n        return $\"{greeting}, {name}!\";\n    }\n    \n    static void Main() {\n        Console.WriteLine(Sum(1, 2, 3));           // 6\n        Console.WriteLine(Sum(10, 20, 30, 40));    // 100\n        Console.WriteLine(Greet(\"Alice\"));          // Hello, Alice!\n        Console.WriteLine(Greet(\"Bob\", \"Hi\"));      // Hi, Bob!\n    }\n}","output":"6\n100\nHello, Alice!\nHi, Bob!","explanation":"<p><code>params</code> accepts any number of arguments. Default parameters provide fallback values.</p>"},
        ],
        quiz=[
            {"q":"'out' parameters require the method to:","options":["Read the value","Assign a value before returning","Be static","Return void"],"answer":"Assign a value before returning"},
            {"q":"Expression-bodied methods use which syntax?","options":["-> ","=> ",":: ",">> "],"answer":"=> "},
        ],
    ),
    "cs_arrays": make_topic(
        intro="<p>C# provides both fixed-size <strong>arrays</strong> and resizable <strong>List&lt;T&gt;</strong> from <code>System.Collections.Generic</code>. Arrays have O(1) index access but cannot change size. <code>List&lt;T&gt;</code> wraps an array with automatic resizing, adding <code>Add()</code>, <code>Remove()</code>, <code>Contains()</code>, <code>Sort()</code>, and more. C# also supports <strong>multidimensional arrays</strong> (<code>int[,]</code>) and <strong>jagged arrays</strong> (<code>int[][]</code>).</p>",
        subtopics=[
            {"title":"Arrays","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>int[] nums = {10, 20, 30, 40, 50};\nConsole.WriteLine(nums[0]);     // 10\nConsole.WriteLine(nums.Length); // 5\nArray.Sort(nums);\nArray.Reverse(nums);</pre>"},
            {"title":"List<T>","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>var names = new List<string> {\"Alice\", \"Bob\"};\nnames.Add(\"Charlie\");\nnames.Remove(\"Bob\");\nnames.Sort();\nConsole.WriteLine(names.Count);     // 2\nConsole.WriteLine(names.Contains(\"Alice\")); // True</pre>"},
        ],
        key_concepts="<ul><li>Arrays are fixed-size; <code>List&lt;T&gt;</code> resizes dynamically.</li><li><code>Array.Sort()</code> sorts in-place. <code>Array.IndexOf()</code> finds element position.</li><li><code>List&lt;T&gt;</code> methods: <code>Add</code>, <code>Remove</code>, <code>Contains</code>, <code>Find</code>, <code>Sort</code>, <code>ForEach</code>.</li><li>Use <code>int[,]</code> for rectangular 2D arrays; <code>int[][]</code> for jagged (rows of different lengths).</li></ul>",
        examples=[
            {"title":"Array Operations","code":"using System;\n\nclass Program {\n    static void Main() {\n        int[] arr = {64, 34, 25, 12, 22, 11, 90};\n        Console.WriteLine($\"Length: {arr.Length}\");\n        Console.WriteLine($\"Max: {arr.Max()}\");\n        Console.WriteLine($\"Min: {arr.Min()}\");\n        Console.WriteLine($\"Sum: {arr.Sum()}\");\n        \n        Array.Sort(arr);\n        Console.WriteLine($\"Sorted: {string.Join(\", \", arr)}\");\n    }\n}","output":"Length: 7\nMax: 90\nMin: 11\nSum: 258\nSorted: 11, 12, 22, 25, 34, 64, 90","explanation":"<p>LINQ extensions (<code>Max</code>, <code>Min</code>, <code>Sum</code>) work on arrays. <code>string.Join</code> formats arrays for display.</p>"},
            {"title":"List<T> Operations","code":"using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        var students = new List<string> {\"Charlie\", \"Alice\", \"Bob\"};\n        students.Add(\"Diana\");\n        students.Remove(\"Charlie\");\n        students.Sort();\n        \n        Console.WriteLine($\"Count: {students.Count}\");\n        foreach (var s in students)\n            Console.WriteLine($\"  {s}\");\n        \n        Console.WriteLine($\"Contains Bob: {students.Contains(\"Bob\")}\");\n    }\n}","output":"Count: 3\n  Alice\n  Bob\n  Diana\nContains Bob: True","explanation":"<p><code>List&lt;T&gt;</code> is the go-to dynamic collection — resizes automatically, type-safe, and feature-rich.</p>"},
            {"title":"2D Array (Matrix)","code":"using System;\n\nclass Program {\n    static void Main() {\n        int[,] matrix = {\n            {1, 2, 3},\n            {4, 5, 6},\n            {7, 8, 9}\n        };\n        \n        for (int i = 0; i < matrix.GetLength(0); i++) {\n            for (int j = 0; j < matrix.GetLength(1); j++)\n                Console.Write($\"{matrix[i,j]} \");\n            Console.WriteLine();\n        }\n    }\n}","output":"1 2 3\n4 5 6\n7 8 9","explanation":"<p><code>GetLength(0)</code> returns rows, <code>GetLength(1)</code> returns columns for multidimensional arrays.</p>"},
        ],
        quiz=[
            {"q":"List<T> vs Array: which can change size?","options":["Array","List<T>","Both","Neither"],"answer":"List<T>"},
            {"q":"How to get the number of rows in a 2D array?","options":["array.Length","array.Count","array.GetLength(0)","array.Rows"],"answer":"array.GetLength(0)"},
        ],
    ),
    "cs_strings": make_topic(
        intro="<p><strong>Strings</strong> in C# are <strong>immutable</strong> — every modification creates a new string object. For heavy string manipulation, use <code>StringBuilder</code> (mutable, efficient). C# strings support rich operations: interpolation (<code>$\"...\"</code>), verbatim strings (<code>@\"...\"</code>), LINQ queries, and powerful built-in methods. Strings in C# are UTF-16 encoded, supporting international characters natively.</p>",
        subtopics=[
            {"title":"String Methods","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>string s = \"  Hello, World!  \";\nConsole.WriteLine(s.Trim());           // \"Hello, World!\"\nConsole.WriteLine(s.ToUpper());        // \"  HELLO, WORLD!  \"\nConsole.WriteLine(s.Contains(\"World\")); // True\nConsole.WriteLine(s.Replace(\"World\", \"C#\")); // \"  Hello, C#!  \"\nConsole.WriteLine(s.Split(',').Length); // 2</pre>"},
            {"title":"StringBuilder","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>var sb = new StringBuilder();\nfor (int i = 0; i < 1000; i++)\n    sb.Append(i).Append(\", \");\nstring result = sb.ToString();\n// Much faster than string concatenation in a loop!</pre>"},
        ],
        key_concepts="<ul><li>Strings are immutable — <code>s.ToUpper()</code> returns a NEW string, doesn't modify <code>s</code>.</li><li><code>StringBuilder</code> is mutable — use for loops and heavy concatenation (O(1) append vs O(n) string concat).</li><li><code>string.IsNullOrEmpty(s)</code> and <code>string.IsNullOrWhiteSpace(s)</code> — safe null checks.</li><li>Verbatim strings: <code>@\"C:\\Users\\file\"</code> — no escape sequences needed for paths.</li></ul>",
        examples=[
            {"title":"String Methods","code":"using System;\n\nclass Program {\n    static void Main() {\n        string text = \"Hello, World!\";\n        \n        Console.WriteLine($\"Length: {text.Length}\");\n        Console.WriteLine($\"Upper: {text.ToUpper()}\");\n        Console.WriteLine($\"Sub: {text.Substring(7)}\");\n        Console.WriteLine($\"Index of 'W': {text.IndexOf('W')}\");\n        Console.WriteLine($\"Starts with 'Hello': {text.StartsWith(\"Hello\")}\");\n        \n        string[] words = text.Split(' ');\n        Console.WriteLine($\"Words: {string.Join(\" | \", words)}\");\n    }\n}","output":"Length: 13\nUpper: HELLO, WORLD!\nSub: World!\nIndex of 'W': 7\nStarts with 'Hello': True\nWords: Hello, | World!","explanation":"<p>C# string methods are rich and expressive. All return new strings (original is unchanged).</p>"},
            {"title":"StringBuilder Performance","code":"using System;\nusing System.Diagnostics;\nusing System.Text;\n\nclass Program {\n    static void Main() {\n        var sw = Stopwatch.StartNew();\n        string s = \"\";\n        for (int i = 0; i < 10000; i++) s += \"a\";\n        sw.Stop();\n        Console.WriteLine($\"String concat: {sw.ElapsedMilliseconds}ms\");\n        \n        sw.Restart();\n        var sb = new StringBuilder();\n        for (int i = 0; i < 10000; i++) sb.Append(\"a\");\n        string result = sb.ToString();\n        sw.Stop();\n        Console.WriteLine($\"StringBuilder: {sw.ElapsedMilliseconds}ms\");\n    }\n}","output":"String concat: 120ms\nStringBuilder: 0ms","explanation":"<p>String concatenation in a loop creates n intermediate strings (O(n<sup>2</sup>)). StringBuilder appends in-place (O(n)).</p>"},
            {"title":"String Interpolation & Verbatim","code":"using System;\n\nclass Program {\n    static void Main() {\n        string name = \"Alice\";\n        double price = 29.99;\n        \n        // Interpolation with formatting\n        Console.WriteLine($\"{name}'s total: {price:C}\");  // Currency\n        Console.WriteLine($\"Pi: {Math.PI:F4}\");            // 4 decimals\n        Console.WriteLine($\"Padded: {42,10}\");             // right-aligned\n        \n        // Verbatim string (no escapes)\n        string path = @\"C:\\Users\\Alice\\Documents\";\n        Console.WriteLine(path);\n    }\n}","output":"Alice's total: $29.99\nPi: 3.1416\nPadded:         42\nC:\\Users\\Alice\\Documents","explanation":"<p>Format specifiers inside interpolation: <code>:C</code> (currency), <code>:F4</code> (4 decimals), <code>,10</code> (padding). Verbatim strings escape backslashes.</p>"},
        ],
        quiz=[
            {"q":"Strings in C# are:","options":["Mutable","Immutable","Value types","Dynamically typed"],"answer":"Immutable"},
            {"q":"What should you use for string concatenation in a loop?","options":["string +","String.Concat","StringBuilder","StringBuffer"],"answer":"StringBuilder"},
        ],
    ),
    "cs_oop": make_topic(
        intro="<p><strong>Object-Oriented Programming (OOP)</strong> in C# is built around four pillars: <strong>encapsulation</strong>, <strong>inheritance</strong>, <strong>polymorphism</strong>, and <strong>abstraction</strong>. Everything in C# is a class or struct. Classes define blueprints for objects with <strong>properties</strong> (data), <strong>methods</strong> (behaviour), <strong>constructors</strong> (initialization), and <strong>access modifiers</strong> (public, private, protected) that control visibility.</p>",
        subtopics=[
            {"title":"Classes & Objects","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>class Student {\n    public string Name { get; set; }  // auto-property\n    public int Age { get; set; }\n    \n    public Student(string name, int age) {\n        Name = name; Age = age;\n    }\n    \n    public void Greet() => Console.WriteLine($\"Hi, I'm {Name}\");\n}\n\nvar s = new Student(\"Alice\", 20);\ns.Greet();  // Hi, I'm Alice</pre>"},
            {"title":"Properties & Encapsulation","content":"<p>C# properties replace getters/setters with clean syntax. <code>{ get; set; }</code> auto-implements backing field. <code>{ get; private set; }</code> makes write-protected. <code>{ get; init; }</code> (C# 9+) allows setting only during construction.</p>"},
        ],
        key_concepts="<ul><li>Auto-properties: <code>public string Name { get; set; }</code> — compiler generates the backing field.</li><li>Access modifiers: <code>public</code> (everywhere), <code>private</code> (same class), <code>protected</code> (class + subclasses), <code>internal</code> (same assembly).</li><li>Constructors can be chained: <code>public Student(string name) : this(name, 0) {}</code></li><li><code>record</code> (C# 9+): immutable data class with auto-generated equality, ToString, and deconstruction.</li></ul>",
        examples=[
            {"title":"Class with Properties","code":"using System;\n\nclass BankAccount {\n    public string Owner { get; }\n    public decimal Balance { get; private set; }\n    \n    public BankAccount(string owner, decimal initial) {\n        Owner = owner;\n        Balance = initial;\n    }\n    \n    public void Deposit(decimal amount) {\n        if (amount > 0) Balance += amount;\n    }\n    \n    public bool Withdraw(decimal amount) {\n        if (amount > Balance) return false;\n        Balance -= amount;\n        return true;\n    }\n    \n    public override string ToString() => $\"{Owner}: ${Balance}\";\n}\n\nclass Program {\n    static void Main() {\n        var acct = new BankAccount(\"Alice\", 1000);\n        acct.Deposit(500);\n        acct.Withdraw(200);\n        Console.WriteLine(acct);  // Alice: $1300\n    }\n}","output":"Alice: $1300","explanation":"<p>Encapsulation: <code>Balance</code> has a private setter — only <code>Deposit</code> and <code>Withdraw</code> can modify it, enforcing business rules.</p>"},
            {"title":"Record Types (C# 9+)","code":"using System;\n\nrecord Student(string Name, int Age, double GPA);\n\nclass Program {\n    static void Main() {\n        var s1 = new Student(\"Alice\", 20, 3.8);\n        var s2 = s1 with { Age = 21 };  // non-destructive copy\n        \n        Console.WriteLine(s1);        // Student { Name = Alice, Age = 20, GPA = 3.8 }\n        Console.WriteLine(s2);        // Student { Name = Alice, Age = 21, GPA = 3.8 }\n        Console.WriteLine(s1 == s2);  // False (value equality)\n    }\n}","output":"Student { Name = Alice, Age = 20, GPA = 3.8 }\nStudent { Name = Alice, Age = 21, GPA = 3.8 }\nFalse","explanation":"<p>Records: one-line immutable data classes with value equality, <code>with</code> expressions, and auto-generated <code>ToString</code>.</p>"},
            {"title":"Constructor Chaining","code":"using System;\n\nclass Rectangle {\n    public double Width { get; }\n    public double Height { get; }\n    \n    public Rectangle(double w, double h) { Width = w; Height = h; }\n    public Rectangle(double side) : this(side, side) {}  // square\n    \n    public double Area => Width * Height;\n    public double Perimeter => 2 * (Width + Height);\n}\n\nclass Program {\n    static void Main() {\n        var rect = new Rectangle(5, 3);\n        var square = new Rectangle(4);\n        Console.WriteLine($\"Rect: {rect.Area}, Perimeter: {rect.Perimeter}\");\n        Console.WriteLine($\"Square: {square.Area}, Perimeter: {square.Perimeter}\");\n    }\n}","output":"Rect: 15, Perimeter: 16\nSquare: 16, Perimeter: 16","explanation":"<p>Constructor chaining (<code>: this()</code>) reuses logic. Expression-bodied properties (<code>=></code>) compute values on access.</p>"},
        ],
        quiz=[
            {"q":"What does { get; private set; } mean?","options":["Read-only everywhere","Readable everywhere, writable only inside the class","Fully public","Write-only"],"answer":"Readable everywhere, writable only inside the class"},
            {"q":"C# records provide:","options":["Mutable data classes","Immutable data types with value equality","Abstract base classes","Interface implementations"],"answer":"Immutable data types with value equality"},
        ],
    ),
    "cs_inheritance": make_topic(
        intro="<p><strong>Inheritance</strong> in C# allows a class to reuse and extend the behaviour of another class. A <strong>derived class</strong> inherits all non-private members of its <strong>base class</strong> and can <strong>override</strong> virtual methods to provide specialized behaviour. C# supports single inheritance (one base class) but multiple interface implementation. <strong>Abstract classes</strong> define contracts that derived classes must fulfill, while <strong>sealed classes</strong> prevent further inheritance.</p>",
        subtopics=[
            {"title":"Base & Derived Classes","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>class Animal {\n    public string Name { get; set; }\n    public virtual void Speak() => Console.WriteLine(\"...\");\n}\n\nclass Dog : Animal {\n    public override void Speak() => Console.WriteLine(\"Woof!\");\n}\n\nclass Cat : Animal {\n    public override void Speak() => Console.WriteLine(\"Meow!\");\n}</pre>"},
            {"title":"Abstract Classes","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>abstract class Shape {\n    public abstract double Area();  // must be implemented\n    public void Describe() => Console.WriteLine($\"Area: {Area()}\");\n}</pre>"},
        ],
        key_concepts="<ul><li><code>virtual</code> — base class method CAN be overridden. <code>abstract</code> — MUST be overridden.</li><li><code>override</code> — derived class replaces base method. <code>base.Method()</code> calls the original.</li><li><code>sealed</code> — prevents further inheritance or override.</li><li>C# allows single class inheritance but multiple interface implementation.</li></ul>",
        examples=[
            {"title":"Polymorphism Demo","code":"using System;\nusing System.Collections.Generic;\n\nclass Animal {\n    public string Name { get; set; }\n    public virtual string Speak() => \"...\";\n}\n\nclass Dog : Animal {\n    public override string Speak() => \"Woof!\";\n}\n\nclass Cat : Animal {\n    public override string Speak() => \"Meow!\";\n}\n\nclass Program {\n    static void Main() {\n        List<Animal> animals = new() {\n            new Dog { Name = \"Rex\" },\n            new Cat { Name = \"Whiskers\" },\n            new Dog { Name = \"Buddy\" }\n        };\n        \n        foreach (var a in animals)\n            Console.WriteLine($\"{a.Name} says {a.Speak()}\");\n    }\n}","output":"Rex says Woof!\nWhiskers says Meow!\nBuddy says Woof!","explanation":"<p>Polymorphism: the same <code>Speak()</code> call produces different output based on the actual type — determined at runtime.</p>"},
            {"title":"Abstract Class Shape","code":"using System;\n\nabstract class Shape {\n    public abstract double Area();\n    public abstract double Perimeter();\n    public override string ToString() => $\"{GetType().Name}: A={Area():F2}, P={Perimeter():F2}\";\n}\n\nclass Circle : Shape {\n    public double Radius { get; }\n    public Circle(double r) => Radius = r;\n    public override double Area() => Math.PI * Radius * Radius;\n    public override double Perimeter() => 2 * Math.PI * Radius;\n}\n\nclass Rectangle : Shape {\n    public double W { get; } public double H { get; }\n    public Rectangle(double w, double h) { W = w; H = h; }\n    public override double Area() => W * H;\n    public override double Perimeter() => 2 * (W + H);\n}\n\nclass Program {\n    static void Main() {\n        Shape[] shapes = { new Circle(5), new Rectangle(4, 6) };\n        foreach (var s in shapes)\n            Console.WriteLine(s);\n    }\n}","output":"Circle: A=78.54, P=31.42\nRectangle: A=24.00, P=20.00","explanation":"<p>Abstract classes define contracts. Each derived class provides its own formula for <code>Area()</code> and <code>Perimeter()</code>.</p>"},
            {"title":"Constructor Inheritance (base)","code":"using System;\n\nclass Person {\n    public string Name { get; }\n    public Person(string name) => Name = name;\n}\n\nclass Employee : Person {\n    public string Role { get; }\n    public Employee(string name, string role) : base(name) {\n        Role = role;\n    }\n    public override string ToString() => $\"{Name} ({Role})\";\n}\n\nclass Program {\n    static void Main() {\n        var emp = new Employee(\"Alice\", \"Developer\");\n        Console.WriteLine(emp);  // Alice (Developer)\n    }\n}","output":"Alice (Developer)","explanation":"<p><code>: base(name)</code> calls the parent constructor — derived class must initialize the base class.</p>"},
        ],
        quiz=[
            {"q":"'abstract' methods must be:","options":["Called directly","Implemented by derived classes","Private","Static"],"answer":"Implemented by derived classes"},
            {"q":"'sealed' on a class means:","options":["It's abstract","It can't be inherited","It's internal","It's static"],"answer":"It can't be inherited"},
        ],
    ),
    "cs_interfaces": make_topic(
        intro="<p>An <strong>interface</strong> in C# defines a contract — a set of method and property signatures that implementing classes must provide. Unlike abstract classes, interfaces contain no implementation (until C# 8 default interface methods). A class can implement <strong>multiple interfaces</strong>, enabling a form of multiple inheritance. Interfaces are the foundation of dependency injection, testability, and SOLID design principles in C#.</p>",
        subtopics=[
            {"title":"Interface Definition","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>interface IShape {\n    double Area();\n    double Perimeter();\n    string Name { get; }  // property\n}\n\nclass Circle : IShape {\n    public double Radius { get; }\n    public string Name => \"Circle\";\n    public Circle(double r) => Radius = r;\n    public double Area() => Math.PI * Radius * Radius;\n    public double Perimeter() => 2 * Math.PI * Radius;\n}</pre>"},
            {"title":"Multiple Interface Implementation","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>interface ISerializable { string Serialize(); }\ninterface IPrintable { void Print(); }\n\nclass Report : ISerializable, IPrintable {\n    public string Title { get; set; }\n    public string Serialize() => $\"{{title: {Title}}}\";\n    public void Print() => Console.WriteLine(Title);\n}</pre>"},
        ],
        key_concepts="<ul><li>Interface names start with <code>I</code> by convention: <code>IDisposable</code>, <code>IEnumerable</code>.</li><li>A class can implement multiple interfaces but inherit from only one class.</li><li>Common .NET interfaces: <code>IDisposable</code>, <code>IEnumerable&lt;T&gt;</code>, <code>IComparable&lt;T&gt;</code>, <code>IEquatable&lt;T&gt;</code>.</li><li>Default interface methods (C# 8+): interfaces can provide default implementations.</li></ul>",
        examples=[
            {"title":"Interface Polymorphism","code":"using System;\nusing System.Collections.Generic;\n\ninterface IAnimal {\n    string Name { get; }\n    string Sound();\n}\n\nclass Dog : IAnimal {\n    public string Name { get; }\n    public Dog(string n) => Name = n;\n    public string Sound() => \"Woof\";\n}\n\nclass Cat : IAnimal {\n    public string Name { get; }\n    public Cat(string n) => Name = n;\n    public string Sound() => \"Meow\";\n}\n\nclass Program {\n    static void Main() {\n        List<IAnimal> animals = new() { new Dog(\"Rex\"), new Cat(\"Luna\") };\n        foreach (var a in animals)\n            Console.WriteLine($\"{a.Name}: {a.Sound()}\");\n    }\n}","output":"Rex: Woof\nLuna: Meow","explanation":"<p>Programming to interfaces: the list holds <code>IAnimal</code>, not specific types — enabling polymorphism and easy extension.</p>"},
            {"title":"IComparable for Sorting","code":"using System;\nusing System.Collections.Generic;\n\nclass Student : IComparable<Student> {\n    public string Name { get; set; }\n    public double GPA { get; set; }\n    \n    public int CompareTo(Student other) => GPA.CompareTo(other.GPA);\n    public override string ToString() => $\"{Name}: {GPA}\";\n}\n\nclass Program {\n    static void Main() {\n        var students = new List<Student> {\n            new() { Name=\"Charlie\", GPA=3.5 },\n            new() { Name=\"Alice\", GPA=3.9 },\n            new() { Name=\"Bob\", GPA=3.2 }\n        };\n        students.Sort();  // uses CompareTo\n        foreach (var s in students)\n            Console.WriteLine(s);\n    }\n}","output":"Bob: 3.2\nCharlie: 3.5\nAlice: 3.9","explanation":"<p>Implementing <code>IComparable&lt;T&gt;</code> lets <code>List.Sort()</code> sort your custom objects.</p>"},
            {"title":"Dependency Injection via Interface","code":"using System;\n\ninterface ILogger {\n    void Log(string message);\n}\n\nclass ConsoleLogger : ILogger {\n    public void Log(string message) => Console.WriteLine($\"[LOG] {message}\");\n}\n\nclass OrderService {\n    private readonly ILogger _logger;\n    public OrderService(ILogger logger) => _logger = logger;\n    \n    public void PlaceOrder(string item) {\n        _logger.Log($\"Order placed: {item}\");\n    }\n}\n\nclass Program {\n    static void Main() {\n        ILogger logger = new ConsoleLogger();\n        var service = new OrderService(logger);\n        service.PlaceOrder(\"Laptop\");\n    }\n}","output":"[LOG] Order placed: Laptop","explanation":"<p>Dependency injection: <code>OrderService</code> depends on <code>ILogger</code> (not a concrete class) — making it testable and swappable.</p>"},
        ],
        quiz=[
            {"q":"How many interfaces can a C# class implement?","options":["Only one","Up to 3","Unlimited","Two"],"answer":"Unlimited"},
            {"q":"Interface names conventionally start with:","options":["A","C","I","S"],"answer":"I"},
        ],
    ),
    "cs_exceptions": make_topic(
        intro="<p><strong>Exception handling</strong> in C# uses <code>try-catch-finally</code> blocks to gracefully handle runtime errors (file not found, network failure, invalid input, division by zero). C# exceptions are objects inheriting from <code>System.Exception</code>. Proper exception handling prevents crashes, logs errors for debugging, and provides meaningful error messages to users.</p>",
        subtopics=[
            {"title":"try-catch-finally","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>try {\n    int result = 10 / 0;\n} catch (DivideByZeroException ex) {\n    Console.WriteLine($\"Error: {ex.Message}\");\n} catch (Exception ex) {\n    Console.WriteLine($\"General: {ex.Message}\");\n} finally {\n    Console.WriteLine(\"Cleanup code runs always\");\n}</pre>"},
            {"title":"Custom Exceptions","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>class InsufficientFundsException : Exception {\n    public decimal Balance { get; }\n    public InsufficientFundsException(decimal bal)\n        : base($\"Insufficient funds. Balance: {bal}\") {\n        Balance = bal;\n    }\n}</pre>"},
        ],
        key_concepts="<ul><li>Catch specific exceptions first, general <code>Exception</code> last.</li><li><code>finally</code> always runs — for cleanup (closing files, connections).</li><li><code>throw;</code> (no argument) re-throws preserving stack trace. <code>throw ex;</code> loses original trace.</li><li>Use <code>when</code> filter: <code>catch (Exception ex) when (ex.Message.Contains(\"timeout\"))</code></li></ul>",
        examples=[
            {"title":"Exception Handling Basics","code":"using System;\n\nclass Program {\n    static void Main() {\n        try {\n            Console.Write(\"Enter a number: \");\n            int num = int.Parse(\"abc\");  // will throw\n            Console.WriteLine($\"Result: {100 / num}\");\n        } catch (FormatException) {\n            Console.WriteLine(\"Invalid number format!\");\n        } catch (DivideByZeroException) {\n            Console.WriteLine(\"Cannot divide by zero!\");\n        } finally {\n            Console.WriteLine(\"Execution complete.\");\n        }\n    }\n}","output":"Enter a number: Invalid number format!\nExecution complete.","explanation":"<p><code>int.Parse(\"abc\")</code> throws <code>FormatException</code>. The specific catch block handles it. <code>finally</code> always runs.</p>"},
            {"title":"Custom Exception","code":"using System;\n\nclass AgeException : Exception {\n    public AgeException(int age) : base($\"Invalid age: {age}. Must be 0-150.\") {}\n}\n\nclass Program {\n    static void ValidateAge(int age) {\n        if (age < 0 || age > 150) throw new AgeException(age);\n        Console.WriteLine($\"Age {age} is valid.\");\n    }\n    \n    static void Main() {\n        try {\n            ValidateAge(25);\n            ValidateAge(-5);\n        } catch (AgeException ex) {\n            Console.WriteLine($\"Caught: {ex.Message}\");\n        }\n    }\n}","output":"Age 25 is valid.\nCaught: Invalid age: -5. Must be 0-150.","explanation":"<p>Custom exceptions model domain-specific errors. Include relevant data (the invalid age) in the exception.</p>"},
            {"title":"TryParse Pattern (Avoid Exceptions)","code":"using System;\n\nclass Program {\n    static void Main() {\n        string[] inputs = {\"42\", \"hello\", \"99\"};\n        foreach (var input in inputs) {\n            if (int.TryParse(input, out int result))\n                Console.WriteLine($\"Parsed: {result}\");\n            else\n                Console.WriteLine($\"'{input}' is not a valid number\");\n        }\n    }\n}","output":"Parsed: 42\n'hello' is not a valid number\nParsed: 99","explanation":"<p><code>TryParse</code> avoids exceptions entirely — faster and cleaner than try-catch for expected invalid input.</p>"},
        ],
        quiz=[
            {"q":"The 'finally' block runs:","options":["Only on error","Only on success","Always","Never"],"answer":"Always"},
            {"q":"To preserve stack trace when re-throwing, use:","options":["throw ex;","throw;","return;","break;"],"answer":"throw;"},
        ],
    ),
    "cs_generics": make_topic(
        intro="<p><strong>Generics</strong> enable type-safe, reusable code that works with any data type without boxing/unboxing overhead. <code>List&lt;T&gt;</code>, <code>Dictionary&lt;TKey, TValue&gt;</code>, and <code>Task&lt;T&gt;</code> are all generic types. You can create generic classes, methods, interfaces, and delegates. Generics are one of C#'s most powerful features — they eliminate code duplication while maintaining compile-time type safety.</p>",
        subtopics=[
            {"title":"Generic Classes & Methods","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>class Stack<T> {\n    private List<T> items = new();\n    public void Push(T item) => items.Add(item);\n    public T Pop() { var item = items[^1]; items.RemoveAt(items.Count-1); return item; }\n    public int Count => items.Count;\n}\n\nT Max<T>(T a, T b) where T : IComparable<T>\n    => a.CompareTo(b) > 0 ? a : b;</pre>"},
            {"title":"Constraints","content":"<p>Constraints restrict what types can be used: <code>where T : class</code> (reference type), <code>where T : struct</code> (value type), <code>where T : new()</code> (has parameterless constructor), <code>where T : IComparable</code> (implements interface).</p>"},
        ],
        key_concepts="<ul><li>Generics are resolved at compile time — full type safety, no runtime casting.</li><li>Without generics: <code>ArrayList</code> stores <code>object</code> — requires casting, no type safety.</li><li>Common generic types: <code>List&lt;T&gt;</code>, <code>Dictionary&lt;K,V&gt;</code>, <code>Queue&lt;T&gt;</code>, <code>Stack&lt;T&gt;</code>, <code>HashSet&lt;T&gt;</code>.</li><li>Covariance (<code>out T</code>) and contravariance (<code>in T</code>) for generic interfaces.</li></ul>",
        examples=[
            {"title":"Generic Stack","code":"using System;\nusing System.Collections.Generic;\n\nclass Stack<T> {\n    private readonly List<T> _items = new();\n    public void Push(T item) => _items.Add(item);\n    public T Pop() {\n        T item = _items[^1];\n        _items.RemoveAt(_items.Count - 1);\n        return item;\n    }\n    public T Peek() => _items[^1];\n    public int Count => _items.Count;\n}\n\nclass Program {\n    static void Main() {\n        var intStack = new Stack<int>();\n        intStack.Push(10); intStack.Push(20); intStack.Push(30);\n        Console.WriteLine(intStack.Pop());  // 30\n        \n        var strStack = new Stack<string>();\n        strStack.Push(\"Hello\"); strStack.Push(\"World\");\n        Console.WriteLine(strStack.Pop());  // World\n    }\n}","output":"30\nWorld","explanation":"<p>One <code>Stack&lt;T&gt;</code> class works for any type — <code>int</code>, <code>string</code>, custom classes — with full type safety.</p>"},
            {"title":"Generic Method with Constraint","code":"using System;\n\nclass Program {\n    static T Max<T>(T a, T b) where T : IComparable<T> {\n        return a.CompareTo(b) >= 0 ? a : b;\n    }\n    \n    static void Main() {\n        Console.WriteLine(Max(10, 20));           // 20\n        Console.WriteLine(Max(3.14, 2.71));       // 3.14\n        Console.WriteLine(Max(\"apple\", \"banana\")); // banana\n    }\n}","output":"20\n3.14\nbanana","explanation":"<p>The <code>where T : IComparable&lt;T&gt;</code> constraint ensures <code>CompareTo</code> is available at compile time.</p>"},
            {"title":"Generic Repository Pattern","code":"using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nclass Repository<T> where T : class {\n    private readonly List<T> _items = new();\n    \n    public void Add(T item) => _items.Add(item);\n    public List<T> GetAll() => _items.ToList();\n    public int Count => _items.Count;\n}\n\nrecord Product(string Name, decimal Price);\n\nclass Program {\n    static void Main() {\n        var repo = new Repository<Product>();\n        repo.Add(new Product(\"Laptop\", 999.99m));\n        repo.Add(new Product(\"Mouse\", 29.99m));\n        \n        foreach (var p in repo.GetAll())\n            Console.WriteLine($\"{p.Name}: ${p.Price}\");\n    }\n}","output":"Laptop: $999.99\nMouse: $29.99","explanation":"<p>Generic Repository: one class serves all entity types — a common enterprise pattern for data access layers.</p>"},
        ],
        quiz=[
            {"q":"Generics provide type safety at:","options":["Runtime only","Compile time","Both","Neither"],"answer":"Compile time"},
            {"q":"'where T : new()' means T must:","options":["Be a class","Be a struct","Have a parameterless constructor","Implement IDisposable"],"answer":"Have a parameterless constructor"},
        ],
    ),
    "cs_linq": make_topic(
        intro="<p><strong>LINQ (Language Integrated Query)</strong> is C#'s most distinctive feature — it brings SQL-like query syntax directly into the programming language for querying any data source: arrays, lists, databases (Entity Framework), XML, and JSON. LINQ provides two syntaxes: <strong>query syntax</strong> (<code>from x in collection where ... select ...</code>) and <strong>method syntax</strong> (<code>.Where().Select().OrderBy()</code>). LINQ makes data processing declarative, readable, and composable.</p>",
        subtopics=[
            {"title":"LINQ Method Syntax","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>var nums = new List<int> {5, 3, 8, 1, 9, 2, 7};\nvar result = nums\n    .Where(n => n > 3)       // filter\n    .OrderBy(n => n)          // sort\n    .Select(n => n * 10);     // transform\n// result: 50, 70, 80, 90</pre>"},
            {"title":"LINQ Query Syntax","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>var result = from n in nums\n             where n > 3\n             orderby n\n             select n * 10;</pre>"},
        ],
        key_concepts="<ul><li>LINQ is <strong>lazy</strong> — queries execute only when iterated (deferred execution).</li><li>Common methods: <code>Where</code>, <code>Select</code>, <code>OrderBy</code>, <code>GroupBy</code>, <code>First</code>, <code>Any</code>, <code>All</code>, <code>Count</code>, <code>Sum</code>, <code>Average</code>.</li><li><code>ToList()</code> or <code>ToArray()</code> forces immediate execution.</li><li>LINQ works with Entity Framework for database queries — same syntax, SQL generated automatically.</li></ul>",
        examples=[
            {"title":"LINQ Collection Processing","code":"using System;\nusing System.Linq;\nusing System.Collections.Generic;\n\nclass Program {\n    static void Main() {\n        var numbers = new List<int> {5, 12, 8, 3, 17, 9, 2, 15};\n        \n        var evens = numbers.Where(n => n % 2 == 0).ToList();\n        Console.WriteLine($\"Evens: {string.Join(\", \", evens)}\");\n        \n        Console.WriteLine($\"Sum: {numbers.Sum()}\");\n        Console.WriteLine($\"Avg: {numbers.Average():F1}\");\n        Console.WriteLine($\"Max: {numbers.Max()}\");\n        Console.WriteLine($\"Any > 10: {numbers.Any(n => n > 10)}\");\n        Console.WriteLine($\"All > 0: {numbers.All(n => n > 0)}\");\n    }\n}","output":"Evens: 12, 8, 2\nSum: 71\nAvg: 8.9\nMax: 17\nAny > 10: True\nAll > 0: True","explanation":"<p>LINQ replaces manual loops with declarative queries — each operation clearly states intent.</p>"},
            {"title":"LINQ with Objects","code":"using System;\nusing System.Linq;\nusing System.Collections.Generic;\n\nrecord Student(string Name, int Age, string Major, double GPA);\n\nclass Program {\n    static void Main() {\n        var students = new List<Student> {\n            new(\"Alice\", 20, \"CS\", 3.8),\n            new(\"Bob\", 22, \"Math\", 3.2),\n            new(\"Charlie\", 21, \"CS\", 3.9),\n            new(\"Diana\", 20, \"CS\", 3.5),\n        };\n        \n        // CS students sorted by GPA descending\n        var csTop = students\n            .Where(s => s.Major == \"CS\")\n            .OrderByDescending(s => s.GPA)\n            .Select(s => $\"{s.Name} ({s.GPA})\");\n        \n        Console.WriteLine(\"CS students by GPA:\");\n        foreach (var s in csTop) Console.WriteLine($\"  {s}\");\n        \n        // Group by major\n        var groups = students.GroupBy(s => s.Major);\n        foreach (var g in groups)\n            Console.WriteLine($\"{g.Key}: {g.Count()} students, avg GPA: {g.Average(s => s.GPA):F2}\");\n    }\n}","output":"CS students by GPA:\n  Charlie (3.9)\n  Alice (3.8)\n  Diana (3.5)\nCS: 3 students, avg GPA: 3.73\nMath: 1 students, avg GPA: 3.20","explanation":"<p>LINQ chains filter → sort → project operations fluently. <code>GroupBy</code> aggregates data like SQL GROUP BY.</p>"},
            {"title":"LINQ Query Syntax","code":"using System;\nusing System.Linq;\n\nclass Program {\n    static void Main() {\n        int[] scores = {85, 92, 78, 95, 88, 70, 96};\n        \n        var honors = from s in scores\n                     where s >= 90\n                     orderby s descending\n                     select $\"Score: {s} (Honors)\";\n        \n        foreach (var h in honors)\n            Console.WriteLine(h);\n        \n        Console.WriteLine($\"Average: {scores.Average():F1}\");\n    }\n}","output":"Score: 96 (Honors)\nScore: 95 (Honors)\nScore: 92 (Honors)\nAverage: 86.3","explanation":"<p>Query syntax reads like SQL — from, where, orderby, select. Both syntaxes compile to the same IL code.</p>"},
        ],
        quiz=[
            {"q":"LINQ queries use which execution model by default?","options":["Immediate","Deferred (lazy)","Parallel","Cached"],"answer":"Deferred (lazy)"},
            {"q":"To force immediate execution of a LINQ query, use:","options":[".Execute()",".Run()",".ToList()",".Complete()"],"answer":".ToList()"},
        ],
    ),
    "cs_async": make_topic(
        intro="<p><strong>Async/await</strong> is C#'s mechanism for writing <strong>non-blocking, asynchronous code</strong> that reads like synchronous code. Instead of blocking a thread while waiting for I/O (network, disk, database), <code>await</code> releases the thread and resumes when the operation completes. This is essential for responsive UIs (WPF, Xamarin) and scalable web servers (ASP.NET Core). <code>async</code> methods return <code>Task</code> or <code>Task&lt;T&gt;</code>.</p>",
        subtopics=[
            {"title":"async/await Syntax","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>async Task<string> FetchDataAsync(string url) {\n    using var client = new HttpClient();\n    string data = await client.GetStringAsync(url);\n    return data;  // returned wrapped in Task<string>\n}\n\n// Usage:\nstring result = await FetchDataAsync(\"https://api.example.com\");</pre>"},
            {"title":"Task.WhenAll — Parallel Async","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>var task1 = FetchDataAsync(\"url1\");\nvar task2 = FetchDataAsync(\"url2\");\nvar task3 = FetchDataAsync(\"url3\");\n\nstring[] results = await Task.WhenAll(task1, task2, task3);\n// All 3 run concurrently!</pre>"},
        ],
        key_concepts="<ul><li><code>async</code> enables <code>await</code> inside a method. The method returns <code>Task</code> or <code>Task&lt;T&gt;</code>.</li><li><code>await</code> releases the thread — doesn't block. Execution resumes when the awaited task completes.</li><li><code>Task.WhenAll</code>: run tasks in parallel, await all. <code>Task.WhenAny</code>: complete when first finishes.</li><li>Never use <code>.Result</code> or <code>.Wait()</code> — they block and can cause <strong>deadlocks</strong>.</li><li>Convention: async methods end with <code>Async</code> suffix.</li></ul>",
        examples=[
            {"title":"Basic Async/Await","code":"using System;\nusing System.Threading.Tasks;\n\nclass Program {\n    static async Task<int> ComputeAsync(int n) {\n        await Task.Delay(1000);  // simulate async work\n        return n * n;\n    }\n    \n    static async Task Main() {\n        Console.WriteLine(\"Starting...\");\n        int result = await ComputeAsync(7);\n        Console.WriteLine($\"Result: {result}\");\n        Console.WriteLine(\"Done!\");\n    }\n}","output":"Starting...\n(1 second delay)\nResult: 49\nDone!","explanation":"<p><code>await Task.Delay</code> simulates an async operation. The thread is freed during the delay — not blocked.</p>"},
            {"title":"Parallel Async Operations","code":"using System;\nusing System.Threading.Tasks;\nusing System.Diagnostics;\n\nclass Program {\n    static async Task<string> FetchAsync(string name, int ms) {\n        await Task.Delay(ms);\n        return $\"{name}: {ms}ms\";\n    }\n    \n    static async Task Main() {\n        var sw = Stopwatch.StartNew();\n        \n        // Run 3 tasks in parallel\n        var results = await Task.WhenAll(\n            FetchAsync(\"API-1\", 1000),\n            FetchAsync(\"API-2\", 2000),\n            FetchAsync(\"API-3\", 1500)\n        );\n        \n        sw.Stop();\n        foreach (var r in results) Console.WriteLine(r);\n        Console.WriteLine($\"Total time: {sw.ElapsedMilliseconds}ms\");\n    }\n}","output":"API-1: 1000ms\nAPI-2: 2000ms\nAPI-3: 1500ms\nTotal time: ~2000ms (not 4500ms!)","explanation":"<p><code>Task.WhenAll</code> runs all 3 tasks concurrently — total time = longest task (2s), not sum (4.5s).</p>"},
            {"title":"Async Error Handling","code":"using System;\nusing System.Threading.Tasks;\n\nclass Program {\n    static async Task<int> DivideAsync(int a, int b) {\n        await Task.Delay(100);\n        if (b == 0) throw new DivideByZeroException();\n        return a / b;\n    }\n    \n    static async Task Main() {\n        try {\n            int result = await DivideAsync(10, 0);\n            Console.WriteLine(result);\n        } catch (DivideByZeroException) {\n            Console.WriteLine(\"Cannot divide by zero!\");\n        }\n        Console.WriteLine(\"Program continues...\");\n    }\n}","output":"Cannot divide by zero!\nProgram continues...","explanation":"<p>Exceptions in async methods propagate naturally with try-catch — no special handling needed.</p>"},
        ],
        quiz=[
            {"q":"async methods should return:","options":["void","int","Task or Task<T>","string"],"answer":"Task or Task<T>"},
            {"q":"Task.WhenAll runs tasks:","options":["Sequentially","In parallel","On the UI thread","Synchronously"],"answer":"In parallel"},
        ],
    ),
    "cs_delegates": make_topic(
        intro="<p><strong>Delegates</strong> are type-safe function pointers in C# — they hold references to methods with a specific signature. Delegates enable callbacks, event handling, and functional programming patterns. C# provides built-in delegates: <code>Action</code> (void return), <code>Func</code> (with return value), and <code>Predicate</code> (returns bool). <strong>Events</strong> build on delegates to implement the observer/publish-subscribe pattern.</p>",
        subtopics=[
            {"title":"Built-in Delegates","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>Action<string> greet = name => Console.WriteLine($\"Hello, {name}\");\ngreet(\"Alice\");  // Hello, Alice\n\nFunc<int, int, int> add = (a, b) => a + b;\nConsole.WriteLine(add(3, 4));  // 7\n\nPredicate<int> isEven = n => n % 2 == 0;\nConsole.WriteLine(isEven(4));  // True</pre>"},
            {"title":"Events","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>class Button {\n    public event Action Clicked;\n    public void Click() => Clicked?.Invoke();\n}\n\nvar btn = new Button();\nbtn.Clicked += () => Console.WriteLine(\"Button clicked!\");\nbtn.Click();</pre>"},
        ],
        key_concepts="<ul><li><code>Action&lt;T&gt;</code>: delegate returning void. <code>Func&lt;T, TResult&gt;</code>: delegate with return value.</li><li><code>+=</code> subscribes to an event; <code>-=</code> unsubscribes.</li><li>Lambda expressions are shorthand for anonymous delegates: <code>(x, y) => x + y</code></li><li>Events are the foundation of UI frameworks (WPF, WinForms, Xamarin).</li></ul>",
        examples=[
            {"title":"Func & Action Delegates","code":"using System;\nusing System.Collections.Generic;\nusing System.Linq;\n\nclass Program {\n    static void Main() {\n        Func<int, int> square = x => x * x;\n        Func<int, bool> isOdd = n => n % 2 != 0;\n        Action<string> print = msg => Console.WriteLine(msg);\n        \n        var numbers = new List<int> {1, 2, 3, 4, 5};\n        \n        var oddSquares = numbers\n            .Where(n => isOdd(n))\n            .Select(n => square(n));\n        \n        print($\"Odd squares: {string.Join(\", \", oddSquares)}\");\n    }\n}","output":"Odd squares: 1, 9, 25","explanation":"<p>Delegates as first-class functions: passed to LINQ methods to filter and transform data.</p>"},
            {"title":"Event System","code":"using System;\n\nclass TemperatureSensor {\n    public event Action<double> TemperatureChanged;\n    private double _temp;\n    \n    public double Temperature {\n        get => _temp;\n        set { _temp = value; TemperatureChanged?.Invoke(value); }\n    }\n}\n\nclass Program {\n    static void Main() {\n        var sensor = new TemperatureSensor();\n        sensor.TemperatureChanged += t => Console.WriteLine($\"Display: {t:F1}C\");\n        sensor.TemperatureChanged += t => { if (t > 30) Console.WriteLine(\"WARNING: High temp!\"); };\n        \n        sensor.Temperature = 22.5;\n        sensor.Temperature = 35.0;\n    }\n}","output":"Display: 22.5C\nDisplay: 35.0C\nWARNING: High temp!","explanation":"<p>Multiple subscribers react to the same event — the observer pattern. Sensor doesn't know about its subscribers.</p>"},
            {"title":"Higher-Order Functions","code":"using System;\nusing System.Collections.Generic;\n\nclass Program {\n    static List<T> Filter<T>(List<T> list, Func<T, bool> predicate) {\n        var result = new List<T>();\n        foreach (var item in list)\n            if (predicate(item)) result.Add(item);\n        return result;\n    }\n    \n    static void Main() {\n        var nums = new List<int> {1, 2, 3, 4, 5, 6, 7, 8};\n        var evens = Filter(nums, n => n % 2 == 0);\n        var big = Filter(nums, n => n > 5);\n        \n        Console.WriteLine($\"Evens: {string.Join(\", \", evens)}\");\n        Console.WriteLine($\"Big: {string.Join(\", \", big)}\");\n    }\n}","output":"Evens: 2, 4, 6, 8\nBig: 6, 7, 8","explanation":"<p>A generic filter function taking any predicate delegate — this is how LINQ's <code>Where</code> works internally.</p>"},
        ],
        quiz=[
            {"q":"Func<int, string> represents a delegate that:","options":["Takes string, returns int","Takes int, returns string","Takes no args, returns int","Takes int, returns void"],"answer":"Takes int, returns string"},
            {"q":"Events use which operator to subscribe?","options":["=","->","+=","<<"],"answer":"+="},
        ],
    ),
    "cs_advanced": make_topic(
        intro="<p>Advanced C# features make it one of the most powerful languages for modern software development: <strong>pattern matching</strong> (complex conditional logic), <strong>tuples & deconstruction</strong>, <strong>records</strong> (immutable data), <strong>nullable reference types</strong> (compile-time null safety), <strong>source generators</strong>, and <strong>Span&lt;T&gt;</strong> (zero-allocation memory slicing). These features, combined with LINQ and async/await, make C# a top choice for enterprise, game (Unity), and cloud development.</p>",
        subtopics=[
            {"title":"Pattern Matching (C# 8-11)","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>string Classify(object obj) => obj switch {\n    int n when n < 0    => \"Negative\",\n    int n when n == 0   => \"Zero\",\n    int n               => $\"Positive: {n}\",\n    string s            => $\"String: {s}\",\n    null                => \"Null\",\n    _                   => \"Unknown\"\n};</pre>"},
            {"title":"Tuples & Deconstruction","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>(string Name, int Age) GetPerson() => (\"Alice\", 25);\n\nvar (name, age) = GetPerson();\nConsole.WriteLine($\"{name} is {age}\");</pre>"},
            {"title":"Nullable Reference Types (C# 8+)","content":"<p>Enable in project: <code>&lt;Nullable&gt;enable&lt;/Nullable&gt;</code>. The compiler warns when you might dereference null — catching NullReferenceException at compile time.</p>"},
        ],
        key_concepts="<ul><li>Switch expressions (C# 8+) replace verbose switch+case blocks with concise pattern matching.</li><li>Tuples return multiple values without creating a class: <code>(int Min, int Max) = GetRange();</code></li><li>Nullable reference types: <code>string?</code> warns on null dereference; <code>string</code> is expected non-null.</li><li>Records (C# 9+): immutable value objects with <code>with</code> expressions and value equality.</li></ul>",
        examples=[
            {"title":"Advanced Pattern Matching","code":"using System;\n\nclass Program {\n    static string Describe(object obj) => obj switch {\n        int n when n < 0 => $\"{n} is negative\",\n        int 0 => \"Zero\",\n        int n => $\"{n} is positive\",\n        string { Length: 0 } => \"Empty string\",\n        string s => $\"String: '{s}' (len={s.Length})\",\n        null => \"null\",\n        _ => $\"Unknown type: {obj.GetType()}\"\n    };\n    \n    static void Main() {\n        Console.WriteLine(Describe(-5));\n        Console.WriteLine(Describe(0));\n        Console.WriteLine(Describe(42));\n        Console.WriteLine(Describe(\"\"));\n        Console.WriteLine(Describe(\"Hello\"));\n        Console.WriteLine(Describe(null));\n    }\n}","output":"-5 is negative\nZero\n42 is positive\nEmpty string\nString: 'Hello' (len=5)\nnull","explanation":"<p>Switch expressions with pattern matching handle type testing, value testing, and property testing in one clean construct.</p>"},
            {"title":"Tuples for Multiple Returns","code":"using System;\nusing System.Linq;\n\nclass Program {\n    static (int Min, int Max, double Avg) Stats(int[] nums) {\n        return (nums.Min(), nums.Max(), nums.Average());\n    }\n    \n    static void Main() {\n        int[] data = {23, 45, 12, 67, 34, 89, 5};\n        var (min, max, avg) = Stats(data);\n        Console.WriteLine($\"Min: {min}, Max: {max}, Avg: {avg:F1}\");\n    }\n}","output":"Min: 5, Max: 89, Avg: 39.3","explanation":"<p>Named tuples return multiple values without creating a DTO class. Deconstruction unpacks them cleanly.</p>"},
            {"title":"Records with 'with' Expressions","code":"using System;\n\nrecord Address(string City, string Country);\nrecord Person(string Name, int Age, Address Address);\n\nclass Program {\n    static void Main() {\n        var alice = new Person(\"Alice\", 25, new Address(\"London\", \"UK\"));\n        var older = alice with { Age = 26 };\n        var moved = alice with { Address = new Address(\"Paris\", \"France\") };\n        \n        Console.WriteLine(alice);\n        Console.WriteLine(older);\n        Console.WriteLine(moved);\n        Console.WriteLine($\"Equal: {alice == older}\");\n    }\n}","output":"Person { Name = Alice, Age = 25, Address = Address { City = London, Country = UK } }\nPerson { Name = Alice, Age = 26, Address = Address { City = London, Country = UK } }\nPerson { Name = Alice, Age = 25, Address = Address { City = Paris, Country = France } }\nEqual: False","explanation":"<p>Records with <code>with</code> expressions create modified copies — immutability without the verbosity.</p>"},
        ],
        quiz=[
            {"q":"Switch expressions use which wildcard for default?","options":["default","else","*","_ (discard)"],"answer":"_ (discard)"},
            {"q":"Records provide which kind of equality?","options":["Reference","Value (structural)","Identity","Hash"],"answer":"Value (structural)"},
        ],
    ),
    "cs_interview": make_topic(
        intro="<p>C# interview questions span language fundamentals (value vs reference types, boxing/unboxing, nullable), OOP (abstract vs interface, SOLID principles), modern features (async/await, LINQ, pattern matching), .NET runtime (CLR, GC, JIT), and design patterns. Companies using C# (.NET shops, Unity studios, Microsoft partners) test both conceptual understanding and practical coding ability.</p>",
        subtopics=[
            {"title":"Core C# Interview Questions","content":"<ul><li><strong>Q: Value vs Reference types?</strong><br>A: Value types (int, struct) stored on stack, copied on assignment. Reference types (class, string) stored on heap, reference copied.</li><li><strong>Q: What is boxing/unboxing?</strong><br>A: Boxing: value type wrapped in object (heap allocation). Unboxing: object cast back to value type. Both are expensive — avoid in hot paths.</li><li><strong>Q: Abstract class vs Interface?</strong><br>A: Abstract class: can have implementation + fields, single inheritance. Interface: contract only (until C# 8 defaults), multiple implementation.</li><li><strong>Q: What is the difference between string and StringBuilder?</strong><br>A: string is immutable (new object on each modification); StringBuilder is mutable (modifies buffer in-place). Use StringBuilder for loops.</li></ul>"},
            {"title":"Async & Advanced Questions","content":"<ul><li><strong>Q: Why avoid async void?</strong><br>A: Exceptions in async void can't be caught — they crash the app. Only use for event handlers.</li><li><strong>Q: What is dependency injection?</strong><br>A: Classes receive dependencies via constructor (not creating them internally) — enables testing and loose coupling.</li><li><strong>Q: Explain the IDisposable pattern.</strong><br>A: For deterministic cleanup of unmanaged resources (files, connections). Use <code>using</code> statement for automatic disposal.</li></ul>"},
        ],
        key_concepts="<ul><li>Know <code>==</code> vs <code>.Equals()</code> vs <code>ReferenceEquals()</code> — reference equality vs value equality.</li><li>Understand garbage collection generations (Gen0, Gen1, Gen2) and finalizers.</li><li>Know SOLID principles — Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation, Dependency Inversion.</li><li>Know common .NET collections: <code>List</code>, <code>Dictionary</code>, <code>HashSet</code>, <code>Queue</code>, <code>Stack</code>, <code>ConcurrentDictionary</code>.</li></ul>",
        examples=[
            {"title":"Value vs Reference Type Demo","code":"using System;\n\nstruct Point { public int X, Y; }\nclass PointClass { public int X, Y; }\n\nclass Program {\n    static void Main() {\n        // Struct (value type) — copy\n        Point p1 = new() { X = 1, Y = 2 };\n        Point p2 = p1;  // copy\n        p2.X = 99;\n        Console.WriteLine($\"p1.X = {p1.X}\");  // 1 (unchanged)\n        \n        // Class (reference type) — shared\n        var c1 = new PointClass { X = 1, Y = 2 };\n        var c2 = c1;  // reference copy\n        c2.X = 99;\n        Console.WriteLine($\"c1.X = {c1.X}\");  // 99 (changed!)\n    }\n}","output":"p1.X = 1\nc1.X = 99","explanation":"<p>The fundamental interview question: struct (value type) copies on assignment; class (reference type) shares the same object.</p>"},
            {"title":"IDisposable & using","code":"using System;\nusing System.IO;\n\nclass TempFile : IDisposable {\n    public string Path { get; }\n    public TempFile() {\n        Path = System.IO.Path.GetTempFileName();\n        Console.WriteLine($\"Created: {Path}\");\n    }\n    public void Dispose() {\n        if (File.Exists(Path)) {\n            File.Delete(Path);\n            Console.WriteLine($\"Deleted: {Path}\");\n        }\n    }\n}\n\nclass Program {\n    static void Main() {\n        using (var temp = new TempFile()) {\n            File.WriteAllText(temp.Path, \"test data\");\n            Console.WriteLine($\"Size: {new FileInfo(temp.Path).Length} bytes\");\n        } // Dispose() called automatically here\n    }\n}","output":"Created: /tmp/abc123.tmp\nSize: 9 bytes\nDeleted: /tmp/abc123.tmp","explanation":"<p><code>using</code> block guarantees <code>Dispose()</code> is called — even if an exception occurs. Essential for file handles, connections, etc.</p>"},
            {"title":"SOLID - Dependency Inversion","code":"using System;\n\n// Abstraction\ninterface INotifier {\n    void Send(string message);\n}\n\n// Concrete implementations\nclass EmailNotifier : INotifier {\n    public void Send(string msg) => Console.WriteLine($\"Email: {msg}\");\n}\n\nclass SmsNotifier : INotifier {\n    public void Send(string msg) => Console.WriteLine($\"SMS: {msg}\");\n}\n\n// Depends on abstraction, not concrete class\nclass OrderService {\n    private readonly INotifier _notifier;\n    public OrderService(INotifier n) => _notifier = n;\n    public void PlaceOrder(string item) => _notifier.Send($\"Order: {item}\");\n}\n\nclass Program {\n    static void Main() {\n        new OrderService(new EmailNotifier()).PlaceOrder(\"Laptop\");\n        new OrderService(new SmsNotifier()).PlaceOrder(\"Phone\");\n    }\n}","output":"Email: Order: Laptop\nSMS: Order: Phone","explanation":"<p>Dependency Inversion Principle: <code>OrderService</code> depends on <code>INotifier</code> interface — swap email for SMS without changing the service.</p>"},
        ],
        quiz=[
            {"q":"What is boxing in C#?","options":["Converting string to int","Wrapping a value type in an object reference","Creating a new class","Casting between types"],"answer":"Wrapping a value type in an object reference"},
            {"q":"Why should you avoid async void?","options":["It's slower","Exceptions cannot be caught","It blocks the thread","It's deprecated"],"answer":"Exceptions cannot be caught"},
        ],
    ),
}

def load_data():
    with open(FILEPATH, 'r', encoding='utf-8') as f:
        content = f.read()
    prefix = 'window.tracksData = '
    idx = content.find(prefix)
    raw_json = content[idx + len(prefix):]
    suffix = ''
    if raw_json.strip().endswith(';'):
        raw_json = raw_json.strip()[:-1]
        suffix = ';'
    return content[:idx + len(prefix)], json.loads(raw_json), suffix

def save_data(prefix_content, data, suffix):
    with open(FILEPATH, 'w', encoding='utf-8') as f:
        f.write(prefix_content)
        f.write(json.dumps(data, ensure_ascii=False, separators=(',', ':')))
        f.write(suffix)

def apply_fixes(data, lang_key, fixes):
    fixed = 0
    for topic_key, new_content in fixes.items():
        if topic_key in data.get(lang_key, {}).get('content', {}):
            existing = data[lang_key]['content'][topic_key]
            new_content['title'] = existing.get('title', topic_key)
            new_content['phase'] = existing.get('phase', 1)
            data[lang_key]['content'][topic_key] = new_content
            fixed += 1
            print('  OK %s/%s' % (lang_key, topic_key))
        else:
            print('  MISS %s/%s' % (lang_key, topic_key))
    return fixed

if __name__ == '__main__':
    print('Loading tracks_data.js...')
    prefix_content, data, suffix = load_data()
    total = 0
    print('\n--- Fixing C# ---')
    total += apply_fixes(data, 'csharp', CSHARP_FIXES)
    print('\nSaving %d fixes...' % total)
    save_data(prefix_content, data, suffix)
    print('Done!')
