"""
Batch: HTML (18 topics) — full content with 3+ examples each
"""
import json, os
FILEPATH = os.path.join(os.path.dirname(__file__), '..', 'core', 'static', 'tracks_data.js')

def make_topic(intro, subtopics, key_concepts, examples, quiz, hands_on=None, problems=None):
    s = {"introduction": intro, "subtopics": subtopics, "key_concepts": key_concepts, "examples": examples}
    return {"structured": s, "concept_quiz": quiz, "hands_on": hands_on or {"title":"Try it!","description":"Practice the concept above.","hint":"Use the examples as a guide.","code":""}, "problem_solving": problems or []}

HTML_FIXES = {
    "html_basics": make_topic(
        intro="<p><strong>HTML</strong> (HyperText Markup Language) is the standard language for creating web pages. It defines the <strong>structure and content</strong> of a webpage using <strong>elements</strong> (tags). HTML is not a programming language — it's a <em>markup</em> language that tells the browser how to display content. Every website you visit is built on HTML. HTML5 (current version) added semantic elements, multimedia, canvas, and APIs for modern web applications.</p>",
        subtopics=[
            {"title":"HTML Document Structure","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>&lt;!DOCTYPE html&gt;\n&lt;html lang=\"en\"&gt;\n&lt;head&gt;\n    &lt;meta charset=\"UTF-8\"&gt;\n    &lt;meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"&gt;\n    &lt;title&gt;My Page&lt;/title&gt;\n&lt;/head&gt;\n&lt;body&gt;\n    &lt;h1&gt;Hello, World!&lt;/h1&gt;\n    &lt;p&gt;This is my first webpage.&lt;/p&gt;\n&lt;/body&gt;\n&lt;/html&gt;</pre>"},
            {"title":"Elements, Tags & Attributes","content":"<p>An HTML element has an <strong>opening tag</strong> (<code>&lt;p&gt;</code>), <strong>content</strong>, and a <strong>closing tag</strong> (<code>&lt;/p&gt;</code>). Some are self-closing: <code>&lt;img /&gt;</code>, <code>&lt;br /&gt;</code>. <strong>Attributes</strong> provide extra info: <code>&lt;a href=\"url\"&gt;</code>.</p>"},
            {"title":"Block vs Inline Elements","content":"<p><strong>Block elements</strong> take full width: <code>&lt;div&gt;</code>, <code>&lt;p&gt;</code>, <code>&lt;h1&gt;</code>-<code>&lt;h6&gt;</code>, <code>&lt;section&gt;</code>. <strong>Inline elements</strong> flow within text: <code>&lt;span&gt;</code>, <code>&lt;a&gt;</code>, <code>&lt;strong&gt;</code>, <code>&lt;em&gt;</code>, <code>&lt;img&gt;</code>.</p>"},
        ],
        key_concepts="<ul><li><code>&lt;!DOCTYPE html&gt;</code> declares HTML5 — must be the first line.</li><li><code>&lt;head&gt;</code> contains metadata, title, CSS/JS links — not visible on page.</li><li><code>&lt;body&gt;</code> contains all visible content.</li><li>HTML is case-insensitive but convention is lowercase.</li><li>Always include <code>lang</code>, <code>charset</code>, and <code>viewport</code> meta tags.</li></ul>",
        examples=[
            {"title":"Basic HTML Page","code":"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <title>My First Page</title>\n</head>\n<body>\n    <h1>Welcome!</h1>\n    <p>This is a <strong>paragraph</strong> with <em>formatted</em> text.</p>\n    <a href=\"https://example.com\">Visit Example</a>\n</body>\n</html>","output":"Renders: heading, paragraph with bold/italic text, and a clickable link","explanation":"<p>The minimal HTML page. <code>&lt;strong&gt;</code> makes text bold, <code>&lt;em&gt;</code> makes it italic, <code>&lt;a href&gt;</code> creates a hyperlink.</p>"},
            {"title":"Headings & Paragraphs","code":"<h1>Main Title (h1)</h1>\n<h2>Section Title (h2)</h2>\n<h3>Subsection (h3)</h3>\n<p>This is a paragraph. HTML collapses   multiple   spaces into one.</p>\n<p>Use <code>&lt;br&gt;</code> for<br>line breaks within a paragraph.</p>\n<hr>\n<p>A horizontal rule above separates sections.</p>","output":"Headings decrease in size h1 > h2 > h3. Paragraphs with line break and horizontal rule.","explanation":"<p>Use only one <code>&lt;h1&gt;</code> per page (SEO). <code>&lt;br&gt;</code> forces a line break. <code>&lt;hr&gt;</code> draws a horizontal line.</p>"},
            {"title":"Comments & Special Characters","code":"<!-- This is an HTML comment - not visible to users -->\n<p>Use &amp;amp; for &amp;, &amp;lt; for &lt;, &amp;gt; for &gt;</p>\n<p>Non-breaking space: hello&nbsp;&nbsp;&nbsp;world (3 spaces)</p>\n<p>Copyright: &copy; 2024 | Trademark: &trade;</p>","output":"Special characters rendered: &, <, >, non-breaking spaces, ©, ™","explanation":"<p>HTML entities display special characters. Comments (<code>&lt;!-- --&gt;</code>) are visible in source code but not rendered.</p>"},
        ],
        quiz=[
            {"q":"What does <!DOCTYPE html> declare?","options":["HTML4","XHTML","HTML5","XML"],"answer":"HTML5"},
            {"q":"Which element contains visible page content?","options":["<head>","<body>","<meta>","<html>"],"answer":"<body>"},
            {"q":"<strong> makes text:","options":["Italic","Bold","Underlined","Strikethrough"],"answer":"Bold"},
        ],
    ),
    "html_text": make_topic(
        intro="<p>HTML provides rich <strong>text formatting</strong> elements: headings (<code>&lt;h1&gt;</code>-<code>&lt;h6&gt;</code>), paragraphs (<code>&lt;p&gt;</code>), emphasis (<code>&lt;em&gt;</code>, <code>&lt;strong&gt;</code>), quotations (<code>&lt;blockquote&gt;</code>, <code>&lt;q&gt;</code>), preformatted text (<code>&lt;pre&gt;</code>), and code (<code>&lt;code&gt;</code>). Choosing the right element matters for <strong>accessibility</strong> (screen readers use heading hierarchy) and <strong>SEO</strong> (search engines weight headings).</p>",
        subtopics=[{"title":"Semantic Text Elements","content":"<ul><li><code>&lt;strong&gt;</code> — important text (bold)</li><li><code>&lt;em&gt;</code> — emphasized text (italic)</li><li><code>&lt;mark&gt;</code> — highlighted text</li><li><code>&lt;del&gt;</code> / <code>&lt;ins&gt;</code> — deleted / inserted text</li><li><code>&lt;sub&gt;</code> / <code>&lt;sup&gt;</code> — subscript / superscript</li><li><code>&lt;abbr title=\"..\"&gt;</code> — abbreviation with tooltip</li></ul>"},{"title":"Blockquote & Code","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>&lt;blockquote cite=\"source\"&gt;\n  &lt;p&gt;The only way to do great work is to love what you do.&lt;/p&gt;\n  &lt;footer&gt;— Steve Jobs&lt;/footer&gt;\n&lt;/blockquote&gt;\n\n&lt;pre&gt;&lt;code&gt;\nfunction hello() {\n    console.log(\"Hello!\");\n}\n&lt;/code&gt;&lt;/pre&gt;</pre>"}],
        key_concepts="<ul><li>Use <code>&lt;strong&gt;</code> not <code>&lt;b&gt;</code> — it has semantic meaning (importance).</li><li>Use <code>&lt;em&gt;</code> not <code>&lt;i&gt;</code> — screen readers use emphasis differently.</li><li><code>&lt;pre&gt;</code> preserves whitespace and line breaks — used for code display.</li><li>Heading hierarchy: <code>&lt;h1&gt;</code> → <code>&lt;h2&gt;</code> → <code>&lt;h3&gt;</code> — never skip levels.</li></ul>",
        examples=[
            {"title":"Text Formatting","code":"<p>This is <strong>bold/important</strong> text.</p>\n<p>This is <em>italic/emphasized</em> text.</p>\n<p>This is <mark>highlighted</mark> text.</p>\n<p>This is <del>deleted</del> and <ins>inserted</ins> text.</p>\n<p>Water is H<sub>2</sub>O. E = mc<sup>2</sup>.</p>\n<p><abbr title=\"HyperText Markup Language\">HTML</abbr> is awesome!</p>","output":"Various text formatting: bold, italic, highlight, strikethrough, subscript/superscript, abbreviation","explanation":"<p>Semantic elements convey meaning to screen readers and search engines, not just visual styling.</p>"},
            {"title":"Blockquote & Citation","code":"<blockquote cite=\"https://example.com\">\n    <p>The best way to predict the future is to invent it.</p>\n    <footer>— <cite>Alan Kay</cite></footer>\n</blockquote>\n\n<p>As <q>someone once said</q>, inline quotes use the q element.</p>","output":"A styled blockquote with citation and an inline quote with quotation marks","explanation":"<p><code>&lt;blockquote&gt;</code> for block-level quotes, <code>&lt;q&gt;</code> for inline. Browsers add quotation marks to <code>&lt;q&gt;</code>.</p>"},
            {"title":"Code Display","code":"<p>Use <code>console.log()</code> to print output.</p>\n\n<pre><code>function greet(name) {\n    return `Hello, ${name}!`;\n}\n\nconsole.log(greet(\"World\"));</code></pre>\n\n<p>Keyboard shortcut: <kbd>Ctrl</kbd> + <kbd>S</kbd> to save.</p>","output":"Inline code, preformatted code block, and keyboard shortcuts","explanation":"<p><code>&lt;code&gt;</code> for inline code, <code>&lt;pre&gt;&lt;code&gt;</code> for code blocks. <code>&lt;kbd&gt;</code> for keyboard keys.</p>"},
        ],
        quiz=[
            {"q":"<strong> vs <b>: what's the difference?","options":["No difference","<strong> has semantic meaning (importance)","<b> is newer","<strong> is deprecated"],"answer":"<strong> has semantic meaning (importance)"},
            {"q":"Which element preserves whitespace?","options":["<p>","<div>","<pre>","<span>"],"answer":"<pre>"},
        ],
    ),
    "html_links": make_topic(
        intro="<p><strong>Hyperlinks</strong> (<code>&lt;a&gt;</code>) are the foundation of the web — they connect pages and resources. Links can navigate to other pages, sections on the same page (anchors), email addresses, phone numbers, and downloadable files. The <code>href</code> attribute specifies the destination, and <code>target</code> controls where it opens.</p>",
        subtopics=[{"title":"Link Types","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>&lt;a href=\"https://example.com\"&gt;External Link&lt;/a&gt;\n&lt;a href=\"/about.html\"&gt;Internal Link&lt;/a&gt;\n&lt;a href=\"#section1\"&gt;Anchor Link (same page)&lt;/a&gt;\n&lt;a href=\"mailto:user@example.com\"&gt;Email Link&lt;/a&gt;\n&lt;a href=\"tel:+1234567890\"&gt;Call Us&lt;/a&gt;\n&lt;a href=\"file.pdf\" download&gt;Download PDF&lt;/a&gt;\n&lt;a href=\"https://example.com\" target=\"_blank\" rel=\"noopener\"&gt;New Tab&lt;/a&gt;</pre>"},{"title":"Navigation","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>&lt;nav&gt;\n  &lt;a href=\"/\"&gt;Home&lt;/a&gt;\n  &lt;a href=\"/about\"&gt;About&lt;/a&gt;\n  &lt;a href=\"/contact\"&gt;Contact&lt;/a&gt;\n&lt;/nav&gt;</pre>"}],
        key_concepts="<ul><li><code>target=\"_blank\"</code> opens in new tab — always add <code>rel=\"noopener noreferrer\"</code> for security.</li><li>Anchor links (<code>#id</code>) scroll to elements with matching <code>id</code> attribute.</li><li><code>mailto:</code> opens email client; <code>tel:</code> opens phone dialer on mobile.</li><li><code>download</code> attribute forces file download instead of opening.</li></ul>",
        examples=[
            {"title":"Various Link Types","code":"<h2>Links</h2>\n<p><a href=\"https://google.com\">Google (same tab)</a></p>\n<p><a href=\"https://google.com\" target=\"_blank\" rel=\"noopener\">Google (new tab)</a></p>\n<p><a href=\"mailto:hello@example.com\">Send Email</a></p>\n<p><a href=\"tel:+15551234567\">Call: (555) 123-4567</a></p>\n<p><a href=\"#bottom\">Jump to Bottom</a></p>\n\n<!-- ... page content ... -->\n\n<p id=\"bottom\">You scrolled here via anchor!</p>","output":"Multiple clickable links: regular, new tab, email, phone, and page anchor","explanation":"<p>Each link type triggers different actions. <code>rel=\"noopener\"</code> prevents the opened page from accessing <code>window.opener</code>.</p>"},
            {"title":"Navigation Bar","code":"<nav style=\"background: #333; padding: 10px;\">\n    <a href=\"/\" style=\"color: white; margin: 0 15px; text-decoration: none;\">Home</a>\n    <a href=\"/products\" style=\"color: white; margin: 0 15px; text-decoration: none;\">Products</a>\n    <a href=\"/about\" style=\"color: white; margin: 0 15px; text-decoration: none;\">About</a>\n    <a href=\"/contact\" style=\"color: white; margin: 0 15px; text-decoration: none;\">Contact</a>\n</nav>","output":"A dark navigation bar with white text links","explanation":"<p><code>&lt;nav&gt;</code> is a semantic element that tells screen readers this is a navigation section.</p>"},
            {"title":"Image as Link","code":"<a href=\"https://example.com\">\n    <img src=\"logo.png\" alt=\"Company Logo\" width=\"200\">\n</a>\n\n<!-- Link with title tooltip -->\n<a href=\"/help\" title=\"Get help and support\">\n    Need help?\n</a>","output":"A clickable image and a link with hover tooltip","explanation":"<p>Wrap any element in <code>&lt;a&gt;</code> to make it clickable. <code>title</code> attribute shows a tooltip on hover.</p>"},
        ],
        quiz=[
            {"q":"Which attribute opens a link in a new tab?","options":["href=\"_new\"","target=\"_blank\"","open=\"new\"","window=\"blank\""],"answer":"target=\"_blank\""},
            {"q":"What does rel=\"noopener\" prevent?","options":["Pop-up blocking","The opened page from accessing window.opener","CORS errors","Caching"],"answer":"The opened page from accessing window.opener"},
        ],
    ),
    "html_images": make_topic(
        intro="<p>The <code>&lt;img&gt;</code> element embeds images in HTML. The <code>src</code> attribute specifies the image source (URL or path), and <code>alt</code> provides alternative text for accessibility (screen readers) and when the image fails to load. Modern HTML adds <code>&lt;picture&gt;</code> for responsive images and <code>&lt;figure&gt;</code>/<code>&lt;figcaption&gt;</code> for captioned images.</p>",
        subtopics=[{"title":"Image Fundamentals","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>&lt;img src=\"photo.jpg\" alt=\"A sunset\" width=\"400\" height=\"300\"&gt;\n&lt;img src=\"logo.svg\" alt=\"Company Logo\" loading=\"lazy\"&gt;</pre>"},{"title":"Responsive Images","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>&lt;picture&gt;\n  &lt;source media=\"(min-width: 800px)\" srcset=\"large.jpg\"&gt;\n  &lt;source media=\"(min-width: 400px)\" srcset=\"medium.jpg\"&gt;\n  &lt;img src=\"small.jpg\" alt=\"Responsive image\"&gt;\n&lt;/picture&gt;</pre>"}],
        key_concepts="<ul><li><code>alt</code> is REQUIRED — describes the image for screen readers and SEO.</li><li><code>width</code>/<code>height</code> prevent layout shifts while image loads (CLS optimization).</li><li><code>loading=\"lazy\"</code> defers loading until image is near viewport — improves page speed.</li><li>Common formats: <code>.jpg</code> (photos), <code>.png</code> (transparency), <code>.svg</code> (vector), <code>.webp</code> (modern, smaller).</li></ul>",
        examples=[
            {"title":"Basic Image","code":"<img \n    src=\"https://via.placeholder.com/400x200\" \n    alt=\"Placeholder image 400x200\"\n    width=\"400\" \n    height=\"200\"\n>\n<p>Image with defined dimensions prevents layout shift.</p>","output":"A 400x200 placeholder image with text below","explanation":"<p>Always set <code>width</code> and <code>height</code> — browsers reserve space before load, preventing content from jumping.</p>"},
            {"title":"Figure with Caption","code":"<figure>\n    <img src=\"chart.png\" alt=\"Sales data Q1-Q4 2024\" style=\"max-width: 100%;\">\n    <figcaption>Figure 1: Quarterly sales data for 2024.</figcaption>\n</figure>","output":"An image with a caption underneath","explanation":"<p><code>&lt;figure&gt;</code> and <code>&lt;figcaption&gt;</code> semantically associate an image with its caption.</p>"},
            {"title":"Image Gallery","code":"<div style=\"display: flex; gap: 10px; flex-wrap: wrap;\">\n    <img src=\"img1.jpg\" alt=\"Mountain\" width=\"200\" height=\"150\" loading=\"lazy\">\n    <img src=\"img2.jpg\" alt=\"Lake\" width=\"200\" height=\"150\" loading=\"lazy\">\n    <img src=\"img3.jpg\" alt=\"Forest\" width=\"200\" height=\"150\" loading=\"lazy\">\n    <img src=\"img4.jpg\" alt=\"Desert\" width=\"200\" height=\"150\" loading=\"lazy\">\n</div>","output":"A responsive image gallery with 4 images in a flex row","explanation":"<p><code>loading=\"lazy\"</code> on gallery images defers loading until they scroll into view — crucial for performance.</p>"},
        ],
        quiz=[
            {"q":"The alt attribute is:","options":["Optional styling","Required for accessibility","Only for SEO","Decorative only"],"answer":"Required for accessibility"},
            {"q":"loading='lazy' does:","options":["Loads image slowly","Defers loading until near viewport","Reduces image quality","Adds animation"],"answer":"Defers loading until near viewport"},
        ],
    ),
    "html_lists":make_topic(intro="<p>HTML provides three types of lists: <strong>ordered lists</strong> (<code>&lt;ol&gt;</code>) with numbered items, <strong>unordered lists</strong> (<code>&lt;ul&gt;</code>) with bullet points, and <strong>description lists</strong> (<code>&lt;dl&gt;</code>) with term-description pairs. Lists can be nested and styled with CSS. They are also used for navigation menus.</p>",subtopics=[{"title":"List Types","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>&lt;ul&gt;&lt;li&gt;Unordered item&lt;/li&gt;&lt;/ul&gt;\n&lt;ol&gt;&lt;li&gt;Ordered item&lt;/li&gt;&lt;/ol&gt;\n&lt;dl&gt;&lt;dt&gt;Term&lt;/dt&gt;&lt;dd&gt;Definition&lt;/dd&gt;&lt;/dl&gt;</pre>"}],key_concepts="<ul><li><code>&lt;ol start=\"5\"&gt;</code> starts numbering at 5.</li><li><code>&lt;ol type=\"A\"&gt;</code> uses letters: A, B, C.</li><li>Lists can be nested: <code>&lt;li&gt;Item&lt;ul&gt;&lt;li&gt;Sub-item&lt;/li&gt;&lt;/ul&gt;&lt;/li&gt;</code></li><li>Navigation menus are typically <code>&lt;nav&gt;&lt;ul&gt;&lt;li&gt;&lt;a&gt;</code> structures.</li></ul>",examples=[
            {"title":"Ordered & Unordered Lists","code":"<h3>Shopping List (unordered)</h3>\n<ul>\n    <li>Milk</li>\n    <li>Bread</li>\n    <li>Eggs</li>\n</ul>\n\n<h3>Steps to Cook (ordered)</h3>\n<ol>\n    <li>Preheat oven to 350F</li>\n    <li>Mix ingredients</li>\n    <li>Bake for 30 minutes</li>\n</ol>","output":"A bullet list and a numbered list","explanation":"<p>Use unordered for collections where order doesn't matter; ordered when sequence is important.</p>"},
            {"title":"Nested List","code":"<ul>\n    <li>Frontend\n        <ul>\n            <li>HTML</li>\n            <li>CSS</li>\n            <li>JavaScript</li>\n        </ul>\n    </li>\n    <li>Backend\n        <ul>\n            <li>Python</li>\n            <li>Node.js</li>\n            <li>PHP</li>\n        </ul>\n    </li>\n</ul>","output":"A nested tree-like list structure","explanation":"<p>Nested lists create hierarchical structures — commonly used for category trees and table of contents.</p>"},
            {"title":"Description List","code":"<dl>\n    <dt>HTML</dt>\n    <dd>HyperText Markup Language — structure of web pages</dd>\n    \n    <dt>CSS</dt>\n    <dd>Cascading Style Sheets — styling and layout</dd>\n    \n    <dt>JavaScript</dt>\n    <dd>Programming language for web interactivity</dd>\n</dl>","output":"Terms with indented definitions","explanation":"<p><code>&lt;dl&gt;</code> is perfect for glossaries, FAQs, and metadata — semantically correct for term-definition pairs.</p>"},
        ],quiz=[{"q":"Which list type uses numbered items?","options":["<ul>","<ol>","<dl>","<nl>"],"answer":"<ol>"},{"q":"<dl> stands for:","options":["Dynamic list","Download list","Description list","Data list"],"answer":"Description list"}]),
    "html_tables":make_topic(intro="<p>HTML tables display data in rows and columns using <code>&lt;table&gt;</code>, <code>&lt;tr&gt;</code> (table row), <code>&lt;th&gt;</code> (header cell), and <code>&lt;td&gt;</code> (data cell). Tables should only be used for <em>tabular data</em>, not page layout. Use <code>&lt;thead&gt;</code>, <code>&lt;tbody&gt;</code>, <code>&lt;tfoot&gt;</code> for semantic structure, and <code>colspan</code>/<code>rowspan</code> to merge cells.</p>",subtopics=[{"title":"Table Structure","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>&lt;table&gt;\n  &lt;thead&gt;\n    &lt;tr&gt;&lt;th&gt;Name&lt;/th&gt;&lt;th&gt;Score&lt;/th&gt;&lt;/tr&gt;\n  &lt;/thead&gt;\n  &lt;tbody&gt;\n    &lt;tr&gt;&lt;td&gt;Alice&lt;/td&gt;&lt;td&gt;95&lt;/td&gt;&lt;/tr&gt;\n    &lt;tr&gt;&lt;td&gt;Bob&lt;/td&gt;&lt;td&gt;87&lt;/td&gt;&lt;/tr&gt;\n  &lt;/tbody&gt;\n&lt;/table&gt;</pre>"}],key_concepts="<ul><li><code>&lt;th&gt;</code> cells are bold and centered by default — used for headers.</li><li><code>colspan=\"2\"</code> spans a cell across 2 columns.</li><li><code>rowspan=\"2\"</code> spans a cell across 2 rows.</li><li>Always use <code>&lt;thead&gt;</code>/<code>&lt;tbody&gt;</code> for accessibility and print styling.</li></ul>",examples=[
            {"title":"Basic Table","code":"<table border=\"1\" style=\"border-collapse: collapse; width: 100%;\">\n    <thead>\n        <tr>\n            <th>Name</th>\n            <th>Age</th>\n            <th>City</th>\n        </tr>\n    </thead>\n    <tbody>\n        <tr><td>Alice</td><td>25</td><td>New York</td></tr>\n        <tr><td>Bob</td><td>30</td><td>London</td></tr>\n        <tr><td>Charlie</td><td>22</td><td>Tokyo</td></tr>\n    </tbody>\n</table>","output":"A 3-column table with header row and 3 data rows","explanation":"<p><code>border-collapse: collapse</code> merges cell borders for a clean look.</p>"},
            {"title":"Colspan & Rowspan","code":"<table border=\"1\" style=\"border-collapse: collapse;\">\n    <tr>\n        <th colspan=\"3\">Student Report</th>\n    </tr>\n    <tr>\n        <th>Subject</th><th>Q1</th><th>Q2</th>\n    </tr>\n    <tr>\n        <td>Math</td><td>85</td><td>90</td>\n    </tr>\n    <tr>\n        <td>Science</td><td>78</td><td>82</td>\n    </tr>\n    <tr>\n        <td colspan=\"2\"><strong>Average</strong></td>\n        <td>83.75</td>\n    </tr>\n</table>","output":"A table with merged header and footer cells","explanation":"<p><code>colspan=\"3\"</code> makes the title span all 3 columns. The average row spans 2 columns with the label.</p>"},
            {"title":"Styled Table","code":"<table style=\"border-collapse: collapse; width: 100%; font-family: sans-serif;\">\n    <thead style=\"background: #2d3748; color: white;\">\n        <tr><th style=\"padding: 12px;\">Product</th><th style=\"padding: 12px;\">Price</th><th style=\"padding: 12px;\">Stock</th></tr>\n    </thead>\n    <tbody>\n        <tr style=\"background: #f7fafc;\"><td style=\"padding: 10px;\">Laptop</td><td>$999</td><td>15</td></tr>\n        <tr style=\"background: #edf2f7;\"><td style=\"padding: 10px;\">Mouse</td><td>$29</td><td>150</td></tr>\n        <tr style=\"background: #f7fafc;\"><td style=\"padding: 10px;\">Keyboard</td><td>$79</td><td>85</td></tr>\n    </tbody>\n</table>","output":"A professionally styled table with alternating row colors","explanation":"<p>Alternating row colors (zebra striping) improves readability — typically done with CSS <code>:nth-child(even)</code>.</p>"},
        ],quiz=[{"q":"<th> is used for:","options":["Table data cells","Table header cells","Table rows","Table footer"],"answer":"Table header cells"},{"q":"colspan='2' makes a cell span:","options":["2 rows","2 columns","2 tables","2 pages"],"answer":"2 columns"}]),
    "html_forms":make_topic(intro="<p>HTML forms collect user input via <code>&lt;form&gt;</code> containing input elements: text fields, checkboxes, radio buttons, dropdowns, textareas, and buttons. Forms submit data via <strong>GET</strong> (in URL) or <strong>POST</strong> (in body) to a server. HTML5 added built-in validation attributes: <code>required</code>, <code>minlength</code>, <code>pattern</code>, <code>type=\"email\"</code>, and more.</p>",subtopics=[{"title":"Form Elements","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>&lt;form action=\"/submit\" method=\"POST\"&gt;\n  &lt;label for=\"name\"&gt;Name:&lt;/label&gt;\n  &lt;input type=\"text\" id=\"name\" name=\"name\" required&gt;\n  &lt;input type=\"email\" name=\"email\" placeholder=\"you@email.com\"&gt;\n  &lt;input type=\"password\" name=\"pass\" minlength=\"8\"&gt;\n  &lt;textarea name=\"bio\" rows=\"4\"&gt;&lt;/textarea&gt;\n  &lt;select name=\"role\"&gt;\n    &lt;option value=\"user\"&gt;User&lt;/option&gt;\n    &lt;option value=\"admin\"&gt;Admin&lt;/option&gt;\n  &lt;/select&gt;\n  &lt;button type=\"submit\"&gt;Submit&lt;/button&gt;\n&lt;/form&gt;</pre>"}],key_concepts="<ul><li>Every input needs a <code>name</code> attribute — it's the key in the submitted data.</li><li><code>&lt;label for=\"id\"&gt;</code> links label to input — clicking the label focuses the input (accessibility).</li><li>HTML5 validation: <code>required</code>, <code>type=\"email\"</code>, <code>min</code>/<code>max</code>, <code>pattern</code>, <code>minlength</code>/<code>maxlength</code>.</li><li><code>method=\"GET\"</code> for searches/filters; <code>method=\"POST\"</code> for creating/modifying data.</li></ul>",examples=[
            {"title":"Registration Form","code":"<form action=\"/register\" method=\"POST\">\n    <div>\n        <label for=\"username\">Username:</label><br>\n        <input type=\"text\" id=\"username\" name=\"username\" required minlength=\"3\" maxlength=\"20\">\n    </div>\n    <div>\n        <label for=\"email\">Email:</label><br>\n        <input type=\"email\" id=\"email\" name=\"email\" required>\n    </div>\n    <div>\n        <label for=\"password\">Password:</label><br>\n        <input type=\"password\" id=\"password\" name=\"password\" required minlength=\"8\">\n    </div>\n    <div>\n        <label for=\"age\">Age:</label><br>\n        <input type=\"number\" id=\"age\" name=\"age\" min=\"13\" max=\"120\">\n    </div>\n    <button type=\"submit\">Register</button>\n</form>","output":"A form with username, email, password, and age fields with validation","explanation":"<p>HTML5 validation attributes handle basic validation without JavaScript — <code>required</code>, <code>min</code>, <code>type=\"email\"</code>.</p>"},
            {"title":"Checkboxes & Radio Buttons","code":"<form>\n    <fieldset>\n        <legend>Choose your skills:</legend>\n        <label><input type=\"checkbox\" name=\"skills\" value=\"html\"> HTML</label><br>\n        <label><input type=\"checkbox\" name=\"skills\" value=\"css\"> CSS</label><br>\n        <label><input type=\"checkbox\" name=\"skills\" value=\"js\" checked> JavaScript</label>\n    </fieldset>\n    \n    <fieldset>\n        <legend>Experience level:</legend>\n        <label><input type=\"radio\" name=\"level\" value=\"beginner\"> Beginner</label><br>\n        <label><input type=\"radio\" name=\"level\" value=\"mid\" checked> Mid-level</label><br>\n        <label><input type=\"radio\" name=\"level\" value=\"senior\"> Senior</label>\n    </fieldset>\n</form>","output":"Checkbox group (multi-select) and radio button group (single-select)","explanation":"<p>Checkboxes allow multiple selections; radios (same <code>name</code>) allow only one. <code>&lt;fieldset&gt;</code> groups related inputs.</p>"},
            {"title":"HTML5 Input Types","code":"<form>\n    <label>Date: <input type=\"date\" name=\"date\"></label><br>\n    <label>Time: <input type=\"time\" name=\"time\"></label><br>\n    <label>Color: <input type=\"color\" name=\"color\" value=\"#3b82f6\"></label><br>\n    <label>Range: <input type=\"range\" name=\"vol\" min=\"0\" max=\"100\" value=\"50\"></label><br>\n    <label>File: <input type=\"file\" name=\"upload\" accept=\".jpg,.png\"></label><br>\n    <label>URL: <input type=\"url\" name=\"website\" placeholder=\"https://...\"></label><br>\n    <label>Search: <input type=\"search\" name=\"q\" placeholder=\"Search...\"></label>\n</form>","output":"Various HTML5 input types: date picker, color picker, range slider, file upload","explanation":"<p>HTML5 input types provide native UI widgets — no JavaScript needed for date pickers or color selectors.</p>"},
        ],quiz=[{"q":"Which attribute makes an input mandatory?","options":["mandatory","needed","required","must"],"answer":"required"},{"q":"Radio buttons with the same name allow:","options":["Multiple selections","Only one selection","No selection","Unlimited selections"],"answer":"Only one selection"}]),
    "html_semantic":make_topic(intro="<p><strong>Semantic HTML</strong> uses meaningful elements that describe their content: <code>&lt;header&gt;</code>, <code>&lt;nav&gt;</code>, <code>&lt;main&gt;</code>, <code>&lt;article&gt;</code>, <code>&lt;section&gt;</code>, <code>&lt;aside&gt;</code>, <code>&lt;footer&gt;</code>. These replaced generic <code>&lt;div&gt;</code> soup, improving accessibility, SEO, and code readability.</p>",subtopics=[{"title":"Semantic Elements","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>&lt;header&gt;Site header / logo / nav&lt;/header&gt;\n&lt;nav&gt;Navigation links&lt;/nav&gt;\n&lt;main&gt;\n  &lt;article&gt;Self-contained content&lt;/article&gt;\n  &lt;section&gt;Thematic grouping&lt;/section&gt;\n  &lt;aside&gt;Sidebar / tangential content&lt;/aside&gt;\n&lt;/main&gt;\n&lt;footer&gt;Copyright / contact info&lt;/footer&gt;</pre>"}],key_concepts="<ul><li><code>&lt;main&gt;</code> — unique content of the page (only one per page).</li><li><code>&lt;article&gt;</code> — self-contained, independently distributable (blog post, comment).</li><li><code>&lt;section&gt;</code> — thematic grouping of content (chapters, tabs).</li><li><code>&lt;aside&gt;</code> — tangentially related content (sidebars, pull quotes).</li></ul>",examples=[
            {"title":"Semantic Page Layout","code":"<!DOCTYPE html>\n<html lang=\"en\">\n<body>\n    <header>\n        <h1>My Blog</h1>\n        <nav>\n            <a href=\"/\">Home</a>\n            <a href=\"/about\">About</a>\n        </nav>\n    </header>\n    \n    <main>\n        <article>\n            <h2>First Blog Post</h2>\n            <time datetime=\"2024-01-15\">January 15, 2024</time>\n            <p>Article content goes here...</p>\n        </article>\n        \n        <aside>\n            <h3>Related Posts</h3>\n            <ul><li><a href=\"#\">Another post</a></li></ul>\n        </aside>\n    </main>\n    \n    <footer>\n        <p>&copy; 2024 My Blog. All rights reserved.</p>\n    </footer>\n</body>\n</html>","output":"A well-structured page with header, nav, article, sidebar, and footer","explanation":"<p>Screen readers announce these landmarks: 'navigation', 'main content', 'complementary' — enabling quick page navigation for users with disabilities.</p>"},
            {"title":"Article vs Section","code":"<!-- Article: self-contained content -->\n<article>\n    <h2>Understanding JavaScript Closures</h2>\n    <p>A closure is...</p>\n    <footer>By Alice | <time datetime=\"2024-01-15\">Jan 15</time></footer>\n</article>\n\n<!-- Section: thematic grouping -->\n<section>\n    <h2>Getting Started</h2>\n    <p>To begin learning HTML...</p>\n</section>\n<section>\n    <h2>Advanced Topics</h2>\n    <p>Once you master the basics...</p>\n</section>","output":"An article (blog post) and two sections (chapters)","explanation":"<p>Use <code>&lt;article&gt;</code> when content makes sense independently (could be syndicated). Use <code>&lt;section&gt;</code> for grouping related content.</p>"},
            {"title":"Div vs Semantic Elements","code":"<!-- BAD: Div soup -->\n<div class=\"header\">\n    <div class=\"nav\">...</div>\n</div>\n<div class=\"content\">\n    <div class=\"post\">...</div>\n    <div class=\"sidebar\">...</div>\n</div>\n<div class=\"footer\">...</div>\n\n<!-- GOOD: Semantic HTML -->\n<header>\n    <nav>...</nav>\n</header>\n<main>\n    <article>...</article>\n    <aside>...</aside>\n</main>\n<footer>...</footer>","output":"Comparison: div-based vs semantic HTML (same visual result, better accessibility)","explanation":"<p>Semantic HTML provides the same visual result but with meaning — search engines and screen readers understand the page structure.</p>"},
        ],quiz=[{"q":"Which element should appear only once per page?","options":["<section>","<article>","<main>","<header>"],"answer":"<main>"},{"q":"<article> represents:","options":["Page navigation","Self-contained content","A sidebar","Page footer"],"answer":"Self-contained content"}]),
    "html_media":make_topic(intro="<p>HTML5 introduced native <code>&lt;video&gt;</code> and <code>&lt;audio&gt;</code> elements, eliminating the need for Flash or plugins. Both support multiple source formats for cross-browser compatibility, playback controls, autoplay, loop, and JavaScript API for custom players.</p>",subtopics=[{"title":"Video & Audio","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>&lt;video controls width=\"640\"&gt;\n  &lt;source src=\"video.mp4\" type=\"video/mp4\"&gt;\n  &lt;source src=\"video.webm\" type=\"video/webm\"&gt;\n  Your browser doesn't support video.\n&lt;/video&gt;\n\n&lt;audio controls&gt;\n  &lt;source src=\"song.mp3\" type=\"audio/mpeg\"&gt;\n  &lt;source src=\"song.ogg\" type=\"audio/ogg\"&gt;\n&lt;/audio&gt;</pre>"}],key_concepts="<ul><li><code>controls</code> shows play/pause/volume UI. Without it, video is silent and uncontrollable.</li><li>Provide multiple <code>&lt;source&gt;</code> formats for compatibility: MP4 + WebM.</li><li><code>autoplay</code> + <code>muted</code> for auto-playing (browsers block unmuted autoplay).</li><li><code>poster=\"thumb.jpg\"</code> shows a preview image before playback.</li></ul>",examples=[
            {"title":"Video Player","code":"<video controls width=\"640\" poster=\"preview.jpg\">\n    <source src=\"demo.mp4\" type=\"video/mp4\">\n    <source src=\"demo.webm\" type=\"video/webm\">\n    <p>Your browser doesn't support HTML5 video. <a href=\"demo.mp4\">Download</a> instead.</p>\n</video>","output":"A video player with play controls and preview image","explanation":"<p>Fallback text inside <code>&lt;video&gt;</code> shows for old browsers. <code>poster</code> displays before play is clicked.</p>"},
            {"title":"YouTube Embed","code":"<iframe \n    width=\"560\" \n    height=\"315\" \n    src=\"https://www.youtube.com/embed/dQw4w9WgXcQ\" \n    title=\"YouTube video\" \n    frameborder=\"0\" \n    allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" \n    allowfullscreen>\n</iframe>","output":"An embedded YouTube video player","explanation":"<p><code>&lt;iframe&gt;</code> embeds external content. YouTube provides embed URLs in the share dialog.</p>"},
            {"title":"Audio Player","code":"<h3>Podcast Episode</h3>\n<audio controls style=\"width: 100%;\">\n    <source src=\"episode.mp3\" type=\"audio/mpeg\">\n    <source src=\"episode.ogg\" type=\"audio/ogg\">\n    Your browser doesn't support audio.\n</audio>\n<p><small>Duration: 45:30</small></p>","output":"An audio player with playback controls","explanation":"<p>HTML5 audio works identically to video — <code>controls</code>, multiple sources, and fallback text.</p>"},
        ],quiz=[{"q":"To auto-play video in modern browsers, you also need:","options":["autoplay only","autoplay + muted","autoplay + controls","autoplay + loop"],"answer":"autoplay + muted"},{"q":"<source> allows multiple formats because:","options":["Faster loading","Browser compatibility","Better quality","Smaller files"],"answer":"Browser compatibility"}]),
    "html_meta":make_topic(intro="<p><strong>Meta tags</strong> provide metadata about the HTML document — information for browsers, search engines, and social media. They go inside <code>&lt;head&gt;</code> and include character encoding, viewport settings, descriptions, keywords, Open Graph (Facebook), Twitter Cards, and robots directives.</p>",subtopics=[{"title":"Essential Meta Tags","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>&lt;meta charset=\"UTF-8\"&gt;\n&lt;meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"&gt;\n&lt;meta name=\"description\" content=\"Learn HTML fundamentals\"&gt;\n&lt;meta name=\"author\" content=\"Alice\"&gt;\n&lt;meta name=\"robots\" content=\"index, follow\"&gt;\n\n&lt;!-- Open Graph (Facebook/LinkedIn) --&gt;\n&lt;meta property=\"og:title\" content=\"My Page\"&gt;\n&lt;meta property=\"og:description\" content=\"Description\"&gt;\n&lt;meta property=\"og:image\" content=\"preview.jpg\"&gt;</pre>"}],key_concepts="<ul><li><code>charset=\"UTF-8\"</code>: supports all international characters.</li><li><code>viewport</code>: essential for mobile responsiveness.</li><li><code>description</code>: shown in Google search results (150-160 chars).</li><li>Open Graph tags control how links appear when shared on social media.</li></ul>",examples=[
            {"title":"Complete Head Section","code":"<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <meta name=\"description\" content=\"Learn HTML basics with practical examples\">\n    <meta name=\"keywords\" content=\"HTML, web development, tutorial\">\n    <meta name=\"author\" content=\"Alice Developer\">\n    <meta name=\"robots\" content=\"index, follow\">\n    \n    <meta property=\"og:title\" content=\"HTML Tutorial\">\n    <meta property=\"og:description\" content=\"Complete HTML guide for beginners\">\n    <meta property=\"og:type\" content=\"website\">\n    \n    <title>HTML Tutorial | Learn Web Development</title>\n    <link rel=\"icon\" href=\"/favicon.ico\" type=\"image/x-icon\">\n    <link rel=\"stylesheet\" href=\"styles.css\">\n</head>","output":"A complete, SEO-optimized head section (not visible on page)","explanation":"<p>This head section covers all bases: encoding, mobile, SEO, social sharing, favicon, and CSS.</p>"},
            {"title":"Viewport for Responsiveness","code":"<!-- WITHOUT viewport: mobile shows desktop zoomed out -->\n<!-- WITH viewport: mobile shows responsive layout -->\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n\n<!-- Prevent user zoom (accessibility concern) -->\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0\">\n\n<!-- Better: allow zoom -->\n<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0\">","output":"Controls how the page appears on mobile devices","explanation":"<p>Without viewport meta, mobile browsers render at desktop width (~980px) and zoom out. This tag is REQUIRED for responsive design.</p>"},
            {"title":"Social Media Cards","code":"<!-- Twitter Card -->\n<meta name=\"twitter:card\" content=\"summary_large_image\">\n<meta name=\"twitter:title\" content=\"HTML Tutorial\">\n<meta name=\"twitter:description\" content=\"Learn HTML from scratch\">\n<meta name=\"twitter:image\" content=\"https://example.com/preview.jpg\">\n\n<!-- Open Graph (Facebook, LinkedIn, etc) -->\n<meta property=\"og:title\" content=\"HTML Tutorial\">\n<meta property=\"og:description\" content=\"Complete guide to HTML5\">\n<meta property=\"og:image\" content=\"https://example.com/preview.jpg\">\n<meta property=\"og:url\" content=\"https://example.com/html-tutorial\">","output":"Controls the preview card shown when sharing links on social media","explanation":"<p>Without these tags, social platforms generate a generic preview. With them, you control the title, description, and image.</p>"},
        ],quiz=[{"q":"The viewport meta tag is essential for:","options":["SEO ranking","Mobile responsiveness","JavaScript loading","CSS animations"],"answer":"Mobile responsiveness"},{"q":"og: tags are used by:","options":["Search engines only","Social media platforms","Email clients","Browsers"],"answer":"Social media platforms"}]),
    "html_iframe":make_topic(intro="<p>The <code>&lt;iframe&gt;</code> element embeds another HTML page within the current page. Common uses: embedding YouTube videos, Google Maps, CodePen demos, third-party widgets, and payment forms. Security is critical — use <code>sandbox</code> and CSP headers to restrict embedded content behavior.</p>",subtopics=[{"title":"iframe Usage","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>&lt;iframe \n    src=\"https://example.com\" \n    width=\"600\" height=\"400\"\n    title=\"Embedded page\"\n    sandbox=\"allow-scripts allow-same-origin\"\n    loading=\"lazy\"\n&gt;&lt;/iframe&gt;</pre>"}],key_concepts="<ul><li><code>sandbox</code> restricts iframe capabilities: no forms, scripts, or popups unless explicitly allowed.</li><li><code>title</code> is required for accessibility (screen readers).</li><li><code>loading=\"lazy\"</code> defers iframe loading for performance.</li><li>Use <code>X-Frame-Options</code> header to prevent YOUR site from being embedded by others (clickjacking).</li></ul>",examples=[
            {"title":"Google Maps Embed","code":"<iframe \n    src=\"https://maps.google.com/maps?q=eiffel+tower&output=embed\" \n    width=\"600\" \n    height=\"450\" \n    style=\"border:0;\" \n    allowfullscreen \n    loading=\"lazy\"\n    title=\"Eiffel Tower Map\">\n</iframe>","output":"An embedded Google Maps showing the Eiffel Tower","explanation":"<p>Google Maps provides embed URLs. <code>allowfullscreen</code> lets users expand the map.</p>"},
            {"title":"Responsive iframe","code":"<div style=\"position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;\">\n    <iframe \n        src=\"https://www.youtube.com/embed/dQw4w9WgXcQ\" \n        style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%;\" \n        frameborder=\"0\" \n        allowfullscreen\n        title=\"Video\">\n    </iframe>\n</div>","output":"A responsive video embed that maintains 16:9 aspect ratio","explanation":"<p>The padding-bottom trick (56.25% = 9/16) creates a responsive container that maintains aspect ratio.</p>"},
            {"title":"Sandboxed iframe","code":"<iframe \n    src=\"untrusted-content.html\"\n    sandbox=\"allow-scripts\"\n    width=\"400\" \n    height=\"300\"\n    title=\"Sandboxed content\">\n</iframe>\n\n<!-- sandbox restrictions:\n  - No form submission\n  - No popups\n  - No top-level navigation\n  - Scripts allowed (explicitly)\n-->","output":"A restricted iframe that can run scripts but not submit forms or navigate","explanation":"<p><code>sandbox</code> locks down the iframe — add permissions explicitly: <code>allow-scripts</code>, <code>allow-forms</code>, <code>allow-popups</code>.</p>"},
        ],quiz=[{"q":"iframe sandbox attribute:","options":["Styles the frame","Restricts embedded content capabilities","Adds scrollbars","Sets the source"],"answer":"Restricts embedded content capabilities"},{"q":"56.25% padding-bottom creates which aspect ratio?","options":["4:3","1:1","16:9","21:9"],"answer":"16:9"}]),
    "html_canvas":make_topic(intro="<p>The <code>&lt;canvas&gt;</code> element provides a drawing surface for JavaScript — 2D graphics, charts, games, image manipulation, and animations. Canvas is pixel-based (raster) unlike SVG (vector). You draw using the Canvas 2D API: rectangles, paths, arcs, text, images, and gradients.</p>",subtopics=[{"title":"Canvas API","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>&lt;canvas id=\"myCanvas\" width=\"400\" height=\"300\"&gt;&lt;/canvas&gt;\n&lt;script&gt;\nconst ctx = document.getElementById('myCanvas').getContext('2d');\nctx.fillStyle = '#3b82f6';\nctx.fillRect(10, 10, 150, 100);\nctx.font = '20px Arial';\nctx.fillText('Hello Canvas!', 10, 150);\n&lt;/script&gt;</pre>"}],key_concepts="<ul><li>Canvas is drawn with JavaScript — the <code>&lt;canvas&gt;</code> tag is just a container.</li><li><code>getContext('2d')</code> provides the 2D drawing API.</li><li>Canvas is pixel-based — scales poorly. Use SVG for scalable graphics.</li><li>Common uses: charts (Chart.js), games, image filters, signatures.</li></ul>",examples=[
            {"title":"Drawing Shapes","code":"<canvas id=\"shapes\" width=\"400\" height=\"200\"></canvas>\n<script>\nconst ctx = document.getElementById('shapes').getContext('2d');\n\n// Rectangle\nctx.fillStyle = '#3b82f6';\nctx.fillRect(10, 10, 120, 80);\n\n// Circle\nctx.beginPath();\nctx.arc(250, 50, 40, 0, Math.PI * 2);\nctx.fillStyle = '#ef4444';\nctx.fill();\n\n// Triangle\nctx.beginPath();\nctx.moveTo(350, 10);\nctx.lineTo(310, 90);\nctx.lineTo(390, 90);\nctx.closePath();\nctx.fillStyle = '#22c55e';\nctx.fill();\n\n// Text\nctx.fillStyle = '#000';\nctx.font = '16px Arial';\nctx.fillText('Rectangle', 20, 120);\nctx.fillText('Circle', 225, 120);\nctx.fillText('Triangle', 325, 120);\n</script>","output":"A blue rectangle, red circle, and green triangle with labels","explanation":"<p>Canvas draws pixel-by-pixel: <code>fillRect</code> for rectangles, <code>arc</code> for circles, <code>moveTo/lineTo</code> for paths.</p>"},
            {"title":"Gradient & Styling","code":"<canvas id=\"gradient\" width=\"400\" height=\"150\"></canvas>\n<script>\nconst ctx = document.getElementById('gradient').getContext('2d');\n\n// Linear gradient\nconst grad = ctx.createLinearGradient(0, 0, 400, 0);\ngrad.addColorStop(0, '#667eea');\ngrad.addColorStop(1, '#764ba2');\n\nctx.fillStyle = grad;\nctx.fillRect(0, 0, 400, 150);\n\nctx.fillStyle = 'white';\nctx.font = 'bold 30px Arial';\nctx.textAlign = 'center';\nctx.fillText('Canvas Gradient!', 200, 85);\n</script>","output":"A gradient banner with centered white text","explanation":"<p><code>createLinearGradient</code> defines start/end points; <code>addColorStop</code> adds colors at positions (0-1).</p>"},
            {"title":"Simple Animation","code":"<canvas id=\"anim\" width=\"400\" height=\"200\"></canvas>\n<script>\nconst canvas = document.getElementById('anim');\nconst ctx = canvas.getContext('2d');\nlet x = 0;\n\nfunction animate() {\n    ctx.clearRect(0, 0, 400, 200);\n    \n    ctx.beginPath();\n    ctx.arc(x, 100, 20, 0, Math.PI * 2);\n    ctx.fillStyle = '#3b82f6';\n    ctx.fill();\n    \n    x = (x + 2) % 420;\n    requestAnimationFrame(animate);\n}\nanimate();\n</script>","output":"A blue ball moving across the canvas continuously","explanation":"<p><code>requestAnimationFrame</code> calls the function at 60fps. <code>clearRect</code> erases the previous frame. This is the basis of canvas games.</p>"},
        ],quiz=[{"q":"Canvas graphics are:","options":["Vector-based (scalable)","Pixel-based (raster)","SVG-based","CSS-based"],"answer":"Pixel-based (raster)"},{"q":"getContext('2d') returns:","options":["The canvas element","The 2D drawing API","A WebGL context","An image"],"answer":"The 2D drawing API"}]),
    "html_api":make_topic(intro="<p>HTML5 introduced powerful <strong>Web APIs</strong> that give JavaScript access to browser capabilities: <strong>Local Storage</strong> (persistent data), <strong>Geolocation</strong> (user's location), <strong>Drag & Drop</strong>, <strong>Web Workers</strong> (background threads), <strong>Notifications API</strong>, and more. These APIs enable rich web applications that rival native desktop/mobile apps.</p>",subtopics=[{"title":"Storage APIs","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>// localStorage — persists until cleared\nlocalStorage.setItem('theme', 'dark');\nconst theme = localStorage.getItem('theme');\nlocalStorage.removeItem('theme');\n\n// sessionStorage — cleared when tab closes\nsessionStorage.setItem('token', 'abc123');</pre>"}],key_concepts="<ul><li><code>localStorage</code>: 5-10MB, persists forever (until cleared). Key-value strings only.</li><li><code>sessionStorage</code>: same API but data cleared when tab closes.</li><li>Geolocation requires user permission: <code>navigator.geolocation.getCurrentPosition()</code>.</li><li>Web Workers run JavaScript in background threads — no UI blocking.</li></ul>",examples=[
            {"title":"Local Storage CRUD","code":"<script>\n// Save\nlocalStorage.setItem('user', JSON.stringify({name: 'Alice', age: 25}));\n\n// Read\nconst user = JSON.parse(localStorage.getItem('user'));\nconsole.log(`Name: ${user.name}, Age: ${user.age}`);\n\n// Update\nuser.age = 26;\nlocalStorage.setItem('user', JSON.stringify(user));\n\n// Delete\nlocalStorage.removeItem('user');\n\n// Clear all\n// localStorage.clear();\n\nconsole.log(`Items in storage: ${localStorage.length}`);\n</script>","output":"Name: Alice, Age: 25\nItems in storage: 0","explanation":"<p>localStorage stores strings only — use <code>JSON.stringify/parse</code> for objects. Data persists across page reloads and browser restarts.</p>"},
            {"title":"Geolocation API","code":"<button onclick=\"getLocation()\">Get My Location</button>\n<p id=\"location\"></p>\n\n<script>\nfunction getLocation() {\n    if (navigator.geolocation) {\n        navigator.geolocation.getCurrentPosition(\n            (pos) => {\n                document.getElementById('location').textContent = \n                    `Lat: ${pos.coords.latitude}, Lng: ${pos.coords.longitude}`;\n            },\n            (err) => {\n                document.getElementById('location').textContent = \n                    `Error: ${err.message}`;\n            }\n        );\n    } else {\n        alert('Geolocation not supported');\n    }\n}\n</script>","output":"Button that shows user's GPS coordinates when clicked (after permission)","explanation":"<p>Geolocation requires explicit user consent. Always handle the error callback — user may deny permission.</p>"},
            {"title":"Fetch API (AJAX)","code":"<script>\n// Modern way to make HTTP requests\nasync function fetchUser() {\n    try {\n        const response = await fetch('https://jsonplaceholder.typicode.com/users/1');\n        const user = await response.json();\n        console.log(`Name: ${user.name}`);\n        console.log(`Email: ${user.email}`);\n        console.log(`City: ${user.address.city}`);\n    } catch (error) {\n        console.error('Failed:', error);\n    }\n}\nfetchUser();\n</script>","output":"Name: Leanne Graham\nEmail: Sincere@april.biz\nCity: Gwenborough","explanation":"<p>Fetch API replaces XMLHttpRequest. <code>async/await</code> makes async code readable. Always wrap in try-catch.</p>"},
        ],quiz=[{"q":"localStorage data persists:","options":["Until page refresh","Until tab closes","Until browser closes","Until manually cleared"],"answer":"Until manually cleared"},{"q":"Geolocation requires:","options":["Nothing","User permission","HTTPS only","GPS hardware"],"answer":"User permission"}]),
    "html_a11y":make_topic(intro="<p><strong>Web accessibility (a11y)</strong> ensures websites are usable by everyone, including people with visual, motor, hearing, or cognitive disabilities. Accessibility is required by law in many countries (ADA, WCAG). Key practices: semantic HTML, alt text, keyboard navigation, ARIA labels, color contrast, and focus management.</p>",subtopics=[{"title":"ARIA Attributes","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>&lt;button aria-label=\"Close dialog\" onclick=\"close()\"&gt;X&lt;/button&gt;\n&lt;div role=\"alert\"&gt;Form submitted successfully!&lt;/div&gt;\n&lt;nav aria-label=\"Main navigation\"&gt;...&lt;/nav&gt;\n&lt;img src=\"chart.png\" alt=\"Sales increased 25% in Q4\"&gt;</pre>"}],key_concepts="<ul><li>Use semantic HTML first — ARIA is a supplement, not replacement.</li><li>All images need <code>alt</code> text. Decorative images: <code>alt=\"\"</code>.</li><li>Ensure 4.5:1 color contrast ratio for text (WCAG AA).</li><li>All interactive elements must be keyboard-accessible (<code>Tab</code>, <code>Enter</code>, <code>Escape</code>).</li><li>Use <code>aria-live=\"polite\"</code> for dynamic content updates.</li></ul>",examples=[
            {"title":"Accessible Form","code":"<form>\n    <div>\n        <label for=\"email\">Email Address <span aria-hidden=\"true\">*</span></label>\n        <input type=\"email\" id=\"email\" name=\"email\" required \n               aria-describedby=\"email-help\">\n        <small id=\"email-help\">We'll never share your email.</small>\n    </div>\n    \n    <div>\n        <label for=\"password\">Password</label>\n        <input type=\"password\" id=\"password\" name=\"password\" required\n               aria-describedby=\"pass-rules\">\n        <small id=\"pass-rules\">Minimum 8 characters with a number.</small>\n    </div>\n    \n    <button type=\"submit\">Sign Up</button>\n</form>","output":"An accessible form with labels, help text, and ARIA descriptions","explanation":"<p><code>aria-describedby</code> links help text to inputs — screen readers read it when the input is focused.</p>"},
            {"title":"Skip Navigation Link","code":"<body>\n    <!-- Skip link (visible on focus) -->\n    <a href=\"#main-content\" class=\"skip-link\" \n       style=\"position: absolute; left: -9999px;\">\n        Skip to main content\n    </a>\n    \n    <header>\n        <nav><!-- 20 navigation links --></nav>\n    </header>\n    \n    <main id=\"main-content\">\n        <h1>Page Content</h1>\n        <p>Keyboard users can skip directly here.</p>\n    </main>\n</body>","output":"A hidden link that appears when Tab is pressed, allowing keyboard users to skip navigation","explanation":"<p>Skip links let keyboard users jump past repetitive navigation — essential for accessibility compliance.</p>"},
            {"title":"ARIA Live Region","code":"<div aria-live=\"polite\" id=\"status\"></div>\n<button onclick=\"document.getElementById('status').textContent = 'Item added to cart!'\">\n    Add to Cart\n</button>\n\n<!-- For alerts/errors -->\n<div role=\"alert\" id=\"error\" style=\"display: none; color: red;\">\n    Please fix the errors below.\n</div>","output":"Dynamic status messages announced by screen readers","explanation":"<p><code>aria-live=\"polite\"</code> announces updates when the user is idle. <code>role=\"alert\"</code> announces immediately (for errors).</p>"},
        ],quiz=[{"q":"WCAG AA requires what color contrast ratio?","options":["2:1","3:1","4.5:1","7:1"],"answer":"4.5:1"},{"q":"Decorative images should have:","options":["No alt attribute","alt=\"decorative\"","alt=\"\"","alt=\"image\""],"answer":"alt=\"\""}]),
    "html_seo":make_topic(intro="<p><strong>SEO (Search Engine Optimization)</strong> through HTML ensures your pages rank well in Google and other search engines. Key HTML SEO factors: title tags, meta descriptions, heading hierarchy, semantic markup, structured data (Schema.org), image alt text, canonical URLs, and page speed optimization.</p>",subtopics=[{"title":"On-Page SEO","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>&lt;title&gt;Best Coffee Shops in NYC | MyBlog&lt;/title&gt;\n&lt;meta name=\"description\" content=\"Discover the top 10 coffee shops in New York City with reviews, photos, and addresses.\"&gt;\n&lt;link rel=\"canonical\" href=\"https://myblog.com/nyc-coffee\"&gt;\n\n&lt;h1&gt;Top 10 Coffee Shops in New York City&lt;/h1&gt;\n&lt;!-- One h1 per page, includes main keyword --&gt;</pre>"}],key_concepts="<ul><li><code>&lt;title&gt;</code>: 50-60 chars, unique per page, includes primary keyword.</li><li><code>meta description</code>: 150-160 chars, compelling summary shown in search results.</li><li>One <code>&lt;h1&gt;</code> per page. Heading hierarchy: h1 → h2 → h3 (never skip levels).</li><li><code>canonical</code> URL prevents duplicate content — tells search engines the 'official' URL.</li></ul>",examples=[
            {"title":"SEO-Optimized Head","code":"<head>\n    <title>Learn Python Programming - Free Tutorial | CodeAcademy</title>\n    <meta name=\"description\" content=\"Free Python tutorial for beginners. Learn variables, loops, functions, and OOP with interactive examples. Start coding in 5 minutes.\">\n    <meta name=\"robots\" content=\"index, follow\">\n    <link rel=\"canonical\" href=\"https://codeacademy.com/python\">\n    \n    <!-- Structured Data (Schema.org) -->\n    <script type=\"application/ld+json\">\n    {\n        \"@context\": \"https://schema.org\",\n        \"@type\": \"Course\",\n        \"name\": \"Learn Python Programming\",\n        \"description\": \"Free Python tutorial for beginners\",\n        \"provider\": { \"@type\": \"Organization\", \"name\": \"CodeAcademy\" }\n    }\n    </script>\n</head>","output":"An invisible but powerful SEO setup in the page head","explanation":"<p>Schema.org structured data helps Google show rich results — course ratings, breadcrumbs, FAQs, etc.</p>"},
            {"title":"Semantic Heading Structure","code":"<article>\n    <h1>Complete Guide to HTML5</h1>\n    \n    <h2>1. Getting Started</h2>\n    <h3>1.1 What is HTML?</h3>\n    <p>HTML is a markup language...</p>\n    <h3>1.2 Setting Up</h3>\n    <p>You need a text editor...</p>\n    \n    <h2>2. HTML Elements</h2>\n    <h3>2.1 Text Elements</h3>\n    <p>Headings, paragraphs...</p>\n    <h3>2.2 Media Elements</h3>\n    <p>Images, video, audio...</p>\n</article>","output":"A properly structured document outline for search engines","explanation":"<p>Search engines use heading hierarchy to understand page structure. Never skip levels (h1 → h3 is wrong).</p>"},
            {"title":"Image SEO","code":"<!-- Good: descriptive alt text -->\n<img src=\"python-loops.png\" \n     alt=\"Python for loop syntax showing iteration over a list\"\n     width=\"600\" height=\"400\"\n     loading=\"lazy\">\n\n<!-- Bad: unhelpful alt text -->\n<img src=\"img123.png\" alt=\"image\">\n<img src=\"photo.jpg\" alt=\"photo of thing\">\n\n<!-- Decorative: empty alt -->\n<img src=\"divider.svg\" alt=\"\" role=\"presentation\">","output":"Images with proper alt text for search engines and screen readers","explanation":"<p>Descriptive alt text helps Google Image search ranking AND accessibility. Decorative images get empty <code>alt=\"\"</code>.</p>"},
        ],quiz=[{"q":"How many <h1> tags should a page have?","options":["As many as needed","Exactly one","Zero","Two (header + content)"],"answer":"Exactly one"},{"q":"Meta description length should be:","options":["50-60 characters","100 characters max","150-160 characters","No limit"],"answer":"150-160 characters"}]),
    "html_responsive":make_topic(intro="<p><strong>Responsive web design</strong> ensures pages look great on all screen sizes — phones, tablets, laptops, and desktops. The foundation: <code>viewport</code> meta tag, CSS media queries, flexible images (<code>max-width: 100%</code>), CSS Grid/Flexbox, and the <code>&lt;picture&gt;</code> element for art-directed images.</p>",subtopics=[{"title":"Responsive Techniques","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>&lt;!-- Viewport meta (required) --&gt;\n&lt;meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"&gt;\n\n&lt;!-- Responsive image --&gt;\n&lt;img src=\"photo.jpg\" alt=\"...\" style=\"max-width: 100%; height: auto;\"&gt;\n\n&lt;!-- Media queries in CSS --&gt;\n@media (max-width: 768px) {\n    .sidebar { display: none; }\n    .content { width: 100%; }\n}</pre>"}],key_concepts="<ul><li>Mobile-first: design for mobile, then add complexity for larger screens.</li><li><code>max-width: 100%</code> on images prevents overflow.</li><li>Use relative units: <code>%</code>, <code>rem</code>, <code>em</code>, <code>vw</code>/<code>vh</code> instead of fixed <code>px</code>.</li><li>Common breakpoints: 576px (phone), 768px (tablet), 992px (laptop), 1200px (desktop).</li></ul>",examples=[
            {"title":"Responsive Layout","code":"<div style=\"display: flex; flex-wrap: wrap; gap: 20px;\">\n    <div style=\"flex: 1 1 250px; background: #e2e8f0; padding: 20px; border-radius: 8px;\">\n        <h3>Card 1</h3>\n        <p>This card will stack on small screens.</p>\n    </div>\n    <div style=\"flex: 1 1 250px; background: #e2e8f0; padding: 20px; border-radius: 8px;\">\n        <h3>Card 2</h3>\n        <p>Flex-wrap handles the responsive behavior.</p>\n    </div>\n    <div style=\"flex: 1 1 250px; background: #e2e8f0; padding: 20px; border-radius: 8px;\">\n        <h3>Card 3</h3>\n        <p>No media queries needed for this!</p>\n    </div>\n</div>","output":"Three cards in a row on desktop, stacking vertically on mobile","explanation":"<p><code>flex: 1 1 250px</code> means: grow, shrink, minimum 250px. <code>flex-wrap: wrap</code> wraps cards when they don't fit.</p>"},
            {"title":"Responsive Navigation","code":"<style>\n.nav { display: flex; background: #1e293b; padding: 10px; }\n.nav a { color: white; padding: 10px 15px; text-decoration: none; }\n.nav a:hover { background: #334155; border-radius: 5px; }\n\n@media (max-width: 600px) {\n    .nav { flex-direction: column; }\n    .nav a { padding: 12px; border-bottom: 1px solid #334155; }\n}\n</style>\n\n<nav class=\"nav\">\n    <a href=\"/\">Home</a>\n    <a href=\"/about\">About</a>\n    <a href=\"/services\">Services</a>\n    <a href=\"/contact\">Contact</a>\n</nav>","output":"Horizontal nav on desktop, vertical stack on mobile (< 600px)","explanation":"<p>Media query at 600px changes flex direction from row to column — a common responsive nav pattern.</p>"},
            {"title":"Picture Element (Art Direction)","code":"<picture>\n    <source media=\"(min-width: 1024px)\" srcset=\"hero-wide.jpg\">\n    <source media=\"(min-width: 640px)\" srcset=\"hero-medium.jpg\">\n    <img src=\"hero-mobile.jpg\" alt=\"Hero image\" style=\"width: 100%; height: auto;\">\n</picture>\n\n<p style=\"font-size: clamp(1rem, 3vw, 2rem);\">\n    This text scales responsively using clamp()!\n</p>","output":"Different images served for desktop, tablet, and mobile","explanation":"<p><code>&lt;picture&gt;</code> serves different images per breakpoint — not just resizing but different crops (art direction).</p>"},
        ],quiz=[{"q":"Mobile-first design means:","options":["Designing for mobile only","Designing for mobile first, then enhancing for desktop","Ignoring desktop users","Using only mobile frameworks"],"answer":"Designing for mobile first, then enhancing for desktop"},{"q":"Which CSS unit is relative to viewport width?","options":["px","em","rem","vw"],"answer":"vw"}]),
    "html_practices":make_topic(intro="<p><strong>HTML best practices</strong> ensure clean, maintainable, performant, and accessible web pages. Following standards improves SEO, cross-browser compatibility, loading speed, and developer collaboration. These practices are what separate amateur HTML from professional-grade code.</p>",subtopics=[{"title":"Code Quality","content":"<ul><li>Use semantic HTML elements over generic divs</li><li>Validate HTML with W3C validator</li><li>Use consistent indentation (2 or 4 spaces)</li><li>Close all tags properly</li><li>Use lowercase for tags and attributes</li><li>Quote all attribute values</li></ul>"}],key_concepts="<ul><li>Performance: minimize HTTP requests, lazy-load images, defer JavaScript.</li><li>Accessibility: alt text, labels, keyboard navigation, ARIA when needed.</li><li>SEO: unique titles, meta descriptions, h1, structured data.</li><li>Security: CSP headers, sanitize user input, use HTTPS.</li></ul>",examples=[
            {"title":"Performance Best Practices","code":"<head>\n    <!-- CSS in head (render-blocking is OK for CSS) -->\n    <link rel=\"stylesheet\" href=\"styles.css\">\n    \n    <!-- Preload critical resources -->\n    <link rel=\"preload\" href=\"hero.jpg\" as=\"image\">\n    <link rel=\"preload\" href=\"font.woff2\" as=\"font\" crossorigin>\n    \n    <!-- JS at end of body or with defer -->\n</head>\n<body>\n    <!-- Lazy-load below-the-fold images -->\n    <img src=\"hero.jpg\" alt=\"Hero\" width=\"1200\" height=\"600\">\n    <img src=\"photo.jpg\" alt=\"Photo\" loading=\"lazy\" width=\"400\" height=\"300\">\n    \n    <!-- defer: loads in parallel, executes after HTML is parsed -->\n    <script src=\"app.js\" defer></script>\n</body>","output":"Optimized page loading order","explanation":"<p><code>defer</code> loads JS in parallel but executes after HTML parsing. <code>preload</code> prioritizes critical assets. <code>loading=\"lazy\"</code> defers off-screen images.</p>"},
            {"title":"Clean HTML Template","code":"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <meta name=\"description\" content=\"Concise page description\">\n    <title>Page Title | Site Name</title>\n    <link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n    <a href=\"#main\" class=\"skip-link\">Skip to content</a>\n    \n    <header>\n        <nav aria-label=\"Main\">\n            <a href=\"/\">Home</a>\n            <a href=\"/about\">About</a>\n        </nav>\n    </header>\n    \n    <main id=\"main\">\n        <h1>Page Heading</h1>\n        <p>Content here...</p>\n    </main>\n    \n    <footer>\n        <p>&copy; 2024 Company. All rights reserved.</p>\n    </footer>\n    \n    <script src=\"app.js\" defer></script>\n</body>\n</html>","output":"A complete, professional HTML template following all best practices","explanation":"<p>This template includes: skip link, semantic elements, accessibility, SEO meta, deferred JS, and clean structure.</p>"},
            {"title":"Common Mistakes to Avoid","code":"<!-- WRONG: Using tables for layout -->\n<table><tr><td>Sidebar</td><td>Content</td></tr></table>\n\n<!-- RIGHT: Use CSS Flexbox/Grid -->\n<div style=\"display: flex;\">\n    <aside>Sidebar</aside>\n    <main>Content</main>\n</div>\n\n<!-- WRONG: Inline styles everywhere -->\n<p style=\"color: red; font-size: 20px;\">Text</p>\n\n<!-- RIGHT: Use CSS classes -->\n<p class=\"error-message\">Text</p>\n\n<!-- WRONG: Missing alt on images -->\n<img src=\"photo.jpg\">\n\n<!-- RIGHT: Descriptive alt text -->\n<img src=\"photo.jpg\" alt=\"Team meeting in conference room\">","output":"Side-by-side comparison of bad vs good HTML practices","explanation":"<p>Tables for layout, inline styles, and missing alt text are the three most common HTML mistakes.</p>"},
        ],quiz=[{"q":"Where should JavaScript files be loaded?","options":["In <head> without defer","At the end of <body> or with defer","Before CSS","In a separate iframe"],"answer":"At the end of <body> or with defer"},{"q":"Which is preferred for page layout?","options":["HTML tables","CSS Flexbox/Grid","Nested divs with float","Frames"],"answer":"CSS Flexbox/Grid"}]),
    "html_interview":make_topic(intro="<p>HTML interview questions test fundamental web knowledge: semantic elements, accessibility, SEO, forms, media, APIs, performance optimization, and HTML5 features. Even senior developers are tested on HTML basics because they're foundational for all web technologies.</p>",subtopics=[{"title":"Common HTML Interview Questions","content":"<ul><li><strong>Q: What is semantic HTML?</strong> A: Using elements that describe meaning (<code>&lt;article&gt;</code>, <code>&lt;nav&gt;</code>) instead of generic <code>&lt;div&gt;</code>/<code>&lt;span&gt;</code>.</li><li><strong>Q: Block vs inline elements?</strong> A: Block takes full width, starts new line (div, p, h1). Inline flows with text (span, a, strong).</li><li><strong>Q: What's the difference between &lt;div&gt; and &lt;section&gt;?</strong> A: <code>&lt;section&gt;</code> has semantic meaning (thematic grouping); <code>&lt;div&gt;</code> is a generic container with no semantic value.</li><li><strong>Q: What does DOCTYPE do?</strong> A: Tells the browser to use standards mode (HTML5). Without it, browsers use quirks mode.</li></ul>"}],key_concepts="<ul><li>Know the difference between <code>&lt;b&gt;</code>/<code>&lt;i&gt;</code> (visual) and <code>&lt;strong&gt;</code>/<code>&lt;em&gt;</code> (semantic).</li><li>Know HTML5 APIs: localStorage, geolocation, canvas, service workers, web sockets.</li><li>Know accessibility: ARIA roles, alt text, keyboard navigation, focus management.</li><li>Know form input types: email, url, tel, date, color, range, file.</li></ul>",examples=[
            {"title":"Block vs Inline Demo","code":"<!-- Block: takes full width -->\n<div style=\"background: #e2e8f0; padding: 10px; margin: 5px;\">\n    This div takes full width\n</div>\n<p style=\"background: #e2e8f0; padding: 10px; margin: 5px;\">\n    This paragraph also takes full width\n</p>\n\n<!-- Inline: flows with text -->\n<p>\n    This has <span style=\"background: #fef3c7;\">inline span</span> and \n    <a href=\"#\" style=\"background: #dbeafe;\">inline link</a> and \n    <strong style=\"background: #dcfce7;\">inline strong</strong> in the flow.\n</p>","output":"Block elements stack vertically; inline elements flow within text","explanation":"<p>This is one of the most common HTML interview questions. Block elements create new lines; inline elements don't.</p>"},
            {"title":"Difference Between id and class","code":"<!-- id: unique, one per page -->\n<h1 id=\"page-title\">Welcome</h1>\n\n<!-- class: reusable, multiple per page -->\n<p class=\"highlight\">First highlighted paragraph</p>\n<p class=\"highlight\">Second highlighted paragraph</p>\n\n<style>\n    #page-title { color: navy; }        /* id selector: # */\n    .highlight { background: yellow; }  /* class selector: . */\n</style>\n\n<!-- CSS specificity: id > class > element -->\n<!-- id can also be used as anchor: <a href=\"#page-title\"> -->","output":"One unique id element and two elements sharing a class","explanation":"<p><code>id</code> is unique (one element), used for anchors and JS. <code>class</code> is reusable (many elements), used for CSS styling.</p>"},
            {"title":"localStorage vs sessionStorage vs Cookies","code":"<script>\n// localStorage: persists forever, ~5MB\nlocalStorage.setItem('pref', 'dark');\n\n// sessionStorage: cleared on tab close, ~5MB\nsessionStorage.setItem('token', 'abc');\n\n// Cookies: sent to server with every request, 4KB max\ndocument.cookie = 'theme=dark; max-age=86400; path=/';\n\nconsole.log('localStorage: persists until cleared');\nconsole.log('sessionStorage: cleared on tab close');\nconsole.log('Cookies: sent to server, small size');\n</script>","output":"Storage comparison: persistence, size, and server behavior","explanation":"<p>A classic interview question. localStorage for client-only persistence, sessionStorage for temporary data, cookies for server communication.</p>"},
        ],quiz=[{"q":"What is the purpose of DOCTYPE?","options":["Define document type for XML","Tell browser to use standards mode","Import external styles","Set character encoding"],"answer":"Tell browser to use standards mode"},{"q":"id vs class: which must be unique?","options":["class","id","Both","Neither"],"answer":"id"}]),
}

def load_data():
    with open(FILEPATH, 'r', encoding='utf-8') as f:
        content = f.read()
    prefix = 'window.tracksData = '
    idx = content.find(prefix)
    raw_json = content[idx + len(prefix):]
    suffix = ''
    if raw_json.strip().endswith(';'):
        raw_json = raw_json.strip()[:-1]
        suffix = ';'
    return content[:idx + len(prefix)], json.loads(raw_json), suffix

def save_data(pc, data, suffix):
    with open(FILEPATH, 'w', encoding='utf-8') as f:
        f.write(pc)
        f.write(json.dumps(data, ensure_ascii=False, separators=(',', ':')))
        f.write(suffix)

def apply_fixes(data, lang_key, fixes):
    fixed = 0
    for tk, nc in fixes.items():
        if tk in data.get(lang_key, {}).get('content', {}):
            existing = data[lang_key]['content'][tk]
            nc['title'] = existing.get('title', tk)
            nc['phase'] = existing.get('phase', 1)
            data[lang_key]['content'][tk] = nc
            fixed += 1
            print('  OK %s/%s' % (lang_key, tk))
        else:
            print('  MISS %s/%s' % (lang_key, tk))
    return fixed

if __name__ == '__main__':
    print('Loading tracks_data.js...')
    pc, data, suffix = load_data()
    total = 0
    print('\n--- Fixing HTML ---')
    total += apply_fixes(data, 'html', HTML_FIXES)
    print('\nSaving %d fixes...' % total)
    save_data(pc, data, suffix)
    print('Done!')
