"""
Batch: PHP (all 18 topics) — full textbook content with 3+ examples each
"""
import json, os
FILEPATH = os.path.join(os.path.dirname(__file__), '..', 'core', 'static', 'tracks_data.js')

def make_topic(intro, subtopics, key_concepts, examples, quiz, hands_on=None, problems=None):
    s = {"introduction": intro, "subtopics": subtopics, "key_concepts": key_concepts, "examples": examples}
    return {"structured": s, "concept_quiz": quiz, "hands_on": hands_on or {"title":"Try it!","description":"Practice the concept above.","hint":"Use the examples as a guide.","code":""}, "problem_solving": problems or []}

PHP_FIXES = {
    "php_basics": make_topic(
        intro="<p><strong>PHP</strong> (PHP: Hypertext Preprocessor) is a server-side scripting language created by Rasmus Lerdorf in 1994. It powers over 75% of websites with server-side programming, including WordPress, Facebook (originally), Wikipedia, and Laravel-based apps. PHP code executes on the server, generating HTML sent to the browser. It is embedded directly in HTML with <code>&lt;?php ?&gt;</code> tags, making it uniquely suited for web development.</p>",
        subtopics=[
            {"title":"PHP Basics","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>&lt;?php\necho \"Hello, World!\\n\";\n$name = \"PHP\";\necho \"Welcome to $name!\\n\";  // variable interpolation\n?&gt;</pre>"},
            {"title":"Variables & Data Types","content":"<p>PHP variables start with <code>$</code>. Types are dynamic: <code>int</code>, <code>float</code>, <code>string</code>, <code>bool</code>, <code>array</code>, <code>null</code>. Use <code>gettype()</code> to check types.</p>"},
            {"title":"PHP in HTML","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>&lt;html&gt;\n&lt;body&gt;\n  &lt;h1&gt;&lt;?php echo \"Dynamic Title\"; ?&gt;&lt;/h1&gt;\n  &lt;p&gt;Today is &lt;?= date('Y-m-d') ?&gt;&lt;/p&gt;\n&lt;/body&gt;\n&lt;/html&gt;</pre>"},
        ],
        key_concepts="<ul><li>PHP is dynamically typed — variables don't declare types.</li><li>All variables start with <code>$</code>: <code>$name</code>, <code>$age</code>.</li><li><code>echo</code> outputs text. <code>&lt;?= expr ?&gt;</code> is shorthand for <code>&lt;?php echo expr; ?&gt;</code>.</li><li>Double-quoted strings interpolate variables: <code>\"Hello $name\"</code>. Single-quoted don't.</li><li>PHP files typically have <code>.php</code> extension and run via a web server (Apache, Nginx) or CLI.</li></ul>",
        examples=[
            {"title":"Hello World & Variables","code":"<?php\necho \"Hello, World!\\n\";\n\n$name = \"Alice\";\n$age = 25;\n$gpa = 3.85;\n$is_student = true;\n\necho \"Name: $name\\n\";\necho \"Age: $age\\n\";\necho \"GPA: $gpa\\n\";\necho \"Student: \" . ($is_student ? \"Yes\" : \"No\") . \"\\n\";\necho \"Type of age: \" . gettype($age) . \"\\n\";\n?>","output":"Hello, World!\nName: Alice\nAge: 25\nGPA: 3.85\nStudent: Yes\nType of age: integer","explanation":"<p>PHP variables are prefixed with <code>$</code>. Double-quoted strings interpolate variables directly.</p>"},
            {"title":"String Operations","code":"<?php\n$text = \"Hello, PHP World!\";\n\necho strlen($text) . \"\\n\";           // 17\necho strtoupper($text) . \"\\n\";       // HELLO, PHP WORLD!\necho str_replace(\"PHP\", \"Web\", $text) . \"\\n\"; // Hello, Web World!\necho substr($text, 7, 3) . \"\\n\";     // PHP\necho strpos($text, \"PHP\") . \"\\n\";    // 7\n\n// String concatenation uses .\n$greeting = \"Hello\" . \" \" . \"World\";\necho $greeting . \"\\n\";\n?>","output":"17\nHELLO, PHP WORLD!\nHello, Web World!\nPHP\n7\nHello World","explanation":"<p>PHP uses <code>.</code> for string concatenation (not <code>+</code>). Built-in string functions are extensive.</p>"},
            {"title":"Type Juggling","code":"<?php\n// PHP automatically converts types\n$x = \"10\";\n$y = 5;\necho $x + $y . \"\\n\";   // 15 (string \"10\" -> int 10)\n\n// Strict comparison\nvar_dump(\"10\" == 10);   // bool(true) — loose\nvar_dump(\"10\" === 10);  // bool(false) — strict (type must match)\n\n// Type casting\n$pi = 3.14;\n$int_pi = (int)$pi;\necho \"$pi -> $int_pi\\n\";  // 3.14 -> 3\n?>","output":"15\nbool(true)\nbool(false)\n3.14 -> 3","explanation":"<p><code>==</code> compares values with type juggling. <code>===</code> compares value AND type — always prefer <code>===</code>.</p>"},
        ],
        quiz=[
            {"q":"PHP variables start with:","options":["@","#","$","&"],"answer":"$"},
            {"q":"Which operator should you use for strict comparison?","options":["==","===","!=","<>"],"answer":"==="},
        ],
    ),
    "php_variables": make_topic(
        intro="<p>PHP variables are <strong>dynamically typed</strong> — no type declaration needed. A variable can hold an integer, then a string, then an array. PHP has 8 data types: <code>int</code>, <code>float</code>, <code>string</code>, <code>bool</code>, <code>array</code>, <code>object</code>, <code>null</code>, and <code>resource</code>. Variable scope in PHP is function-level: variables inside a function are local unless declared <code>global</code>. <strong>Superglobals</strong> (<code>$_GET</code>, <code>$_POST</code>, <code>$_SESSION</code>) are available everywhere.</p>",
        subtopics=[
            {"title":"Variable Scope","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>$global_var = \"I'm global\";\n\nfunction test() {\n    // $global_var not accessible here!\n    global $global_var; // now it is\n    $local_var = \"I'm local\"; // only exists in this function\n    echo $global_var;\n}\n\nstatic $count = 0; // persists between calls</pre>"},
            {"title":"Constants","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>define('PI', 3.14159);\nconst TAX_RATE = 0.08;  // modern syntax\n\necho PI . \"\\n\";       // 3.14159\necho TAX_RATE . \"\\n\"; // 0.08</pre>"},
        ],
        key_concepts="<ul><li>PHP variables are function-scoped, NOT block-scoped.</li><li><code>global</code> keyword or <code>$GLOBALS[]</code> array accesses global variables inside functions.</li><li><code>static</code> variables persist between function calls.</li><li>Superglobals: <code>$_GET</code>, <code>$_POST</code>, <code>$_SESSION</code>, <code>$_COOKIE</code>, <code>$_SERVER</code>, <code>$_FILES</code>.</li><li><code>isset($var)</code> checks if set and not null. <code>empty($var)</code> checks if falsy.</li></ul>",
        examples=[
            {"title":"Variable Types","code":"<?php\n$int_val = 42;\n$float_val = 3.14;\n$str_val = \"Hello\";\n$bool_val = true;\n$null_val = null;\n$arr_val = [1, 2, 3];\n\n$vars = [$int_val, $float_val, $str_val, $bool_val, $null_val];\nforeach ($vars as $v) {\n    echo gettype($v) . \": \" . var_export($v, true) . \"\\n\";\n}\n?>","output":"integer: 42\ndouble: 3.14\nstring: 'Hello'\nboolean: true\nNULL: NULL","explanation":"<p><code>gettype()</code> returns the type name. <code>var_export()</code> gives a parsable string representation.</p>"},
            {"title":"Scope & Static Variables","code":"<?php\nfunction counter() {\n    static $count = 0;\n    $count++;\n    echo \"Count: $count\\n\";\n}\n\ncounter(); // 1\ncounter(); // 2\ncounter(); // 3\n\n$x = 10;\nfunction showX() {\n    // $x not accessible without 'global'\n    echo \"x = \" . ($x ?? \"undefined\") . \"\\n\";\n}\nshowX();\n?>","output":"Count: 1\nCount: 2\nCount: 3\nx = undefined","explanation":"<p><code>static</code> preserves value between calls. Functions can't see global variables without <code>global</code> keyword.</p>"},
            {"title":"isset, empty, and Type Checking","code":"<?php\n$a = 0;\n$b = \"\";\n$c = null;\n$d = \"Hello\";\n\nforeach (['a'=>$a, 'b'=>$b, 'c'=>$c, 'd'=>$d] as $name => $val) {\n    $set = isset($val) ? 'Y' : 'N';\n    $emp = empty($val) ? 'Y' : 'N';\n    echo \"\\$$name: isset=$set, empty=$emp\\n\";\n}\n?>","output":"$a: isset=Y, empty=Y\n$b: isset=Y, empty=Y\n$c: isset=N, empty=Y\n$d: isset=Y, empty=N","explanation":"<p><code>isset()</code> returns false for null. <code>empty()</code> returns true for 0, '', null, false, [] — a common source of bugs.</p>"},
        ],
        quiz=[
            {"q":"PHP variable scope is:","options":["Block-level","Function-level","Global by default","Class-level"],"answer":"Function-level"},
            {"q":"Which superglobal handles form POST data?","options":["$_GET","$_POST","$_REQUEST","$_FORM"],"answer":"$_POST"},
        ],
    ),
    "php_operators": make_topic(
        intro="<p>PHP operators include arithmetic, comparison, logical, string (<code>.</code> concatenation), assignment, and the <strong>spaceship operator</strong> (<code>&lt;=&gt;</code>) for three-way comparison. PHP 7 added the <strong>null coalescing operator</strong> (<code>??</code>) and PHP 8 added the <strong>nullsafe operator</strong> (<code>?-></code>). Understanding loose (<code>==</code>) vs strict (<code>===</code>) comparison is critical to avoid PHP's infamous type juggling bugs.</p>",
        subtopics=[
            {"title":"Comparison Operators","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>// Loose comparison (type juggling)\n0 == false   // true  (both falsy)\n\"\" == false  // true  (both falsy)\n\"0\" == false // true  (!)\n\n// Strict comparison (type + value)\n0 === false  // false (int vs bool)\n\"\" === false // false (string vs bool)\n\n// Spaceship operator (PHP 7+)\n1 <=> 2  // -1 (less)\n2 <=> 2  //  0 (equal)\n3 <=> 2  //  1 (greater)</pre>"},
            {"title":"Null Coalescing","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>$name = $_GET['name'] ?? 'Guest';  // 'Guest' if not set\n$user = $obj?->getUser()?->name;   // nullsafe (PHP 8)</pre>"},
        ],
        key_concepts="<ul><li>Always use <code>===</code> and <code>!==</code> for comparison — <code>==</code> has surprising type juggling results.</li><li><code>??</code> null coalescing: returns left if not null, else right. Replaces <code>isset() ? ... : ...</code>.</li><li><code>??=</code> null coalescing assignment (PHP 7.4+).</li><li><code>&lt;=&gt;</code> spaceship: returns -1, 0, or 1 — perfect for <code>usort()</code> comparators.</li></ul>",
        examples=[
            {"title":"Strict vs Loose Comparison","code":"<?php\n$tests = [\n    ['0 == false', 0 == false],\n    ['0 === false', 0 === false],\n    ['\"\" == false', \"\" == false],\n    ['\"\" === false', \"\" === false],\n    ['null == false', null == false],\n    ['null === false', null === false],\n];\n\nforeach ($tests as [$expr, $result]) {\n    echo \"$expr: \" . ($result ? 'true' : 'false') . \"\\n\";\n}\n?>","output":"0 == false: true\n0 === false: false\n\"\" == false: true\n\"\" === false: false\nnull == false: true\nnull === false: false","explanation":"<p>Loose <code>==</code> treats 0, '', null, and false as equal! Always use <code>===</code> to avoid bugs.</p>"},
            {"title":"Null Coalescing Operator","code":"<?php\n$config = ['debug' => true, 'name' => 'MyApp'];\n\n$debug = $config['debug'] ?? false;\n$version = $config['version'] ?? '1.0.0';\n$name = $config['name'] ?? 'Default';\n\necho \"App: $name v$version (debug: \" . ($debug ? 'on' : 'off') . \")\\n\";\n\n// Chaining\n$val = $config['a'] ?? $config['b'] ?? 'fallback';\necho \"Value: $val\\n\";\n?>","output":"App: MyApp v1.0.0 (debug: on)\nValue: fallback","explanation":"<p><code>??</code> chains: tries each value left-to-right, returns the first non-null.</p>"},
            {"title":"Spaceship Operator for Sorting","code":"<?php\n$people = [\n    ['name' => 'Charlie', 'age' => 25],\n    ['name' => 'Alice', 'age' => 30],\n    ['name' => 'Bob', 'age' => 22],\n];\n\nusort($people, fn($a, $b) => $a['age'] <=> $b['age']);\n\nforeach ($people as $p) {\n    echo \"{$p['name']}: {$p['age']}\\n\";\n}\n?>","output":"Bob: 22\nCharlie: 25\nAlice: 30","explanation":"<p>The spaceship operator <code>&lt;=&gt;</code> returns -1/0/1, perfect for <code>usort()</code> comparators.</p>"},
        ],
        quiz=[
            {"q":"What does the ?? operator do?","options":["Ternary check","Returns left side if not null, else right","Strict comparison","Error suppression"],"answer":"Returns left side if not null, else right"},
            {"q":"0 == false in PHP is:","options":["true","false","Error","undefined"],"answer":"true"},
        ],
    ),
    "php_control": make_topic(
        intro="<p>PHP control flow includes <code>if</code>/<code>elseif</code>/<code>else</code>, <code>switch</code>, and PHP 8's <strong>match expression</strong> — a safer, more powerful alternative to switch that uses strict comparison and returns values. PHP also supports alternative syntax for embedding in HTML templates: <code>if(): ... endif;</code>.</p>",
        subtopics=[
            {"title":"if / elseif / else","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>$score = 85;\nif ($score >= 90) echo \"A\";\nelseif ($score >= 80) echo \"B\";\nelseif ($score >= 70) echo \"C\";\nelse echo \"F\";</pre>"},
            {"title":"match Expression (PHP 8)","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>$status = match($code) {\n    200 => 'OK',\n    404 => 'Not Found',\n    500 => 'Server Error',\n    default => 'Unknown'\n};</pre><p><code>match</code> uses strict comparison (<code>===</code>), returns a value, and throws if no match (no fall-through).</p>"},
        ],
        key_concepts="<ul><li><code>match</code> (PHP 8+) is preferred over <code>switch</code>: strict comparison, no fall-through, returns value.</li><li>Alternative syntax: <code>if(): ... endif;</code> is cleaner in HTML templates.</li><li>PHP has no falsy/truthy surprise if you use <code>===</code>.</li></ul>",
        examples=[
            {"title":"Grade Calculator","code":"<?php\n$score = 78;\n\nif ($score >= 90) $grade = 'A';\nelseif ($score >= 80) $grade = 'B';\nelseif ($score >= 70) $grade = 'C';\nelseif ($score >= 60) $grade = 'D';\nelse $grade = 'F';\n\necho \"Score: $score -> Grade: $grade\\n\";\necho ($grade === 'F') ? \"Retake required\\n\" : \"Passed!\\n\";\n?>","output":"Score: 78 -> Grade: C\nPassed!","explanation":"<p>Chained elseif with ternary output — straightforward conditional logic.</p>"},
            {"title":"match Expression (PHP 8)","code":"<?php\n$day = date('l');  // current day name\n\n$type = match(true) {\n    in_array($day, ['Saturday', 'Sunday']) => 'Weekend',\n    $day === 'Friday' => 'Almost weekend!',\n    default => 'Workday'\n};\n\necho \"$day: $type\\n\";\n\n// HTTP status\n$status = 404;\n$message = match($status) {\n    200 => 'OK',\n    301 => 'Moved',\n    404 => 'Not Found',\n    500 => 'Server Error',\n    default => 'Unknown'\n};\necho \"$status: $message\\n\";\n?>","output":"Friday: Almost weekend!\n404: Not Found","explanation":"<p><code>match(true)</code> evaluates each arm as a boolean — enabling complex conditions. Much safer than switch.</p>"},
            {"title":"Alternative Syntax in Templates","code":"<?php $items = ['Apple', 'Banana', 'Cherry']; ?>\n\n<?php if (count($items) > 0): ?>\n  <ul>\n  <?php foreach ($items as $item): ?>\n    <li><?= htmlspecialchars($item) ?></li>\n  <?php endforeach; ?>\n  </ul>\n<?php else: ?>\n  <p>No items found.</p>\n<?php endif; ?>","output":"<ul>\n  <li>Apple</li>\n  <li>Banana</li>\n  <li>Cherry</li>\n</ul>","explanation":"<p>Alternative syntax (<code>if(): ... endif;</code>) is cleaner than curly braces when mixing PHP with HTML.</p>"},
        ],
        quiz=[
            {"q":"match expressions use which comparison?","options":["== (loose)","=== (strict)","<=> (spaceship)","!= (not equal)"],"answer":"=== (strict)"},
            {"q":"What happens if no match arm matches and there's no default?","options":["Returns null","Returns false","Throws UnhandledMatchError","Falls through"],"answer":"Throws UnhandledMatchError"},
        ],
    ),
    "php_loops": make_topic(
        intro="<p>PHP loops: <code>for</code>, <code>foreach</code>, <code>while</code>, <code>do-while</code>. The <code>foreach</code> loop is PHP's most important loop — it iterates arrays and objects with clean syntax. PHP arrays are ordered maps (both indexed and associative), and <code>foreach</code> handles both. <code>break</code> exits a loop; <code>continue</code> skips to the next iteration.</p>",
        subtopics=[
            {"title":"foreach — The PHP Loop","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>$fruits = ['Apple', 'Banana', 'Cherry'];\nforeach ($fruits as $fruit) {\n    echo \"$fruit\\n\";\n}\n\n// With keys\n$scores = ['Alice' => 95, 'Bob' => 87];\nforeach ($scores as $name => $score) {\n    echo \"$name: $score\\n\";\n}</pre>"},
            {"title":"for & while","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>for ($i = 0; $i < 5; $i++) echo $i . ' ';\n// 0 1 2 3 4\n\n$n = 10;\nwhile ($n > 0) {\n    echo $n . ' ';\n    $n -= 3;\n}\n// 10 7 4 1</pre>"},
        ],
        key_concepts="<ul><li><code>foreach</code> works with both indexed and associative arrays.</li><li><code>foreach ($arr as &$val)</code> — reference allows modification (unset after loop!).</li><li><code>break 2;</code> breaks out of 2 nested loops.</li><li>Use <code>range(1, 10)</code> to generate a sequence.</li></ul>",
        examples=[
            {"title":"Iterating Arrays","code":"<?php\n$colors = ['red', 'green', 'blue'];\n\necho \"Indexed:\\n\";\nforeach ($colors as $index => $color) {\n    echo \"  $index: $color\\n\";\n}\n\n$user = ['name' => 'Alice', 'age' => 25, 'city' => 'NYC'];\necho \"Associative:\\n\";\nforeach ($user as $key => $value) {\n    echo \"  $key: $value\\n\";\n}\n?>","output":"Indexed:\n  0: red\n  1: green\n  2: blue\nAssociative:\n  name: Alice\n  age: 25\n  city: NYC","explanation":"<p><code>foreach</code> provides both key and value — works identically for indexed and associative arrays.</p>"},
            {"title":"FizzBuzz","code":"<?php\nfor ($i = 1; $i <= 15; $i++) {\n    if ($i % 15 === 0) echo \"FizzBuzz\";\n    elseif ($i % 3 === 0) echo \"Fizz\";\n    elseif ($i % 5 === 0) echo \"Buzz\";\n    else echo $i;\n    echo \"\\n\";\n}\n?>","output":"1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz","explanation":"<p>Classic for-loop problem. Check 15 first to avoid printing only Fizz or Buzz for multiples of both.</p>"},
            {"title":"Array Transformation in Loop","code":"<?php\n$prices = [10.5, 20.0, 15.75, 30.25];\n$tax_rate = 0.08;\n\n$totals = [];\nforeach ($prices as $price) {\n    $totals[] = round($price * (1 + $tax_rate), 2);\n}\n\necho \"Prices: \" . implode(', ', $prices) . \"\\n\";\necho \"With tax: \" . implode(', ', $totals) . \"\\n\";\necho \"Total: $\" . array_sum($totals) . \"\\n\";\n?>","output":"Prices: 10.5, 20, 15.75, 30.25\nWith tax: 11.34, 21.6, 17.01, 32.67\nTotal: $82.62","explanation":"<p><code>$arr[] = value</code> appends to an array. <code>implode()</code> joins, <code>array_sum()</code> totals.</p>"},
        ],
        quiz=[
            {"q":"foreach ($arr as &$val) — what does & do?","options":["Creates a copy","Passes by reference (allows modification)","Gets the key","Skips null values"],"answer":"Passes by reference (allows modification)"},
            {"q":"break 2; does what?","options":["Breaks current loop","Breaks out of 2 nested loops","Pauses for 2 seconds","Skips 2 iterations"],"answer":"Breaks out of 2 nested loops"},
        ],
    ),
    "php_functions": make_topic(
        intro="<p>PHP functions support <strong>default parameters</strong>, <strong>type declarations</strong> (PHP 7+), <strong>return type hints</strong>, <strong>variadic arguments</strong> (<code>...$args</code>), <strong>named arguments</strong> (PHP 8), and <strong>arrow functions</strong> (<code>fn() =></code>). PHP 7+ introduced <strong>strict typing</strong> mode with <code>declare(strict_types=1)</code>, turning PHP from a loosely-typed into a safely-typed language for function boundaries.</p>",
        subtopics=[
            {"title":"Function Syntax","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>function greet(string $name, string $greeting = 'Hello'): string {\n    return \"$greeting, $name!\";\n}\necho greet('Alice');           // Hello, Alice!\necho greet('Bob', 'Hi');       // Hi, Bob!\necho greet(greeting: 'Hey', name: 'Charlie'); // Named args (PHP 8)</pre>"},
            {"title":"Arrow Functions (PHP 7.4+)","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>$double = fn($x) => $x * 2;\n$nums = [1, 2, 3, 4];\n$doubled = array_map(fn($n) => $n * 2, $nums);\n// [2, 4, 6, 8]</pre>"},
        ],
        key_concepts="<ul><li>Type hints: <code>function foo(int $x): string</code> — enforced at runtime.</li><li><code>declare(strict_types=1)</code> at top of file enables strict type checking.</li><li><code>...$args</code> variadic parameter collects remaining arguments into an array.</li><li>Arrow functions (<code>fn() =></code>) auto-capture outer scope variables (closures don't — use <code>use</code>).</li><li>Named arguments (PHP 8): call by parameter name, skip defaults.</li></ul>",
        examples=[
            {"title":"Typed Functions","code":"<?php\ndeclare(strict_types=1);\n\nfunction add(int $a, int $b): int {\n    return $a + $b;\n}\n\nfunction formatPrice(float $price, string $currency = 'USD'): string {\n    return \"$currency \" . number_format($price, 2);\n}\n\necho add(3, 4) . \"\\n\";              // 7\necho formatPrice(29.99) . \"\\n\";      // USD 29.99\necho formatPrice(49.50, 'EUR') . \"\\n\"; // EUR 49.50\n?>","output":"7\nUSD 29.99\nEUR 49.50","explanation":"<p>Type hints with <code>strict_types=1</code> catches type mismatches at runtime — much safer code.</p>"},
            {"title":"Array Functions (map, filter, reduce)","code":"<?php\n$numbers = [1, 2, 3, 4, 5, 6, 7, 8];\n\n$evens = array_filter($numbers, fn($n) => $n % 2 === 0);\n$doubled = array_map(fn($n) => $n * 2, $numbers);\n$sum = array_reduce($numbers, fn($carry, $n) => $carry + $n, 0);\n\necho \"Evens: \" . implode(', ', $evens) . \"\\n\";\necho \"Doubled: \" . implode(', ', $doubled) . \"\\n\";\necho \"Sum: $sum\\n\";\n?>","output":"Evens: 2, 4, 6, 8\nDoubled: 2, 4, 6, 8, 10, 12, 14, 16\nSum: 36","explanation":"<p>PHP's functional array functions with arrow functions — concise and readable.</p>"},
            {"title":"Variadic & Named Arguments","code":"<?php\nfunction sum(int ...$numbers): int {\n    return array_sum($numbers);\n}\n\nfunction createUser(string $name, int $age, string $role = 'user'): string {\n    return \"$name ($role, age $age)\";\n}\n\necho sum(1, 2, 3, 4, 5) . \"\\n\";     // 15\necho createUser('Alice', 25) . \"\\n\"; // Alice (user, age 25)\necho createUser(\n    name: 'Bob',\n    role: 'admin',\n    age: 30\n) . \"\\n\"; // Named args, any order\n?>","output":"15\nAlice (user, age 25)\nBob (admin, age 30)","explanation":"<p><code>...$numbers</code> collects all arguments. Named arguments (PHP 8) allow calling in any order.</p>"},
        ],
        quiz=[
            {"q":"declare(strict_types=1) enables:","options":["OOP mode","Strict type checking for functions","Thread safety","Namespace isolation"],"answer":"Strict type checking for functions"},
            {"q":"Arrow functions in PHP use:","options":["-> syntax","=> syntax","fn() => syntax","lambda() syntax"],"answer":"fn() => syntax"},
        ],
    ),
    "php_arrays": make_topic(
        intro="<p>PHP arrays are the language's most versatile data structure — they serve as <strong>indexed arrays</strong>, <strong>associative arrays</strong> (hash maps), <strong>stacks</strong>, <strong>queues</strong>, and <strong>sets</strong>. PHP provides 80+ built-in array functions: <code>array_map</code>, <code>array_filter</code>, <code>array_merge</code>, <code>array_slice</code>, <code>sort</code>, <code>usort</code>, and more. Arrays are ordered maps — keys can be integers or strings, and insertion order is preserved.</p>",
        subtopics=[
            {"title":"Creating Arrays","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>$indexed = [10, 20, 30]; // or array(10, 20, 30)\n$assoc = ['name' => 'Alice', 'age' => 25];\n$nested = [\n    ['id' => 1, 'name' => 'Alice'],\n    ['id' => 2, 'name' => 'Bob'],\n];</pre>"},
            {"title":"Array Functions","content":"<ul><li><code>count($arr)</code> — length</li><li><code>array_push($arr, $val)</code> or <code>$arr[] = $val</code></li><li><code>array_pop($arr)</code> — remove last</li><li><code>array_merge($a, $b)</code> — combine</li><li><code>in_array($val, $arr)</code> — search</li><li><code>array_keys($arr)</code>, <code>array_values($arr)</code></li><li><code>array_unique($arr)</code> — remove duplicates</li></ul>"},
        ],
        key_concepts="<ul><li>PHP arrays are ordered hash maps — both integer and string keys coexist.</li><li><code>$arr[] = value</code> appends. <code>unset($arr[key])</code> removes by key.</li><li><code>array_map</code> transforms, <code>array_filter</code> filters, <code>array_reduce</code> aggregates.</li><li><code>list($a, $b) = $arr</code> or <code>[$a, $b] = $arr</code> destructures arrays.</li><li>Spread operator: <code>[...$arr1, ...$arr2]</code> merges arrays (PHP 7.4+).</li></ul>",
        examples=[
            {"title":"Array Operations","code":"<?php\n$fruits = ['Apple', 'Banana', 'Cherry'];\n$fruits[] = 'Date';  // append\narray_unshift($fruits, 'Avocado');  // prepend\n\necho \"Count: \" . count($fruits) . \"\\n\";\necho \"Has Banana: \" . (in_array('Banana', $fruits) ? 'Yes' : 'No') . \"\\n\";\n\nsort($fruits);\necho \"Sorted: \" . implode(', ', $fruits) . \"\\n\";\n?>","output":"Count: 5\nHas Banana: Yes\nSorted: Apple, Avocado, Banana, Cherry, Date","explanation":"<p>PHP arrays support push, prepend, search, and sort with simple function calls.</p>"},
            {"title":"Associative Array (Hash Map)","code":"<?php\n$student = [\n    'name' => 'Alice',\n    'age' => 20,\n    'grades' => [85, 92, 78, 95]\n];\n\necho \"{$student['name']}, age {$student['age']}\\n\";\necho \"Avg grade: \" . array_sum($student['grades']) / count($student['grades']) . \"\\n\";\n\n// Check key exists\nif (array_key_exists('email', $student)) {\n    echo $student['email'];\n} else {\n    echo \"No email on file\\n\";\n}\n?>","output":"Alice, age 20\nAvg grade: 87.5\nNo email on file","explanation":"<p>Associative arrays work like Python dicts/JS objects. <code>array_key_exists()</code> safely checks for keys.</p>"},
            {"title":"Destructuring & Spread","code":"<?php\n// Array destructuring\n$coords = [37.7749, -122.4194];\n[$lat, $lng] = $coords;\necho \"Location: $lat, $lng\\n\";\n\n// Spread operator (PHP 7.4+)\n$first = [1, 2, 3];\n$second = [4, 5, 6];\n$merged = [...$first, ...$second];\necho \"Merged: \" . implode(', ', $merged) . \"\\n\";\n\n// Named destructuring\n['name' => $name, 'age' => $age] = ['name' => 'Bob', 'age' => 30];\necho \"$name is $age\\n\";\n?>","output":"Location: 37.7749, -122.4194\nMerged: 1, 2, 3, 4, 5, 6\nBob is 30","explanation":"<p>Destructuring unpacks arrays into variables. Spread operator merges arrays cleanly.</p>"},
        ],
        quiz=[
            {"q":"PHP arrays are internally implemented as:","options":["Linked lists","B-trees","Ordered hash maps","Fixed-size arrays"],"answer":"Ordered hash maps"},
            {"q":"$arr[] = 'value' does what?","options":["Replaces all values","Appends to the array","Creates a new array","Throws an error"],"answer":"Appends to the array"},
        ],
    ),
    "php_strings": make_topic(
        intro="<p>PHP has extensive string handling: 100+ built-in string functions, regular expression support (PCRE), and powerful formatting. Strings can be single-quoted (<code>'literal'</code> — no interpolation), double-quoted (<code>\"with $vars\"</code>), heredoc (<code>&lt;&lt;&lt;EOT</code>), and nowdoc (<code>&lt;&lt;&lt;'EOT'</code>). PHP 8 added <code>str_contains()</code>, <code>str_starts_with()</code>, and <code>str_ends_with()</code>.</p>",
        subtopics=[
            {"title":"String Functions","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>$s = \"Hello, PHP World!\";\nstrlen($s);              // 17\nstrtoupper($s);          // HELLO, PHP WORLD!\nstr_replace('PHP', 'Web', $s); // Hello, Web World!\nsubstr($s, 7, 3);        // PHP\nstr_contains($s, 'PHP'); // true (PHP 8+)\nexplode(' ', $s);        // ['Hello,', 'PHP', 'World!']</pre>"},
            {"title":"Regular Expressions","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>$email = 'user@example.com';\nif (preg_match('/^[\\w.]+@[\\w]+\\.[a-z]{2,}$/i', $email)) {\n    echo 'Valid email';\n}\n\n$text = 'Call 555-1234 or 555-5678';\npreg_match_all('/\\d{3}-\\d{4}/', $text, $matches);\n// $matches[0] = ['555-1234', '555-5678']</pre>"},
        ],
        key_concepts="<ul><li><code>.</code> concatenates strings (not <code>+</code>).</li><li><code>explode()</code> splits string to array; <code>implode()</code> joins array to string.</li><li><code>sprintf()</code> formats strings: <code>sprintf('%.2f', 3.14159)</code> → '3.14'.</li><li><code>htmlspecialchars()</code> prevents XSS — always escape user input in HTML output.</li><li>PHP 8: <code>str_contains()</code>, <code>str_starts_with()</code>, <code>str_ends_with()</code> — finally!</li></ul>",
        examples=[
            {"title":"String Manipulation","code":"<?php\n$text = \"  Hello, PHP World!  \";\n\necho \"Length: \" . strlen(trim($text)) . \"\\n\";\necho \"Upper: \" . strtoupper($text) . \"\\n\";\necho \"Replace: \" . str_replace('PHP', 'Web', $text) . \"\\n\";\necho \"Reverse: \" . strrev(trim($text)) . \"\\n\";\necho \"Repeat: \" . str_repeat('Ha', 3) . \"\\n\";\necho \"Pad: '\" . str_pad('42', 5, '0', STR_PAD_LEFT) . \"'\\n\";\n?>","output":"Length: 17\nUpper:   HELLO, PHP WORLD!  \nReplace:   Hello, Web World!  \nReverse: !dlroW PHP ,olleH\nRepeat: HaHaHa\nPad: '00042'","explanation":"<p>PHP has a string function for almost everything — no regex needed for common operations.</p>"},
            {"title":"Explode, Implode & Formatting","code":"<?php\n$csv = \"Alice,25,3.8;Bob,22,3.5;Charlie,21,3.9\";\n\n$rows = explode(';', $csv);\nforeach ($rows as $row) {\n    [$name, $age, $gpa] = explode(',', $row);\n    echo sprintf(\"%-10s Age: %2d  GPA: %.1f\\n\", $name, $age, $gpa);\n}\n\n$words = ['PHP', 'is', 'awesome'];\necho implode(' ', $words) . \"\\n\";\n?>","output":"Alice      Age: 25  GPA: 3.8\nBob        Age: 22  GPA: 3.5\nCharlie    Age: 21  GPA: 3.9\nPHP is awesome","explanation":"<p><code>explode()</code> splits, <code>sprintf()</code> formats with padding and precision — clean tabular output.</p>"},
            {"title":"PHP 8 String Functions","code":"<?php\n$url = 'https://www.example.com/page';\n\necho str_contains($url, 'example') ? 'Contains example' : 'No';\necho \"\\n\";\necho str_starts_with($url, 'https') ? 'HTTPS' : 'HTTP';\necho \"\\n\";\necho str_ends_with($url, '.html') ? 'HTML page' : 'Not HTML';\necho \"\\n\";\n\n// Before PHP 8 you needed:\n// strpos($url, 'example') !== false\n// substr($url, 0, 5) === 'https'\n?>","output":"Contains example\nHTTPS\nNot HTML","explanation":"<p>PHP 8 finally added intuitive string checking functions — no more <code>strpos !== false</code> hacks.</p>"},
        ],
        quiz=[
            {"q":"Which PHP operator concatenates strings?","options":["+","&",".",".."],"answer":"."},
            {"q":"str_contains() was introduced in:","options":["PHP 5","PHP 7","PHP 7.4","PHP 8"],"answer":"PHP 8"},
        ],
    ),
    "php_forms": make_topic(
        intro="<p><strong>Form handling</strong> is PHP's core strength — processing HTML form submissions via <code>$_GET</code> and <code>$_POST</code> superglobals. Forms submit data via HTTP GET (in URL) or POST (in body). Server-side validation and sanitization are critical — never trust user input. PHP provides <code>filter_input()</code> and <code>htmlspecialchars()</code> for safe processing.</p>",
        subtopics=[{"title":"$_GET vs $_POST","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>// HTML: <form method='post' action='process.php'>\n$name = $_POST['name'] ?? '';\n$email = $_POST['email'] ?? '';\n\n// Sanitize\n$name = htmlspecialchars(trim($name));\n$email = filter_var($email, FILTER_SANITIZE_EMAIL);</pre>"},{"title":"Validation","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>$errors = [];\nif (empty($name)) $errors[] = 'Name is required';\nif (!filter_var($email, FILTER_VALIDATE_EMAIL))\n    $errors[] = 'Invalid email';\nif (strlen($name) > 50)\n    $errors[] = 'Name too long';</pre>"}],
        key_concepts="<ul><li>GET: data in URL (bookmarkable, limited size). Use for search, filters.</li><li>POST: data in body (hidden, no size limit). Use for login, registration, mutations.</li><li>Always sanitize: <code>htmlspecialchars()</code> for HTML output, <code>filter_var()</code> for validation.</li><li>CSRF protection: include a token in forms, verify on submit.</li></ul>",
        examples=[
            {"title":"Form Processing","code":"<?php\n// Simulate POST data\n$_POST = ['name' => '  Alice  ', 'email' => 'alice@example.com', 'age' => '25'];\n\n$name = htmlspecialchars(trim($_POST['name'] ?? ''));\n$email = filter_var($_POST['email'] ?? '', FILTER_SANITIZE_EMAIL);\n$age = (int)($_POST['age'] ?? 0);\n\n$errors = [];\nif (empty($name)) $errors[] = 'Name required';\nif (!filter_var($email, FILTER_VALIDATE_EMAIL)) $errors[] = 'Invalid email';\nif ($age < 1 || $age > 150) $errors[] = 'Invalid age';\n\nif (empty($errors)) {\n    echo \"Valid: $name, $email, age $age\\n\";\n} else {\n    foreach ($errors as $err) echo \"Error: $err\\n\";\n}\n?>","output":"Valid: Alice, alice@example.com, age 25","explanation":"<p>Trim, sanitize, validate, then process — the standard PHP form handling pattern.</p>"},
            {"title":"Filter Functions","code":"<?php\n$inputs = [\n    'good@email.com',\n    'bad-email',\n    'http://example.com',\n    'not-a-url',\n    '42',\n    'not-a-number'\n];\n\nforeach ($inputs as $input) {\n    $is_email = filter_var($input, FILTER_VALIDATE_EMAIL) ? 'Valid email' : '';\n    $is_url = filter_var($input, FILTER_VALIDATE_URL) ? 'Valid URL' : '';\n    $is_int = filter_var($input, FILTER_VALIDATE_INT) !== false ? 'Valid int' : '';\n    $type = $is_email ?: $is_url ?: $is_int ?: 'Invalid';\n    echo \"$input => $type\\n\";\n}\n?>","output":"good@email.com => Valid email\nbad-email => Invalid\nhttp://example.com => Valid URL\nnot-a-url => Invalid\n42 => Valid int\nnot-a-number => Invalid","explanation":"<p><code>filter_var()</code> validates emails, URLs, integers, and more — much safer than regex for common patterns.</p>"},
            {"title":"XSS Prevention","code":"<?php\n// User input (potentially malicious)\n$input = '<script>alert(\"XSS\")</script>';\n\n// UNSAFE — directly echoing user input\necho \"Unsafe: $input\\n\";\n\n// SAFE — escaping HTML entities\n$safe = htmlspecialchars($input, ENT_QUOTES, 'UTF-8');\necho \"Safe: $safe\\n\";\n?>","output":"Unsafe: <script>alert(\"XSS\")</script>\nSafe: &lt;script&gt;alert(&quot;XSS&quot;)&lt;/script&gt;","explanation":"<p><code>htmlspecialchars()</code> converts <code>&lt;</code> to <code>&amp;lt;</code>, preventing script injection — the #1 web security rule.</p>"},
        ],
        quiz=[
            {"q":"Which function prevents XSS attacks?","options":["strip_tags()","htmlspecialchars()","addslashes()","urlencode()"],"answer":"htmlspecialchars()"},
            {"q":"$_POST data is sent:","options":["In the URL","In the HTTP body","In cookies","In headers only"],"answer":"In the HTTP body"},
        ],
    ),
    "php_oop": make_topic(
        intro="<p>PHP has full <strong>object-oriented programming</strong> support: classes, interfaces, abstract classes, traits, enums (PHP 8.1), constructor promotion (PHP 8.0), readonly properties (PHP 8.1), and named arguments. Modern PHP OOP is comparable to Java/C# in capability. Laravel, Symfony, and all modern PHP frameworks are built entirely on OOP principles.</p>",
        subtopics=[{"title":"Classes & Constructor Promotion","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>// PHP 8 constructor promotion\nclass User {\n    public function __construct(\n        private string $name,\n        private int $age,\n        private string $role = 'user'\n    ) {}\n    \n    public function greet(): string {\n        return \"Hi, I'm {$this->name} ({$this->role})\";\n    }\n}</pre>"},{"title":"Interfaces & Traits","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>interface Loggable {\n    public function log(string $msg): void;\n}\n\ntrait Timestamps {\n    public function createdAt(): string {\n        return date('Y-m-d H:i:s');\n    }\n}\n\nclass Post implements Loggable {\n    use Timestamps;\n    public function log(string $msg): void { echo $msg; }\n}</pre>"}],
        key_concepts="<ul><li>Constructor promotion (PHP 8): declare and assign properties in one line.</li><li>Traits: reusable code blocks included in multiple classes (PHP's solution to no multiple inheritance).</li><li>Enums (PHP 8.1): <code>enum Status { case Active; case Inactive; }</code></li><li>Readonly properties (PHP 8.1): set once in constructor, immutable after.</li><li><code>$this-></code> accesses instance members. <code>self::</code> accesses static members.</li></ul>",
        examples=[
            {"title":"Class with Constructor Promotion","code":"<?php\nclass Product {\n    public function __construct(\n        private string $name,\n        private float $price,\n        private int $quantity = 0\n    ) {}\n    \n    public function total(): float {\n        return $this->price * $this->quantity;\n    }\n    \n    public function __toString(): string {\n        return \"{$this->name}: \\${$this->price} x {$this->quantity} = \\${$this->total()}\";\n    }\n}\n\n$p = new Product('Laptop', 999.99, 2);\necho $p . \"\\n\";\n?>","output":"Laptop: $999.99 x 2 = $1999.98","explanation":"<p>Constructor promotion eliminates the <code>$this->prop = $prop;</code> boilerplate — 3 lines instead of 9.</p>"},
            {"title":"Inheritance & Polymorphism","code":"<?php\nabstract class Shape {\n    abstract public function area(): float;\n    public function describe(): string {\n        return get_class($this) . \": area = \" . number_format($this->area(), 2);\n    }\n}\n\nclass Circle extends Shape {\n    public function __construct(private float $radius) {}\n    public function area(): float { return M_PI * $this->radius ** 2; }\n}\n\nclass Rectangle extends Shape {\n    public function __construct(private float $w, private float $h) {}\n    public function area(): float { return $this->w * $this->h; }\n}\n\n$shapes = [new Circle(5), new Rectangle(4, 6)];\nforeach ($shapes as $s) echo $s->describe() . \"\\n\";\n?>","output":"Circle: area = 78.54\nRectangle: area = 24.00","explanation":"<p>Abstract class defines a contract; each subclass provides its own <code>area()</code> implementation.</p>"},
            {"title":"Trait (Code Reuse)","code":"<?php\ntrait HasTimestamps {\n    private string $created;\n    public function setCreated(): void { $this->created = date('Y-m-d'); }\n    public function getCreated(): string { return $this->created; }\n}\n\ntrait HasSlug {\n    public function slug(string $title): string {\n        return strtolower(str_replace(' ', '-', $title));\n    }\n}\n\nclass Article {\n    use HasTimestamps, HasSlug;\n    public function __construct(private string $title) {\n        $this->setCreated();\n    }\n}\n\n$article = new Article('PHP 8 New Features');\necho \"Slug: \" . $article->slug('PHP 8 New Features') . \"\\n\";\necho \"Created: \" . $article->getCreated() . \"\\n\";\n?>","output":"Slug: php-8-new-features\nCreated: 2024-01-15","explanation":"<p>Traits inject reusable functionality — <code>Article</code> gets both timestamp and slug methods without inheritance.</p>"},
        ],
        quiz=[
            {"q":"Traits in PHP solve:","options":["Null safety","Multiple inheritance limitation","Async programming","Database access"],"answer":"Multiple inheritance limitation"},
            {"q":"Constructor promotion was introduced in:","options":["PHP 7","PHP 7.4","PHP 8.0","PHP 8.1"],"answer":"PHP 8.0"},
        ],
    ),
    "php_inheritance": make_topic(
        intro="<p><strong>Inheritance</strong> in PHP allows a child class to extend a parent class, inheriting all public and protected members. PHP supports single inheritance (one parent) plus interfaces and traits for additional capabilities. <code>abstract</code> classes define contracts; <code>final</code> prevents overriding. The <code>parent::</code> keyword calls the parent's methods.</p>",
        subtopics=[{"title":"extends & override","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>class Animal {\n    public function __construct(protected string $name) {}\n    public function speak(): string { return '...'; }\n}\nclass Dog extends Animal {\n    public function speak(): string { return \"$this->name says Woof!\"; }\n}\nclass Cat extends Animal {\n    public function speak(): string { return \"$this->name says Meow!\"; }\n}</pre>"},{"title":"Abstract & Final","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>abstract class Logger {\n    abstract public function log(string $msg): void;\n    public function info(string $msg): void { $this->log(\"[INFO] $msg\"); }\n}\n\nfinal class FileLogger extends Logger {\n    public function log(string $msg): void { echo $msg . \"\\n\"; }\n}</pre>"}],
        key_concepts="<ul><li><code>extends</code> for class inheritance; <code>implements</code> for interfaces.</li><li><code>abstract</code>: must be overridden. <code>final</code>: cannot be overridden.</li><li><code>parent::__construct()</code> calls parent constructor.</li><li>PHP 8: <code>readonly</code> properties can be set once and never changed.</li></ul>",
        examples=[
            {"title":"Polymorphism","code":"<?php\nclass Vehicle {\n    public function __construct(\n        protected string $make,\n        protected int $year\n    ) {}\n    public function describe(): string {\n        return \"{$this->year} {$this->make}\";\n    }\n}\nclass Car extends Vehicle {\n    public function __construct(string $make, int $year, private int $doors = 4) {\n        parent::__construct($make, $year);\n    }\n    public function describe(): string {\n        return parent::describe() . \" ({$this->doors}-door car)\";\n    }\n}\nclass Truck extends Vehicle {\n    public function describe(): string {\n        return parent::describe() . ' (truck)';\n    }\n}\n\n$vehicles = [new Car('Toyota', 2023), new Truck('Ford', 2022)];\nforeach ($vehicles as $v) echo $v->describe() . \"\\n\";\n?>","output":"2023 Toyota (4-door car)\n2022 Ford (truck)","explanation":"<p><code>parent::describe()</code> reuses the parent's logic while extending it in the child class.</p>"},
            {"title":"Interface Implementation","code":"<?php\ninterface Printable {\n    public function toString(): string;\n}\ninterface Exportable {\n    public function toJson(): string;\n}\n\nclass Report implements Printable, Exportable {\n    public function __construct(private string $title, private array $data) {}\n    public function toString(): string { return \"Report: {$this->title}\"; }\n    public function toJson(): string { return json_encode(['title' => $this->title, 'data' => $this->data]); }\n}\n\n$r = new Report('Sales', [100, 200, 300]);\necho $r->toString() . \"\\n\";\necho $r->toJson() . \"\\n\";\n?>","output":"Report: Sales\n{\"title\":\"Sales\",\"data\":[100,200,300]}","explanation":"<p>A class can implement multiple interfaces — achieving multiple inheritance of contracts.</p>"},
            {"title":"Abstract Class","code":"<?php\nabstract class Database {\n    abstract protected function connect(): bool;\n    abstract public function query(string $sql): array;\n    \n    public function execute(string $sql): void {\n        if ($this->connect()) {\n            $result = $this->query($sql);\n            echo \"Rows: \" . count($result) . \"\\n\";\n        }\n    }\n}\n\nclass MockDB extends Database {\n    protected function connect(): bool { echo \"Connected\\n\"; return true; }\n    public function query(string $sql): array { return ['row1', 'row2', 'row3']; }\n}\n\n$db = new MockDB();\n$db->execute('SELECT * FROM users');\n?>","output":"Connected\nRows: 3","explanation":"<p>Abstract class provides the template (<code>execute()</code>); concrete class implements the specifics.</p>"},
        ],
        quiz=[
            {"q":"PHP supports:","options":["Multiple class inheritance","Single class inheritance only","No inheritance","Diamond inheritance"],"answer":"Single class inheritance only"},
            {"q":"'final' on a method means:","options":["Must be overridden","Cannot be overridden","Is abstract","Is static"],"answer":"Cannot be overridden"},
        ],
    ),
    "php_traits": make_topic(
        intro="<p><strong>Traits</strong> are PHP's mechanism for code reuse in single-inheritance classes. A trait is a collection of methods that can be included in multiple unrelated classes using the <code>use</code> keyword. Traits solve the problem of shared functionality across classes that don't share a common ancestor. They can have methods, abstract methods, properties, and constants.</p>",
        subtopics=[{"title":"Trait Basics","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>trait Cacheable {\n    private array $cache = [];\n    public function cacheGet(string $key): mixed {\n        return $this->cache[$key] ?? null;\n    }\n    public function cacheSet(string $key, mixed $val): void {\n        $this->cache[$key] = $val;\n    }\n}</pre>"},{"title":"Conflict Resolution","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>trait A { public function greet() { echo 'A'; } }\ntrait B { public function greet() { echo 'B'; } }\n\nclass C {\n    use A, B {\n        A::greet insteadof B;  // resolve conflict\n        B::greet as greetB;    // alias\n    }\n}</pre>"}],
        key_concepts="<ul><li>Traits are included with <code>use TraitName;</code> inside a class body.</li><li>A class can use multiple traits: <code>use TraitA, TraitB;</code></li><li>Trait methods override inherited methods; class methods override trait methods.</li><li>Conflicts between traits must be resolved with <code>insteadof</code> and <code>as</code>.</li></ul>",
        examples=[
            {"title":"Reusable Trait","code":"<?php\ntrait Sluggable {\n    public function toSlug(string $text): string {\n        return strtolower(preg_replace('/[^a-z0-9]+/i', '-', trim($text)));\n    }\n}\ntrait Timestampable {\n    public function now(): string { return date('Y-m-d H:i:s'); }\n}\n\nclass Post {\n    use Sluggable, Timestampable;\n    public function __construct(private string $title) {}\n}\nclass Category {\n    use Sluggable;\n    public function __construct(private string $name) {}\n}\n\n$post = new Post('Hello World!');\necho $post->toSlug('Hello World!') . \"\\n\";\necho $post->now() . \"\\n\";\n\n$cat = new Category('Web Dev');\necho $cat->toSlug('Web Dev') . \"\\n\";\n?>","output":"hello-world-\n2024-01-15 10:30:00\nweb-dev","explanation":"<p>Both <code>Post</code> and <code>Category</code> get slug functionality without inheritance. <code>Post</code> also gets timestamps.</p>"},
            {"title":"Trait with Abstract Method","code":"<?php\ntrait Validatable {\n    abstract protected function rules(): array;\n    \n    public function validate(array $data): array {\n        $errors = [];\n        foreach ($this->rules() as $field => $rule) {\n            if ($rule === 'required' && empty($data[$field])) {\n                $errors[] = \"$field is required\";\n            }\n        }\n        return $errors;\n    }\n}\n\nclass LoginForm {\n    use Validatable;\n    protected function rules(): array {\n        return ['email' => 'required', 'password' => 'required'];\n    }\n}\n\n$form = new LoginForm();\n$errors = $form->validate(['email' => 'test@test.com', 'password' => '']);\nforeach ($errors as $e) echo \"Error: $e\\n\";\n?>","output":"Error: password is required","explanation":"<p>Trait with abstract methods forces classes to implement specific methods — a contract within a trait.</p>"},
            {"title":"Multiple Traits with Conflict","code":"<?php\ntrait Logger {\n    public function output(string $msg): void { echo \"[LOG] $msg\\n\"; }\n}\ntrait Debugger {\n    public function output(string $msg): void { echo \"[DEBUG] $msg\\n\"; }\n}\n\nclass App {\n    use Logger, Debugger {\n        Logger::output insteadof Debugger;\n        Debugger::output as debug;\n    }\n}\n\n$app = new App();\n$app->output('Starting app');  // Uses Logger\n$app->debug('Verbose info');   // Uses Debugger via alias\n?>","output":"[LOG] Starting app\n[DEBUG] Verbose info","explanation":"<p><code>insteadof</code> resolves conflicts; <code>as</code> creates an alias for the displaced method.</p>"},
        ],
        quiz=[
            {"q":"How do you include a trait in a class?","options":["extends TraitName","implements TraitName","use TraitName;","import TraitName"],"answer":"use TraitName;"},
            {"q":"Trait method conflicts are resolved with:","options":["override","extends","insteadof","replaces"],"answer":"insteadof"},
        ],
    ),
    "php_pdo": make_topic(
        intro="<p><strong>PDO (PHP Data Objects)</strong> is PHP's modern database abstraction layer — a unified API for MySQL, PostgreSQL, SQLite, and other databases. PDO provides <strong>prepared statements</strong> that prevent SQL injection, transaction support, and error handling modes. Never use the old <code>mysql_*</code> functions (removed in PHP 7). Always use PDO or MySQLi with prepared statements.</p>",
        subtopics=[{"title":"Connecting & Querying","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>$pdo = new PDO('mysql:host=localhost;dbname=mydb', 'user', 'pass');\n$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);\n\n// Prepared statement (SAFE)\n$stmt = $pdo->prepare('SELECT * FROM users WHERE email = ?');\n$stmt->execute(['alice@example.com']);\n$user = $stmt->fetch(PDO::FETCH_ASSOC);</pre>"},{"title":"CRUD Operations","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>// INSERT\n$stmt = $pdo->prepare('INSERT INTO users (name, email) VALUES (?, ?)');\n$stmt->execute(['Alice', 'alice@test.com']);\n$id = $pdo->lastInsertId();\n\n// UPDATE\n$pdo->prepare('UPDATE users SET name = ? WHERE id = ?')->execute(['Bob', $id]);\n\n// DELETE\n$pdo->prepare('DELETE FROM users WHERE id = ?')->execute([$id]);</pre>"}],
        key_concepts="<ul><li>Always use prepared statements — they prevent SQL injection by separating SQL from data.</li><li><code>PDO::ERRMODE_EXCEPTION</code> throws exceptions on errors (set it always).</li><li><code>fetch(PDO::FETCH_ASSOC)</code> returns associative array. <code>fetchAll()</code> gets all rows.</li><li>Named parameters: <code>:name</code> instead of <code>?</code> for readability.</li><li>Transactions: <code>beginTransaction()</code>, <code>commit()</code>, <code>rollBack()</code>.</li></ul>",
        examples=[
            {"title":"PDO Connection & Query","code":"<?php\ntry {\n    $pdo = new PDO('sqlite::memory:');\n    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);\n    \n    $pdo->exec('CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT, age INT)');\n    \n    $stmt = $pdo->prepare('INSERT INTO users (name, age) VALUES (?, ?)');\n    $stmt->execute(['Alice', 25]);\n    $stmt->execute(['Bob', 30]);\n    $stmt->execute(['Charlie', 22]);\n    \n    $result = $pdo->query('SELECT * FROM users ORDER BY age');\n    foreach ($result as $row) {\n        echo \"{$row['name']}: age {$row['age']}\\n\";\n    }\n} catch (PDOException $e) {\n    echo \"Error: \" . $e->getMessage();\n}\n?>","output":"Charlie: age 22\nAlice: age 25\nBob: age 30","explanation":"<p>SQLite in-memory database for demo. Prepared statements with <code>?</code> placeholders prevent SQL injection.</p>"},
            {"title":"Named Parameters","code":"<?php\n$pdo = new PDO('sqlite::memory:');\n$pdo->exec('CREATE TABLE products (id INTEGER PRIMARY KEY, name TEXT, price REAL)');\n\n$stmt = $pdo->prepare('INSERT INTO products (name, price) VALUES (:name, :price)');\n\n$products = [\n    ['name' => 'Laptop', 'price' => 999.99],\n    ['name' => 'Mouse', 'price' => 29.99],\n    ['name' => 'Keyboard', 'price' => 79.99],\n];\n\nforeach ($products as $p) {\n    $stmt->execute($p);\n}\n\n$result = $pdo->query('SELECT name, price FROM products');\nwhile ($row = $result->fetch(PDO::FETCH_ASSOC)) {\n    echo sprintf(\"%-10s $%.2f\\n\", $row['name'], $row['price']);\n}\n?>","output":"Laptop     $999.99\nMouse      $29.99\nKeyboard   $79.99","explanation":"<p>Named parameters (<code>:name</code>, <code>:price</code>) are more readable than positional <code>?</code> — keys match array keys.</p>"},
            {"title":"Transaction Example","code":"<?php\n$pdo = new PDO('sqlite::memory:');\n$pdo->exec('CREATE TABLE accounts (id INTEGER PRIMARY KEY, name TEXT, balance REAL)');\n$pdo->exec(\"INSERT INTO accounts VALUES (1, 'Alice', 1000)\");\n$pdo->exec(\"INSERT INTO accounts VALUES (2, 'Bob', 500)\");\n\ntry {\n    $pdo->beginTransaction();\n    \n    $pdo->prepare('UPDATE accounts SET balance = balance - ? WHERE id = ?')->execute([200, 1]);\n    $pdo->prepare('UPDATE accounts SET balance = balance + ? WHERE id = ?')->execute([200, 2]);\n    \n    $pdo->commit();\n    echo \"Transfer successful!\\n\";\n} catch (Exception $e) {\n    $pdo->rollBack();\n    echo \"Transfer failed: \" . $e->getMessage();\n}\n\n$stmt = $pdo->query('SELECT * FROM accounts');\nforeach ($stmt as $row) {\n    echo \"{$row['name']}: \\${$row['balance']}\\n\";\n}\n?>","output":"Transfer successful!\nAlice: $800\nBob: $700","explanation":"<p>Transactions ensure both operations succeed or both fail — critical for financial operations.</p>"},
        ],
        quiz=[
            {"q":"Prepared statements prevent:","options":["XSS attacks","SQL injection","CSRF attacks","Buffer overflow"],"answer":"SQL injection"},
            {"q":"PDO stands for:","options":["PHP Data Output","PHP Database Object","PHP Data Objects","PHP Dynamic Operations"],"answer":"PHP Data Objects"},
        ],
    ),
    "php_sessions": make_topic(
        intro="<p><strong>Sessions</strong> and <strong>cookies</strong> maintain state across HTTP requests (HTTP is stateless). <strong>Cookies</strong> store small data on the client (browser) — sent with every request. <strong>Sessions</strong> store data on the server, identified by a session ID cookie. Sessions are used for authentication, shopping carts, and user preferences. PHP's <code>$_SESSION</code> superglobal makes session management straightforward.</p>",
        subtopics=[{"title":"Sessions","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>session_start();  // must be first!\n\n$_SESSION['user'] = 'Alice';\n$_SESSION['role'] = 'admin';\n\necho $_SESSION['user'];  // Alice\n\n// Destroy session (logout)\nsession_destroy();</pre>"},{"title":"Cookies","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>// Set cookie (expires in 30 days)\nsetcookie('theme', 'dark', time() + 86400 * 30, '/');\n\n// Read cookie\n$theme = $_COOKIE['theme'] ?? 'light';\n\n// Delete cookie\nsetcookie('theme', '', time() - 3600, '/');</pre>"}],
        key_concepts="<ul><li><code>session_start()</code> must be called before any output.</li><li>Session ID is stored as a cookie (<code>PHPSESSID</code> by default).</li><li>Session data stored server-side — more secure than cookies for sensitive data.</li><li>Cookies: 4KB max, sent with every request — don't store large data.</li><li>Session fixation prevention: <code>session_regenerate_id(true)</code> after login.</li></ul>",
        examples=[
            {"title":"Login with Sessions","code":"<?php\nsession_start();\n\nfunction login(string $username, string $password): bool {\n    // Simulated user database\n    $users = ['alice' => 'pass123', 'bob' => 'secret'];\n    \n    if (isset($users[$username]) && $users[$username] === $password) {\n        $_SESSION['user'] = $username;\n        $_SESSION['logged_in'] = true;\n        session_regenerate_id(true);  // prevent fixation\n        return true;\n    }\n    return false;\n}\n\nfunction isLoggedIn(): bool {\n    return $_SESSION['logged_in'] ?? false;\n}\n\nlogin('alice', 'pass123');\necho isLoggedIn() ? \"Logged in as {$_SESSION['user']}\" : \"Not logged in\";\necho \"\\n\";\n?>","output":"Logged in as alice","explanation":"<p><code>session_regenerate_id(true)</code> after login prevents session fixation attacks.</p>"},
            {"title":"Shopping Cart with Sessions","code":"<?php\nsession_start();\n$_SESSION['cart'] = $_SESSION['cart'] ?? [];\n\nfunction addToCart(string $item, float $price): void {\n    $_SESSION['cart'][] = ['item' => $item, 'price' => $price];\n}\n\nfunction getTotal(): float {\n    return array_sum(array_column($_SESSION['cart'], 'price'));\n}\n\naddToCart('Laptop', 999.99);\naddToCart('Mouse', 29.99);\naddToCart('Keyboard', 79.99);\n\necho \"Cart (\" . count($_SESSION['cart']) . \" items):\\n\";\nforeach ($_SESSION['cart'] as $item) {\n    echo \"  {$item['item']}: \\${$item['price']}\\n\";\n}\necho \"Total: \\$\" . number_format(getTotal(), 2) . \"\\n\";\n?>","output":"Cart (3 items):\n  Laptop: $999.99\n  Mouse: $29.99\n  Keyboard: $79.99\nTotal: $1,109.97","explanation":"<p>Session-based cart persists across page loads. <code>array_column()</code> extracts prices for summing.</p>"},
            {"title":"Cookie Preferences","code":"<?php\n// Set user preferences as cookies\nsetcookie('theme', 'dark', time() + 86400*30, '/');\nsetcookie('lang', 'en', time() + 86400*30, '/');\n\n// Simulate reading (would be on next request)\n$_COOKIE['theme'] = 'dark';\n$_COOKIE['lang'] = 'en';\n\n$theme = $_COOKIE['theme'] ?? 'light';\n$lang = $_COOKIE['lang'] ?? 'en';\n\necho \"Theme: $theme\\n\";\necho \"Language: $lang\\n\";\necho \"Cookie max size: ~4KB\\n\";\necho \"Cookies are sent with EVERY HTTP request\\n\";\n?>","output":"Theme: dark\nLanguage: en\nCookie max size: ~4KB\nCookies are sent with EVERY HTTP request","explanation":"<p>Cookies persist in the browser. Use for non-sensitive preferences; use sessions for auth data.</p>"},
        ],
        quiz=[
            {"q":"Session data is stored:","options":["In cookies","On the server","In the URL","In localStorage"],"answer":"On the server"},
            {"q":"session_start() must be called:","options":["After HTML output","Before any output","Only once per app","In the footer"],"answer":"Before any output"},
        ],
    ),
    "php_files": make_topic(
        intro="<p>PHP provides built-in functions for <strong>file system operations</strong>: reading, writing, uploading, and directory management. Key functions: <code>file_get_contents()</code> / <code>file_put_contents()</code> for simple read/write, <code>fopen()</code> / <code>fclose()</code> for streaming, and <code>move_uploaded_file()</code> for file uploads. Always validate file types and sizes for uploads to prevent security vulnerabilities.</p>",
        subtopics=[{"title":"Read & Write","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>// Simple read/write\n$content = file_get_contents('data.txt');\nfile_put_contents('output.txt', 'Hello!');\nfile_put_contents('log.txt', 'entry\\n', FILE_APPEND);\n\n// Line-by-line\n$lines = file('data.txt', FILE_IGNORE_NEW_LINES);</pre>"},{"title":"File Uploads","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>if ($_FILES['upload']['error'] === UPLOAD_ERR_OK) {\n    $tmp = $_FILES['upload']['tmp_name'];\n    $name = basename($_FILES['upload']['name']);\n    move_uploaded_file($tmp, \"uploads/$name\");\n}</pre>"}],
        key_concepts="<ul><li><code>file_get_contents()</code> reads entire file to string — simple and fast.</li><li><code>file_put_contents()</code> writes string to file. <code>FILE_APPEND</code> flag appends.</li><li><code>file()</code> reads file into array of lines.</li><li>Always validate uploads: check <code>$_FILES['error']</code>, MIME type, file size, and extension.</li><li><code>is_file()</code>, <code>file_exists()</code>, <code>is_dir()</code> for checking paths.</li></ul>",
        examples=[
            {"title":"Read & Write Files","code":"<?php\n$filename = '/tmp/test_php.txt';\n\n// Write\nfile_put_contents($filename, \"Line 1\\nLine 2\\nLine 3\\n\");\necho \"Written!\\n\";\n\n// Read entire file\n$content = file_get_contents($filename);\necho \"Content:\\n$content\";\n\n// Read as array of lines\n$lines = file($filename, FILE_IGNORE_NEW_LINES);\necho \"Lines: \" . count($lines) . \"\\n\";\necho \"First: {$lines[0]}\\n\";\n\n// Append\nfile_put_contents($filename, \"Line 4\\n\", FILE_APPEND);\n?>","output":"Written!\nContent:\nLine 1\nLine 2\nLine 3\nLines: 3\nFirst: Line 1","explanation":"<p><code>file_get_contents</code>/<code>file_put_contents</code> are PHP's simplest file I/O — one function each.</p>"},
            {"title":"CSV File Processing","code":"<?php\n$csv = \"Name,Age,Score\\nAlice,25,95\\nBob,30,87\\nCharlie,22,92\";\nfile_put_contents('/tmp/data.csv', $csv);\n\n$handle = fopen('/tmp/data.csv', 'r');\n$header = fgetcsv($handle);  // ['Name', 'Age', 'Score']\n\nwhile (($row = fgetcsv($handle)) !== false) {\n    [$name, $age, $score] = $row;\n    echo sprintf(\"%-10s Age: %2d  Score: %d\\n\", $name, $age, $score);\n}\nfclose($handle);\n?>","output":"Alice      Age: 25  Score: 95\nBob        Age: 30  Score: 87\nCharlie    Age: 22  Score: 92","explanation":"<p><code>fgetcsv()</code> parses CSV rows automatically — handles quoted fields and delimiters.</p>"},
            {"title":"Directory Operations","code":"<?php\n$dir = '/tmp/php_test_dir';\n\nif (!is_dir($dir)) mkdir($dir, 0755, true);\n\nfile_put_contents(\"$dir/a.txt\", 'File A');\nfile_put_contents(\"$dir/b.txt\", 'File B');\n\necho \"Directory listing:\\n\";\nforeach (scandir($dir) as $file) {\n    if ($file === '.' || $file === '..') continue;\n    $size = filesize(\"$dir/$file\");\n    echo \"  $file ($size bytes)\\n\";\n}\n?>","output":"Directory listing:\n  a.txt (6 bytes)\n  b.txt (6 bytes)","explanation":"<p><code>scandir()</code> lists directory contents. <code>mkdir()</code> with <code>recursive=true</code> creates nested directories.</p>"},
        ],
        quiz=[
            {"q":"file_get_contents() returns:","options":["Array of lines","File handle","String of entire file","Boolean"],"answer":"String of entire file"},
            {"q":"FILE_APPEND flag does what?","options":["Overwrites file","Appends to existing content","Creates backup","Locks the file"],"answer":"Appends to existing content"},
        ],
    ),
    "php_json": make_topic(
        intro="<p><strong>JSON</strong> (JavaScript Object Notation) is the standard data format for APIs and web services. PHP provides <code>json_encode()</code> (PHP → JSON string) and <code>json_decode()</code> (JSON string → PHP). JSON is used for REST APIs, configuration files, AJAX communication, and data exchange between frontend and backend.</p>",
        subtopics=[{"title":"Encoding & Decoding","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>$data = ['name' => 'Alice', 'age' => 25, 'scores' => [85, 92, 78]];\n$json = json_encode($data, JSON_PRETTY_PRINT);\necho $json;\n\n$decoded = json_decode($json, true);  // true = assoc array\necho $decoded['name'];  // Alice</pre>"},{"title":"API Response","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>header('Content-Type: application/json');\necho json_encode([\n    'status' => 'success',\n    'data' => $result\n]);</pre>"}],
        key_concepts="<ul><li><code>json_encode($data)</code> converts PHP arrays/objects to JSON string.</li><li><code>json_decode($json, true)</code> — <code>true</code> returns associative array; <code>false</code> returns stdClass object.</li><li><code>JSON_PRETTY_PRINT</code> flag for readable output.</li><li>Always check <code>json_last_error()</code> after decode for parse errors.</li></ul>",
        examples=[
            {"title":"Encode & Decode","code":"<?php\n$student = [\n    'name' => 'Alice',\n    'age' => 20,\n    'courses' => ['Math', 'CS', 'Physics'],\n    'active' => true\n];\n\n$json = json_encode($student, JSON_PRETTY_PRINT);\necho \"JSON:\\n$json\\n\\n\";\n\n$decoded = json_decode($json, true);\necho \"Name: {$decoded['name']}\\n\";\necho \"Courses: \" . implode(', ', $decoded['courses']) . \"\\n\";\n?>","output":"JSON:\n{\n    \"name\": \"Alice\",\n    \"age\": 20,\n    \"courses\": [\n        \"Math\",\n        \"CS\",\n        \"Physics\"\n    ],\n    \"active\": true\n}\n\nName: Alice\nCourses: Math, CS, Physics","explanation":"<p><code>json_encode</code> with <code>JSON_PRETTY_PRINT</code> for readable output. <code>json_decode</code> with <code>true</code> returns arrays.</p>"},
            {"title":"REST API Response","code":"<?php\nfunction apiResponse(bool $success, $data, string $message = ''): string {\n    return json_encode([\n        'success' => $success,\n        'message' => $message,\n        'data' => $data,\n        'timestamp' => date('c')\n    ], JSON_PRETTY_PRINT);\n}\n\necho apiResponse(true, ['id' => 1, 'name' => 'Alice'], 'User found');\necho \"\\n\\n\";\necho apiResponse(false, null, 'User not found');\n?>","output":"{\n    \"success\": true,\n    \"message\": \"User found\",\n    \"data\": { \"id\": 1, \"name\": \"Alice\" },\n    \"timestamp\": \"2024-01-15T10:30:00+00:00\"\n}\n\n{\n    \"success\": false,\n    \"message\": \"User not found\",\n    \"data\": null,\n    \"timestamp\": \"2024-01-15T10:30:00+00:00\"\n}","explanation":"<p>Standard API response structure: success flag, message, data, and timestamp — used across all modern REST APIs.</p>"},
            {"title":"Reading JSON File","code":"<?php\n$json_data = '{\"users\":[{\"name\":\"Alice\",\"age\":25},{\"name\":\"Bob\",\"age\":30},{\"name\":\"Charlie\",\"age\":22}]}';\n\n$data = json_decode($json_data, true);\nif (json_last_error() !== JSON_ERROR_NONE) {\n    echo 'JSON Error: ' . json_last_error_msg();\n    exit;\n}\n\necho \"Users:\\n\";\nforeach ($data['users'] as $user) {\n    echo \"  {$user['name']} (age {$user['age']})\\n\";\n}\n\n$avg_age = array_sum(array_column($data['users'], 'age')) / count($data['users']);\necho sprintf(\"Average age: %.1f\\n\", $avg_age);\n?>","output":"Users:\n  Alice (age 25)\n  Bob (age 30)\n  Charlie (age 22)\nAverage age: 25.7","explanation":"<p>Always check <code>json_last_error()</code> after parsing — invalid JSON silently returns null without this check.</p>"},
        ],
        quiz=[
            {"q":"json_decode($json, true) returns:","options":["stdClass object","Associative array","Indexed array","String"],"answer":"Associative array"},
            {"q":"Which flag makes json_encode output readable?","options":["JSON_FORMAT","JSON_INDENT","JSON_PRETTY_PRINT","JSON_READABLE"],"answer":"JSON_PRETTY_PRINT"},
        ],
    ),
    "php_advanced": make_topic(
        intro="<p>Advanced PHP covers <strong>namespaces</strong>, <strong>Composer</strong> (dependency management), <strong>enums</strong> (PHP 8.1), <strong>fibers</strong> (PHP 8.1, lightweight concurrency), <strong>attributes</strong> (PHP 8.0, annotations), and <strong>named arguments</strong>. Modern PHP (8.x) is a dramatically different language from PHP 5 — type-safe, performant, and feature-rich. Understanding these features is essential for working with Laravel, Symfony, and modern PHP codebases.</p>",
        subtopics=[{"title":"Namespaces & Autoloading","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>// src/Models/User.php\nnamespace App\\Models;\n\nclass User {\n    public function __construct(public string $name) {}\n}\n\n// Usage\nuse App\\Models\\User;\n$u = new User('Alice');</pre>"},{"title":"Enums (PHP 8.1)","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>enum Status: string {\n    case Active = 'active';\n    case Inactive = 'inactive';\n    case Pending = 'pending';\n}\n\n$s = Status::Active;\necho $s->value;  // 'active'\necho $s->name;   // 'Active'</pre>"}],
        key_concepts="<ul><li>Namespaces prevent class name collisions: <code>App\\Models\\User</code> vs <code>Vendor\\Models\\User</code>.</li><li>Composer: PHP's package manager. <code>composer require package</code>, autoloading via <code>vendor/autoload.php</code>.</li><li>Enums (PHP 8.1): type-safe constants with methods. Backed enums have values.</li><li>Attributes (PHP 8.0): metadata annotations — <code>#[Route('/api')]</code> replaces docblock annotations.</li></ul>",
        examples=[
            {"title":"Enums with Methods","code":"<?php\nenum Color: string {\n    case Red = '#FF0000';\n    case Green = '#00FF00';\n    case Blue = '#0000FF';\n    \n    public function label(): string {\n        return match($this) {\n            self::Red => 'Red Color',\n            self::Green => 'Green Color',\n            self::Blue => 'Blue Color',\n        };\n    }\n}\n\n$color = Color::Blue;\necho \"Name: {$color->name}\\n\";\necho \"Value: {$color->value}\\n\";\necho \"Label: {$color->label()}\\n\";\n\n// From value\n$fromStr = Color::from('#FF0000');\necho \"From string: {$fromStr->name}\\n\";\n?>","output":"Name: Blue\nValue: #0000FF\nLabel: Blue Color\nFrom string: Red","explanation":"<p>PHP 8.1 enums are first-class types with values and methods — replacing const arrays and magic strings.</p>"},
            {"title":"Readonly Properties (PHP 8.1)","code":"<?php\nclass Point {\n    public function __construct(\n        public readonly float $x,\n        public readonly float $y\n    ) {}\n    \n    public function distanceTo(Point $other): float {\n        return sqrt(($this->x - $other->x)**2 + ($this->y - $other->y)**2);\n    }\n}\n\n$a = new Point(0, 0);\n$b = new Point(3, 4);\necho \"({$a->x}, {$a->y}) to ({$b->x}, {$b->y})\\n\";\necho \"Distance: \" . number_format($a->distanceTo($b), 2) . \"\\n\";\n\n// $a->x = 5;  // Error! readonly property\n?>","output":"(0, 0) to (3, 4)\nDistance: 5.00","explanation":"<p><code>readonly</code> properties can be set once (in constructor) and never changed — enforcing immutability.</p>"},
            {"title":"First-Class Callable Syntax","code":"<?php\n$numbers = [3, 1, 4, 1, 5, 9, 2, 6];\n\n// PHP 8.1: First-class callable syntax\n$sorted = $numbers;\nsort($sorted);\n\n$mapped = array_map(strtoupper(...), ['hello', 'world']);\n\necho \"Original: \" . implode(', ', $numbers) . \"\\n\";\necho \"Sorted: \" . implode(', ', $sorted) . \"\\n\";\necho \"Upper: \" . implode(', ', $mapped) . \"\\n\";\n\n// Named arguments with built-in functions\n$trimmed = array_map(\n    callback: fn($s) => trim($s),\n    array: ['  hello  ', '  world  ']\n);\necho \"Trimmed: \" . implode(', ', $trimmed) . \"\\n\";\n?>","output":"Original: 3, 1, 4, 1, 5, 9, 2, 6\nSorted: 1, 1, 2, 3, 4, 5, 6, 9\nUpper: HELLO, WORLD\nTrimmed: hello, world","explanation":"<p><code>function_name(...)</code> creates a first-class callable — cleaner than <code>'function_name'</code> strings.</p>"},
        ],
        quiz=[
            {"q":"PHP's package manager is:","options":["npm","pip","Composer","Maven"],"answer":"Composer"},
            {"q":"Enums were introduced in:","options":["PHP 7.4","PHP 8.0","PHP 8.1","PHP 8.2"],"answer":"PHP 8.1"},
        ],
    ),
    "php_interview": make_topic(
        intro="<p>PHP interview questions test: language fundamentals (<code>==</code> vs <code>===</code>, superglobals, type juggling), OOP (traits, interfaces, abstract classes), modern PHP features (PHP 8 match, enums, readonly, named args), security (SQL injection, XSS, CSRF prevention), and framework knowledge (Laravel, Symfony). Companies using PHP expect knowledge of Composer, PSR standards, and RESTful API design.</p>",
        subtopics=[{"title":"Common PHP Interview Questions","content":"<ul><li><strong>Q: Difference between == and ===?</strong><br>A: == compares values with type juggling (0 == false is true). === compares value AND type (0 === false is false). Always use ===.</li><li><strong>Q: What are traits?</strong><br>A: Reusable code blocks included in classes with 'use'. Solves single-inheritance limitation without interface implementation overhead.</li><li><strong>Q: How do you prevent SQL injection?</strong><br>A: Use PDO prepared statements with parameterized queries. Never concatenate user input into SQL strings.</li><li><strong>Q: What is Composer?</strong><br>A: PHP's dependency manager. Manages packages, autoloading (PSR-4), and version constraints via composer.json.</li></ul>"},{"title":"Security Questions","content":"<ul><li>XSS prevention: <code>htmlspecialchars()</code> on all user output</li><li>SQL injection: PDO prepared statements</li><li>CSRF: token in forms, validate on submit</li><li>Password hashing: <code>password_hash()</code> + <code>password_verify()</code></li><li>File upload: validate MIME type, size, extension</li></ul>"}],
        key_concepts="<ul><li>Know PSR standards: PSR-4 (autoloading), PSR-7 (HTTP messages), PSR-12 (coding style).</li><li>Know Laravel basics: routes, controllers, Eloquent ORM, Blade templates, middleware.</li><li>Understand PHP's request lifecycle: client → web server → PHP-FPM → response.</li><li>Know the difference between <code>include</code> (warning) and <code>require</code> (fatal error).</li></ul>",
        examples=[
            {"title":"Password Hashing (Secure)","code":"<?php\n$password = 'MySecretPass123';\n\n// Hash (store this in database)\n$hash = password_hash($password, PASSWORD_DEFAULT);\necho \"Hash: $hash\\n\";\necho \"Length: \" . strlen($hash) . \"\\n\";\n\n// Verify (during login)\n$is_valid = password_verify('MySecretPass123', $hash);\necho \"Valid password: \" . ($is_valid ? 'Yes' : 'No') . \"\\n\";\n\n$is_wrong = password_verify('WrongPassword', $hash);\necho \"Wrong password: \" . ($is_wrong ? 'Yes' : 'No') . \"\\n\";\n?>","output":"Hash: $2y$10$xxxxxxxxxxxxxxxxxxxxxxxxxxxxx\nLength: 60\nValid password: Yes\nWrong password: No","explanation":"<p><code>password_hash()</code> uses bcrypt by default — automatically salted, slow (intentionally), secure. Never use md5/sha1 for passwords.</p>"},
            {"title":"Type Juggling Gotchas","code":"<?php\n$tests = [\n    ['0 == false', 0 == false],\n    ['\"\" == false', '' == false],\n    ['\"0\" == false', '0' == false],\n    ['null == false', null == false],\n    ['0 == \"php\"', 0 == 'php'],      // true in PHP 7, false in PHP 8!\n    ['0 === false', 0 === false],\n    ['\"\" === false', '' === false],\n];\n\nforeach ($tests as [$expr, $result]) {\n    echo sprintf(\"%-15s %s\\n\", $expr, $result ? 'true' : 'false');\n}\n\necho \"\\nLesson: Always use ===\\n\";\n?>","output":"0 == false      true\n\"\" == false     true\n\"0\" == false    true\nnull == false   true\n0 == \"php\"      false\n0 === false     false\n\"\" === false    false\n\nLesson: Always use ===","explanation":"<p>PHP's loose comparison (<code>==</code>) has many surprising results. Strict comparison (<code>===</code>) prevents all these gotchas.</p>"},
            {"title":"Modern PHP Features","code":"<?php\n// Match expression (PHP 8)\n$status = 'active';\n$label = match($status) {\n    'active' => 'Active User',\n    'inactive' => 'Inactive User',\n    default => 'Unknown'\n};\necho \"$label\\n\";\n\n// Named arguments (PHP 8)\nfunction createTag(string $tag, string $content, string $class = ''): string {\n    $cls = $class ? \" class=\\\"$class\\\"\" : '';\n    return \"<$tag$cls>$content</$tag>\";\n}\n\necho createTag(content: 'Hello', tag: 'h1', class: 'title') . \"\\n\";\n\n// Nullsafe operator (PHP 8)\nclass Config {\n    public ?array $db = null;\n    public function get(string $key): ?string {\n        return $this->db[$key] ?? null;\n    }\n}\n\n$config = new Config();\necho $config?->get('host') ?? 'No host configured';\necho \"\\n\";\n?>","output":"Active User\n<h1 class=\"title\">Hello</h1>\nNo host configured","explanation":"<p>PHP 8 features make code safer and more readable — match, named args, and nullsafe operator.</p>"},
        ],
        quiz=[
            {"q":"password_hash() uses which algorithm by default?","options":["MD5","SHA-256","bcrypt","AES"],"answer":"bcrypt"},
            {"q":"In PHP 8, 0 == 'php' returns:","options":["true (like PHP 7)","false (changed in PHP 8)","Error","null"],"answer":"false (changed in PHP 8)"},
        ],
    ),
}

def load_data():
    with open(FILEPATH, 'r', encoding='utf-8') as f:
        content = f.read()
    prefix = 'window.tracksData = '
    idx = content.find(prefix)
    raw_json = content[idx + len(prefix):]
    suffix = ''
    if raw_json.strip().endswith(';'):
        raw_json = raw_json.strip()[:-1]
        suffix = ';'
    return content[:idx + len(prefix)], json.loads(raw_json), suffix

def save_data(pc, data, suffix):
    with open(FILEPATH, 'w', encoding='utf-8') as f:
        f.write(pc)
        f.write(json.dumps(data, ensure_ascii=False, separators=(',', ':')))
        f.write(suffix)

def apply_fixes(data, lang_key, fixes):
    fixed = 0
    for tk, nc in fixes.items():
        if tk in data.get(lang_key, {}).get('content', {}):
            existing = data[lang_key]['content'][tk]
            nc['title'] = existing.get('title', tk)
            nc['phase'] = existing.get('phase', 1)
            data[lang_key]['content'][tk] = nc
            fixed += 1
            print('  OK %s/%s' % (lang_key, tk))
        else:
            print('  MISS %s/%s' % (lang_key, tk))
    return fixed

if __name__ == '__main__':
    print('Loading tracks_data.js...')
    pc, data, suffix = load_data()
    total = 0
    print('\n--- Fixing PHP ---')
    total += apply_fixes(data, 'php', PHP_FIXES)
    print('\nSaving %d fixes...' % total)
    save_data(pc, data, suffix)
    print('Done!')
