"""
Batch: C (18 topics) + C# (18 topics) — full content with 3+ examples each
"""
import json, os
FILEPATH = os.path.join(os.path.dirname(__file__), '..', 'core', 'static', 'tracks_data.js')

def make_topic(intro, subtopics, key_concepts, examples, quiz, hands_on=None, problems=None):
    s = {"introduction": intro, "subtopics": subtopics, "key_concepts": key_concepts, "examples": examples}
    return {"structured": s, "concept_quiz": quiz, "hands_on": hands_on or {"title":"Try it!","description":"Practice the concept above.","hint":"Use the examples as a guide.","code":""}, "problem_solving": problems or []}

C_FIXES = {
    "c_basics": make_topic(
        intro="<p><strong>C</strong> is a general-purpose, procedural programming language created by Dennis Ritchie at Bell Labs in 1972. C is the foundation of modern computing — the Linux kernel, Windows OS, Python interpreter, and most embedded systems are written in C. It provides low-level access to memory through pointers, minimal runtime overhead, and compiles to highly efficient machine code. C is the language of systems programming, operating systems, compilers, and hardware-level software.</p>",
        subtopics=[
            {"title":"Program Structure","content":"<p>Every C program starts with <code>#include</code> directives for headers, then defines functions. The <code>main()</code> function is the entry point. C uses <code>{}</code> for blocks and <code>;</code> to end statements.</p><pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>#include &lt;stdio.h&gt;\n\nint main() {\n    printf(\"Hello, World!\\n\");\n    return 0;  // 0 = success\n}</pre>"},
            {"title":"Compilation Process","content":"<p>C is a compiled language. The <strong>preprocessor</strong> handles <code>#include</code>/<code>#define</code>, the <strong>compiler</strong> converts C to assembly, the <strong>assembler</strong> produces object code, and the <strong>linker</strong> combines everything into an executable.</p><pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>gcc hello.c -o hello   # compile\n./hello                # run</pre>"},
            {"title":"Data Types","content":"<p>C has basic data types: <code>int</code> (integer), <code>float</code>/<code>double</code> (floating-point), <code>char</code> (single character). Use <code>sizeof()</code> to check sizes.</p><pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>int age = 25;\nfloat pi = 3.14f;\nchar grade = 'A';\nprintf(\"int size: %zu bytes\\n\", sizeof(int)); // 4</pre>"},
        ],
        key_concepts="<ul><li>C is statically typed, compiled, and procedural.</li><li><code>main()</code> returns <code>int</code> — 0 means success, non-zero means error.</li><li><code>printf()</code> uses format specifiers: <code>%d</code> (int), <code>%f</code> (float), <code>%c</code> (char), <code>%s</code> (string).</li><li>Header files (<code>.h</code>) declare functions; source files (<code>.c</code>) define them.</li><li>C has no built-in string type — strings are <code>char</code> arrays terminated by <code>'\\0'</code>.</li></ul>",
        examples=[
            {"title":"Hello World","code":"#include <stdio.h>\n\nint main() {\n    printf(\"Hello, World!\\n\");\n    return 0;\n}","output":"Hello, World!","explanation":"<p><code>#include &lt;stdio.h&gt;</code> includes the Standard I/O library. <code>printf</code> prints formatted output. <code>\\n</code> adds a newline.</p>"},
            {"title":"Variables & Format Specifiers","code":"#include <stdio.h>\n\nint main() {\n    int age = 25;\n    float height = 5.9;\n    char initial = 'A';\n    \n    printf(\"Age: %d\\n\", age);\n    printf(\"Height: %.1f\\n\", height);\n    printf(\"Initial: %c\\n\", initial);\n    printf(\"Size of int: %zu bytes\\n\", sizeof(int));\n    return 0;\n}","output":"Age: 25\nHeight: 5.9\nInitial: A\nSize of int: 4 bytes","explanation":"<p>Format specifiers tell <code>printf</code> how to display each variable. <code>%.1f</code> limits to 1 decimal place.</p>"},
            {"title":"User Input with scanf","code":"#include <stdio.h>\n\nint main() {\n    int num;\n    printf(\"Enter a number: \");\n    scanf(\"%d\", &num);\n    printf(\"You entered: %d\\n\", num);\n    printf(\"Doubled: %d\\n\", num * 2);\n    return 0;\n}","output":"Enter a number: 7\nYou entered: 7\nDoubled: 14","explanation":"<p><code>scanf</code> reads input. The <code>&</code> (address-of) operator passes the memory address where the value should be stored.</p>"},
        ],
        quiz=[
            {"q":"What is the entry point of a C program?","options":["start()","init()","main()","run()"],"answer":"main()"},
            {"q":"Which format specifier prints an integer?","options":["%f","%d","%s","%c"],"answer":"%d"},
            {"q":"What does the & operator do in scanf?","options":["Logical AND","Gets the address of a variable","Bitwise AND","Dereferences a pointer"],"answer":"Gets the address of a variable"},
        ],
    ),
    "c_variables": make_topic(
        intro="<p><strong>Variables</strong> in C are named memory locations that store data. Every variable must be declared with a <strong>type</strong> before use. C provides several fundamental types: integers (<code>int</code>, <code>short</code>, <code>long</code>, <code>long long</code>), floating-point (<code>float</code>, <code>double</code>), characters (<code>char</code>), and <code>void</code>. Variables can be modified with <code>unsigned</code> (non-negative only), <code>const</code> (read-only), and <code>static</code> (persistent across function calls). Understanding variable scope, storage duration, and type sizes is critical for writing correct C code.</p>",
        subtopics=[
            {"title":"Declaration & Initialization","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>int x;          // declaration (undefined value)\nint y = 10;     // declaration + initialization\nconst float PI = 3.14159f;  // constant\nunsigned int count = 0;     // can't be negative</pre>"},
            {"title":"Variable Scope","content":"<p><strong>Local variables</strong> exist only within their block <code>{}</code>. <strong>Global variables</strong> (declared outside functions) are accessible everywhere. <strong>Static local variables</strong> persist between function calls.</p>"},
            {"title":"Type Qualifiers","content":"<ul><li><code>const</code> — value cannot change after initialization</li><li><code>volatile</code> — value may change unexpectedly (hardware registers)</li><li><code>static</code> — local scope but persistent lifetime</li><li><code>extern</code> — declared in another file</li></ul>"},
        ],
        key_concepts="<ul><li><code>int</code> is typically 4 bytes (32 bits), range: -2B to +2B.</li><li><code>char</code> is 1 byte — can store ASCII characters or small integers (-128 to 127).</li><li><code>sizeof(type)</code> returns bytes. Sizes are platform-dependent.</li><li>Uninitialized variables contain garbage values — always initialize.</li><li>Type casting: <code>(float)x</code> converts <code>int x</code> to float.</li></ul>",
        examples=[
            {"title":"Data Types & Sizes","code":"#include <stdio.h>\n\nint main() {\n    printf(\"char:   %zu byte\\n\", sizeof(char));\n    printf(\"int:    %zu bytes\\n\", sizeof(int));\n    printf(\"float:  %zu bytes\\n\", sizeof(float));\n    printf(\"double: %zu bytes\\n\", sizeof(double));\n    printf(\"long:   %zu bytes\\n\", sizeof(long));\n    return 0;\n}","output":"char:   1 byte\nint:    4 bytes\nfloat:  4 bytes\ndouble: 8 bytes\nlong:   8 bytes","explanation":"<p><code>sizeof</code> shows the memory footprint of each type — essential for understanding memory usage and limits.</p>"},
            {"title":"Constants & Type Casting","code":"#include <stdio.h>\n\nint main() {\n    const float PI = 3.14159f;\n    int radius = 7;\n    float area = PI * radius * radius;\n    \n    printf(\"Radius: %d\\n\", radius);\n    printf(\"Area: %.2f\\n\", area);\n    \n    // Integer division vs float division\n    printf(\"5/2 = %d\\n\", 5/2);           // 2 (truncated)\n    printf(\"5/2 = %.1f\\n\", 5.0/2);       // 2.5\n    printf(\"5/2 = %.1f\\n\", (float)5/2);  // 2.5 (cast)\n    return 0;\n}","output":"Radius: 7\nArea: 153.94\n5/2 = 2\n5/2 = 2.5\n5/2 = 2.5","explanation":"<p>Integer division truncates — cast one operand to <code>float</code> to get a decimal result. <code>const</code> makes PI read-only.</p>"},
            {"title":"Static Variable Demo","code":"#include <stdio.h>\n\nvoid counter() {\n    static int count = 0;  // persists between calls\n    count++;\n    printf(\"Called %d times\\n\", count);\n}\n\nint main() {\n    counter();  // 1\n    counter();  // 2\n    counter();  // 3\n    return 0;\n}","output":"Called 1 times\nCalled 2 times\nCalled 3 times","explanation":"<p><code>static</code> local variables retain their value between function calls — initialized only once.</p>"},
        ],
        quiz=[
            {"q":"What value does an uninitialized local variable contain in C?","options":["0","NULL","Garbage/undefined","Empty string"],"answer":"Garbage/undefined"},
            {"q":"Which keyword makes a variable read-only?","options":["static","final","const","readonly"],"answer":"const"},
        ],
    ),
    "c_operators": make_topic(
        intro="<p><strong>Operators</strong> in C perform operations on operands — arithmetic, comparison, logical, bitwise, and assignment. C has a rich set of operators with well-defined <strong>precedence</strong> and <strong>associativity</strong> rules. Understanding these is essential to avoid bugs, especially with increment/decrement (<code>++</code>/<code>--</code>), the ternary operator (<code>?:</code>), and bitwise operators used in systems and embedded programming.</p>",
        subtopics=[
            {"title":"Arithmetic & Assignment Operators","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>int a = 10, b = 3;\nprintf(\"%d\\n\", a + b);   // 13\nprintf(\"%d\\n\", a / b);   // 3 (integer division)\nprintf(\"%d\\n\", a % b);   // 1 (remainder)\n\na += 5;  // a = a + 5 = 15\na *= 2;  // a = a * 2 = 30</pre>"},
            {"title":"Comparison & Logical Operators","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>// Comparison: ==, !=, <, >, <=, >=\n// Logical: && (AND), || (OR), ! (NOT)\n\nint age = 20;\nif (age >= 18 && age <= 65) {\n    printf(\"Working age\\n\");\n}</pre>"},
            {"title":"Increment, Decrement & Ternary","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>int x = 5;\nprintf(\"%d\\n\", x++);  // prints 5, then increments to 6\nprintf(\"%d\\n\", ++x);  // increments to 7, then prints 7\n\nint max = (a > b) ? a : b;  // ternary operator</pre>"},
        ],
        key_concepts="<ul><li><code>x++</code> (post-increment) uses the value first, then increments. <code>++x</code> (pre-increment) increments first.</li><li><code>&&</code> and <code>||</code> short-circuit: if left side determines the result, right side is not evaluated.</li><li>Integer division truncates: <code>7/2 = 3</code>, not 3.5.</li><li>Operator precedence: <code>* / %</code> before <code>+ -</code>. Use parentheses for clarity.</li></ul>",
        examples=[
            {"title":"Arithmetic Operations","code":"#include <stdio.h>\n\nint main() {\n    int a = 17, b = 5;\n    printf(\"a + b = %d\\n\", a + b);   // 22\n    printf(\"a - b = %d\\n\", a - b);   // 12\n    printf(\"a * b = %d\\n\", a * b);   // 85\n    printf(\"a / b = %d\\n\", a / b);   // 3\n    printf(\"a %% b = %d\\n\", a % b);  // 2\n    return 0;\n}","output":"a + b = 22\na - b = 12\na * b = 85\na / b = 3\na % b = 2","explanation":"<p><code>%</code> gives the remainder (modulo). <code>%%</code> is needed in printf to print a literal percent sign.</p>"},
            {"title":"Pre vs Post Increment","code":"#include <stdio.h>\n\nint main() {\n    int x = 10;\n    printf(\"x   = %d\\n\", x);     // 10\n    printf(\"x++ = %d\\n\", x++);   // 10 (use, then increment)\n    printf(\"x   = %d\\n\", x);     // 11\n    printf(\"++x = %d\\n\", ++x);   // 12 (increment, then use)\n    return 0;\n}","output":"x   = 10\nx++ = 10\nx   = 11\n++x = 12","explanation":"<p>Post-increment returns the current value then increments; pre-increment increments first. This distinction matters in loop conditions and expressions.</p>"},
            {"title":"Ternary Operator","code":"#include <stdio.h>\n\nint main() {\n    int a = 15, b = 20;\n    int max = (a > b) ? a : b;\n    printf(\"Max of %d and %d is %d\\n\", a, b, max);\n    \n    int num = -5;\n    printf(\"%d is %s\\n\", num, (num >= 0) ? \"positive\" : \"negative\");\n    return 0;\n}","output":"Max of 15 and 20 is 20\n-5 is negative","explanation":"<p>The ternary operator <code>condition ? value_if_true : value_if_false</code> is a concise inline alternative to if-else.</p>"},
        ],
        quiz=[
            {"q":"What does x++ do?","options":["Increments x then returns new value","Returns x then increments","Doubles x","Adds 1 to x and prints"],"answer":"Returns x then increments"},
            {"q":"What is 7 / 2 in C (integer division)?","options":["3.5","3","4","3.0"],"answer":"3"},
        ],
    ),
    "c_control": make_topic(
        intro="<p><strong>Control flow</strong> statements in C determine which code blocks execute and in what order. C provides <code>if</code>/<code>else if</code>/<code>else</code> for conditional branching, <code>switch</code> for multi-way branching on integer/char values, and the ternary operator for inline conditionals. These are fundamental to all programming logic — every non-trivial program makes decisions based on data.</p>",
        subtopics=[
            {"title":"if / else if / else","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>int score = 85;\nif (score >= 90) {\n    printf(\"Grade: A\\n\");\n} else if (score >= 80) {\n    printf(\"Grade: B\\n\");\n} else if (score >= 70) {\n    printf(\"Grade: C\\n\");\n} else {\n    printf(\"Grade: F\\n\");\n}</pre>"},
            {"title":"switch Statement","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>char grade = 'B';\nswitch (grade) {\n    case 'A': printf(\"Excellent\\n\"); break;\n    case 'B': printf(\"Good\\n\"); break;\n    case 'C': printf(\"Average\\n\"); break;\n    default:  printf(\"Unknown\\n\"); break;\n}</pre><p>Each <code>case</code> must end with <code>break;</code> — without it, execution falls through to the next case.</p>"},
            {"title":"Nested & Compound Conditions","content":"<p>Combine conditions with <code>&&</code> (AND), <code>||</code> (OR), and <code>!</code> (NOT). Nest if-else blocks for multi-level decisions, but prefer switch or early returns for readability.</p>"},
        ],
        key_concepts="<ul><li><code>switch</code> works with <code>int</code>, <code>char</code>, and enum types — not strings or floats.</li><li>Always include <code>break;</code> in switch cases to prevent fall-through.</li><li>In C, any non-zero value is truthy; 0 is falsy.</li><li><code>if (x = 5)</code> is an assignment (always true) — use <code>if (x == 5)</code> for comparison.</li></ul>",
        examples=[
            {"title":"Grade Calculator","code":"#include <stdio.h>\n\nint main() {\n    int score = 78;\n    char grade;\n    \n    if (score >= 90) grade = 'A';\n    else if (score >= 80) grade = 'B';\n    else if (score >= 70) grade = 'C';\n    else if (score >= 60) grade = 'D';\n    else grade = 'F';\n    \n    printf(\"Score: %d, Grade: %c\\n\", score, grade);\n    \n    if (grade == 'F')\n        printf(\"You need to retake the exam.\\n\");\n    else\n        printf(\"You passed!\\n\");\n    return 0;\n}","output":"Score: 78, Grade: C\nYou passed!","explanation":"<p>Chained if-else assigns a grade based on numeric score. The result is used in a second conditional check.</p>"},
            {"title":"Switch with Menu","code":"#include <stdio.h>\n\nint main() {\n    int choice = 2;\n    printf(\"Menu: 1=Add 2=Sub 3=Mul\\n\");\n    \n    int a = 10, b = 3;\n    switch (choice) {\n        case 1: printf(\"%d + %d = %d\\n\", a, b, a+b); break;\n        case 2: printf(\"%d - %d = %d\\n\", a, b, a-b); break;\n        case 3: printf(\"%d * %d = %d\\n\", a, b, a*b); break;\n        default: printf(\"Invalid choice\\n\"); break;\n    }\n    return 0;\n}","output":"Menu: 1=Add 2=Sub 3=Mul\n10 - 3 = 7","explanation":"<p>Switch-case is cleaner than multiple if-else for menu-driven programs with discrete integer choices.</p>"},
            {"title":"Leap Year Check","code":"#include <stdio.h>\n\nint main() {\n    int year = 2024;\n    \n    if ((year % 4 == 0 && year % 100 != 0) || year % 400 == 0)\n        printf(\"%d is a leap year\\n\", year);\n    else\n        printf(\"%d is not a leap year\\n\", year);\n    return 0;\n}","output":"2024 is a leap year","explanation":"<p>Compound conditions with <code>&&</code> and <code>||</code> implement the leap year rule: divisible by 4, except centuries unless also divisible by 400.</p>"},
        ],
        quiz=[
            {"q":"What happens if you forget 'break' in a switch case?","options":["Compile error","Falls through to next case","Program crashes","Returns to first case"],"answer":"Falls through to next case"},
            {"q":"In C, which value is considered 'false'?","options":["1","-1","0","Any non-null"],"answer":"0"},
        ],
    ),
    "c_loops": make_topic(
        intro="<p><strong>Loops</strong> in C repeat a block of code while a condition is true. C provides three loop structures: <code>for</code> (known iterations), <code>while</code> (condition-first), and <code>do-while</code> (body-first, guaranteed at least once). Loop control statements <code>break</code> (exit loop immediately) and <code>continue</code> (skip to next iteration) provide fine-grained control. Nested loops are common for working with 2D arrays and matrices.</p>",
        subtopics=[
            {"title":"for Loop","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>for (int i = 0; i < 5; i++) {\n    printf(\"%d \", i);  // 0 1 2 3 4\n}\n\n// Nested for (multiplication table)\nfor (int i = 1; i <= 3; i++) {\n    for (int j = 1; j <= 3; j++) {\n        printf(\"%d*%d=%d  \", i, j, i*j);\n    }\n    printf(\"\\n\");\n}</pre>"},
            {"title":"while & do-while","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>// while: checks condition FIRST\nint n = 5;\nwhile (n > 0) {\n    printf(\"%d \", n--);\n}\n// Output: 5 4 3 2 1\n\n// do-while: runs body FIRST, then checks\nint x = 0;\ndo {\n    printf(\"x = %d\\n\", x);\n    x++;\n} while (x < 3);</pre>"},
            {"title":"break & continue","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>for (int i = 0; i < 10; i++) {\n    if (i == 5) break;      // exit loop\n    if (i % 2 == 0) continue; // skip even numbers\n    printf(\"%d \", i);       // prints: 1 3\n}</pre>"},
        ],
        key_concepts="<ul><li><code>for(init; condition; update)</code> — all three parts optional. <code>for(;;)</code> is infinite loop.</li><li><code>while</code> may execute zero times; <code>do-while</code> always runs at least once.</li><li><code>break</code> exits the innermost loop only.</li><li>Infinite loops (<code>while(1)</code>) are common in embedded systems — use <code>break</code> to exit.</li></ul>",
        examples=[
            {"title":"Sum of Numbers","code":"#include <stdio.h>\n\nint main() {\n    int sum = 0;\n    for (int i = 1; i <= 100; i++) {\n        sum += i;\n    }\n    printf(\"Sum 1..100 = %d\\n\", sum);\n    return 0;\n}","output":"Sum 1..100 = 5050","explanation":"<p>Classic for-loop accumulation. Gauss's formula gives the same result: n*(n+1)/2 = 5050.</p>"},
            {"title":"Multiplication Table","code":"#include <stdio.h>\n\nint main() {\n    int n = 5;\n    for (int i = 1; i <= 10; i++) {\n        printf(\"%d x %d = %d\\n\", n, i, n * i);\n    }\n    return 0;\n}","output":"5 x 1 = 5\n5 x 2 = 10\n5 x 3 = 15\n...\n5 x 10 = 50","explanation":"<p>A straightforward for-loop printing the multiplication table for a given number.</p>"},
            {"title":"Fibonacci with while","code":"#include <stdio.h>\n\nint main() {\n    int a = 0, b = 1, temp;\n    int count = 10;\n    \n    printf(\"Fibonacci: \");\n    int i = 0;\n    while (i < count) {\n        printf(\"%d \", a);\n        temp = a + b;\n        a = b;\n        b = temp;\n        i++;\n    }\n    printf(\"\\n\");\n    return 0;\n}","output":"Fibonacci: 0 1 1 2 3 5 8 13 21 34","explanation":"<p>Each Fibonacci number is the sum of the two preceding ones. The while loop generates the first 10 terms.</p>"},
        ],
        quiz=[
            {"q":"Which loop always runs at least once?","options":["for","while","do-while","All of them"],"answer":"do-while"},
            {"q":"What does 'continue' do inside a loop?","options":["Exits the loop","Skips to the next iteration","Pauses execution","Restarts the loop"],"answer":"Skips to the next iteration"},
        ],
    ),
    "c_functions": make_topic(
        intro="<p>A <strong>function</strong> in C is a reusable block of code that performs a specific task. Functions promote code reuse, modularity, and readability. Every C program has at least one function — <code>main()</code>. Functions have a <strong>return type</strong>, a <strong>name</strong>, <strong>parameters</strong>, and a <strong>body</strong>. C uses <strong>pass-by-value</strong> — function parameters are copies. To modify the original variable, pass a <strong>pointer</strong>. Function <strong>prototypes</strong> (declarations) go at the top of the file so the compiler knows about functions before they're called.</p>",
        subtopics=[
            {"title":"Defining & Calling Functions","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>// Function prototype (declaration)\nint add(int a, int b);\n\nint main() {\n    int result = add(3, 4);\n    printf(\"%d\\n\", result);  // 7\n    return 0;\n}\n\n// Function definition\nint add(int a, int b) {\n    return a + b;\n}</pre>"},
            {"title":"Pass by Value vs Pass by Pointer","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>void swap(int *a, int *b) {\n    int temp = *a;\n    *a = *b;\n    *b = temp;\n}\n\nint x = 5, y = 10;\nswap(&x, &y);  // x=10, y=5 now</pre>"},
            {"title":"Recursion","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>int factorial(int n) {\n    if (n <= 1) return 1;         // base case\n    return n * factorial(n - 1);  // recursive call\n}\nprintf(\"%d\\n\", factorial(5));  // 120</pre>"},
        ],
        key_concepts="<ul><li><code>void</code> return type means the function returns nothing.</li><li>C is pass-by-value — use pointers to modify caller's variables.</li><li>Every recursive function needs a base case to avoid infinite recursion (stack overflow).</li><li>Function prototypes enable forward declaration — call functions before defining them.</li></ul>",
        examples=[
            {"title":"Max of Three Numbers","code":"#include <stdio.h>\n\nint max(int a, int b) {\n    return (a > b) ? a : b;\n}\n\nint max3(int a, int b, int c) {\n    return max(max(a, b), c);\n}\n\nint main() {\n    printf(\"Max: %d\\n\", max3(15, 42, 27));\n    return 0;\n}","output":"Max: 42","explanation":"<p>Function composition: <code>max3</code> reuses <code>max</code> to find the largest of three numbers.</p>"},
            {"title":"Swap with Pointers","code":"#include <stdio.h>\n\nvoid swap(int *a, int *b) {\n    int temp = *a;\n    *a = *b;\n    *b = temp;\n}\n\nint main() {\n    int x = 10, y = 20;\n    printf(\"Before: x=%d, y=%d\\n\", x, y);\n    swap(&x, &y);\n    printf(\"After:  x=%d, y=%d\\n\", x, y);\n    return 0;\n}","output":"Before: x=10, y=20\nAfter:  x=20, y=10","explanation":"<p>Passing addresses (<code>&x</code>) allows the function to modify the caller's variables through pointers.</p>"},
            {"title":"Factorial (Recursion)","code":"#include <stdio.h>\n\nint factorial(int n) {\n    if (n <= 1) return 1;\n    return n * factorial(n - 1);\n}\n\nint main() {\n    for (int i = 1; i <= 6; i++) {\n        printf(\"%d! = %d\\n\", i, factorial(i));\n    }\n    return 0;\n}","output":"1! = 1\n2! = 2\n3! = 6\n4! = 24\n5! = 120\n6! = 720","explanation":"<p>Each call multiplies n by the result of <code>factorial(n-1)</code> until reaching the base case (n<=1).</p>"},
        ],
        quiz=[
            {"q":"C passes arguments to functions by:","options":["Reference","Value (copies)","Name","Pointer always"],"answer":"Value (copies)"},
            {"q":"A function with 'void' return type:","options":["Returns NULL","Returns 0","Returns nothing","Cannot be called"],"answer":"Returns nothing"},
        ],
    ),
    "c_arrays": make_topic(
        intro="<p>An <strong>array</strong> in C is a fixed-size, contiguous block of memory storing elements of the same type. Arrays provide <strong>O(1) index-based access</strong> but have a fixed size declared at compile time. The array name acts as a pointer to the first element. C does <strong>not</strong> check array bounds — accessing out-of-bounds indices leads to undefined behaviour (crashes, security vulnerabilities). Multi-dimensional arrays (2D arrays) represent matrices and tables.</p>",
        subtopics=[
            {"title":"Declaration & Initialization","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>int nums[5] = {10, 20, 30, 40, 50};\nchar name[] = \"Hello\";  // sized automatically\nint matrix[2][3] = {{1,2,3}, {4,5,6}};\n\nprintf(\"%d\\n\", nums[0]);       // 10\nprintf(\"%c\\n\", name[1]);       // 'e'\nprintf(\"%d\\n\", matrix[1][2]);  // 6</pre>"},
            {"title":"Passing Arrays to Functions","content":"<p>Arrays decay to pointers when passed to functions. The function receives a pointer, not a copy — so modifications affect the original array. Always pass the size separately.</p><pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>void printArray(int arr[], int size) {\n    for (int i = 0; i < size; i++)\n        printf(\"%d \", arr[i]);\n}</pre>"},
        ],
        key_concepts="<ul><li>Array indices start at 0. An array of size n has valid indices 0 to n-1.</li><li><code>sizeof(arr)/sizeof(arr[0])</code> gives the number of elements (only in the declaring scope).</li><li>Arrays cannot be resized — use <code>malloc</code>/<code>realloc</code> for dynamic arrays.</li><li>Strings in C are <code>char</code> arrays ending with <code>'\\0'</code> (null terminator).</li></ul>",
        examples=[
            {"title":"Array Sum & Average","code":"#include <stdio.h>\n\nint main() {\n    int arr[] = {10, 25, 30, 45, 50};\n    int n = sizeof(arr) / sizeof(arr[0]);\n    int sum = 0;\n    \n    for (int i = 0; i < n; i++)\n        sum += arr[i];\n    \n    printf(\"Sum: %d\\n\", sum);\n    printf(\"Average: %.1f\\n\", (float)sum / n);\n    return 0;\n}","output":"Sum: 160\nAverage: 32.0","explanation":"<p><code>sizeof(arr)/sizeof(arr[0])</code> calculates element count. Cast to float for accurate average.</p>"},
            {"title":"Find Max Element","code":"#include <stdio.h>\n\nint findMax(int arr[], int n) {\n    int max = arr[0];\n    for (int i = 1; i < n; i++)\n        if (arr[i] > max) max = arr[i];\n    return max;\n}\n\nint main() {\n    int nums[] = {42, 17, 93, 55, 8};\n    printf(\"Max: %d\\n\", findMax(nums, 5));\n    return 0;\n}","output":"Max: 93","explanation":"<p>Linear scan for maximum — the array is passed as a pointer, so we must also pass its size.</p>"},
            {"title":"2D Array (Matrix)","code":"#include <stdio.h>\n\nint main() {\n    int matrix[3][3] = {\n        {1, 2, 3},\n        {4, 5, 6},\n        {7, 8, 9}\n    };\n    \n    printf(\"Matrix:\\n\");\n    for (int i = 0; i < 3; i++) {\n        for (int j = 0; j < 3; j++)\n            printf(\"%d \", matrix[i][j]);\n        printf(\"\\n\");\n    }\n    return 0;\n}","output":"Matrix:\n1 2 3\n4 5 6\n7 8 9","explanation":"<p>2D arrays are arrays of arrays — accessed with two indices: row and column.</p>"},
        ],
        quiz=[
            {"q":"Array indices in C start at:","options":["1","0","-1","Depends on compiler"],"answer":"0"},
            {"q":"When passing an array to a function, C passes:","options":["A copy of the array","A pointer to the first element","The array size","Nothing"],"answer":"A pointer to the first element"},
        ],
    ),
    "c_strings": make_topic(
        intro="<p><strong>Strings in C</strong> are arrays of characters terminated by a <strong>null character</strong> (<code>'\\0'</code>). Unlike languages with a built-in String type, C requires manual memory management for strings. The <code>&lt;string.h&gt;</code> library provides essential string functions: <code>strlen</code> (length), <code>strcpy</code> (copy), <code>strcat</code> (concatenate), <code>strcmp</code> (compare), and <code>strstr</code> (find substring). Buffer overflow from improper string handling is one of the most common and dangerous security vulnerabilities in C.</p>",
        subtopics=[
            {"title":"String Basics","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>char greeting[] = \"Hello\";  // auto-sized to 6 (includes \\0)\nchar name[20];               // buffer for up to 19 chars\nstrcpy(name, \"World\");\nprintf(\"%s %s\\n\", greeting, name);</pre>"},
            {"title":"String Functions (string.h)","content":"<ul><li><code>strlen(s)</code> — length (not counting <code>'\\0'</code>)</li><li><code>strcpy(dest, src)</code> — copy src to dest</li><li><code>strcat(dest, src)</code> — append src to dest</li><li><code>strcmp(s1, s2)</code> — compare: returns 0 if equal, <0 if s1<s2, >0 if s1>s2</li><li><code>strstr(haystack, needle)</code> — find substring</li></ul>"},
        ],
        key_concepts="<ul><li>Always allocate enough space: <code>char buf[100];</code> holds 99 chars + null terminator.</li><li>Use <code>strncpy</code>, <code>strncat</code> (with size limits) to prevent buffer overflows.</li><li><code>==</code> compares pointers, not string content — use <code>strcmp()</code> for string comparison.</li><li><code>fgets(buf, size, stdin)</code> is safer than <code>gets()</code> for input (gets is removed in C11).</li></ul>",
        examples=[
            {"title":"String Length & Copy","code":"#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char src[] = \"Hello, C!\";\n    char dest[50];\n    \n    strcpy(dest, src);\n    printf(\"Source: %s\\n\", src);\n    printf(\"Copy:   %s\\n\", dest);\n    printf(\"Length: %zu\\n\", strlen(dest));\n    return 0;\n}","output":"Source: Hello, C!\nCopy:   Hello, C!\nLength: 9","explanation":"<p><code>strcpy</code> copies the string including the null terminator. <code>strlen</code> returns 9 (excludes <code>'\\0'</code>).</p>"},
            {"title":"String Comparison","code":"#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char a[] = \"apple\";\n    char b[] = \"banana\";\n    \n    int result = strcmp(a, b);\n    if (result < 0)\n        printf(\"\\\"%s\\\" comes before \\\"%s\\\"\\n\", a, b);\n    else if (result > 0)\n        printf(\"\\\"%s\\\" comes after \\\"%s\\\"\\n\", a, b);\n    else\n        printf(\"Strings are equal\\n\");\n    return 0;\n}","output":"\"apple\" comes before \"banana\"","explanation":"<p><code>strcmp</code> returns negative if the first string is lexicographically less, 0 if equal, positive if greater.</p>"},
            {"title":"String Concatenation","code":"#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char sentence[100] = \"Hello\";\n    strcat(sentence, \", \");\n    strcat(sentence, \"World!\");\n    printf(\"%s\\n\", sentence);\n    printf(\"Length: %zu\\n\", strlen(sentence));\n    return 0;\n}","output":"Hello, World!\nLength: 13","explanation":"<p><code>strcat</code> appends to the end of the destination string. Ensure the buffer is large enough to prevent overflow.</p>"},
        ],
        quiz=[
            {"q":"How are strings terminated in C?","options":["With a newline","With a space","With a null character (\\0)","They have a length property"],"answer":"With a null character (\\0)"},
            {"q":"To compare two strings in C, use:","options":["==","equals()","strcmp()","compare()"],"answer":"strcmp()"},
        ],
    ),
    "c_pointers": make_topic(
        intro="<p><strong>Pointers</strong> are variables that store <strong>memory addresses</strong> — they 'point to' the location of another variable in memory. Pointers are C's superpower: they enable pass-by-reference, dynamic memory allocation, efficient array access, data structures (linked lists, trees), and hardware-level programming. The two key operators: <code>&</code> (address-of) gets a variable's address, and <code>*</code> (dereference) accesses the value at an address.</p>",
        subtopics=[
            {"title":"Pointer Basics","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>int x = 42;\nint *p = &x;  // p stores address of x\n\nprintf(\"Value: %d\\n\", x);    // 42\nprintf(\"Address: %p\\n\", &x); // 0x7ffeabc...\nprintf(\"Pointer: %p\\n\", p);  // same address\nprintf(\"Deref:  %d\\n\", *p);  // 42\n\n*p = 100;  // modify x through pointer\nprintf(\"x = %d\\n\", x);      // 100</pre>"},
            {"title":"Pointer Arithmetic","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>int arr[] = {10, 20, 30, 40, 50};\nint *p = arr;  // points to arr[0]\n\nprintf(\"%d\\n\", *p);       // 10\nprintf(\"%d\\n\", *(p+1));   // 20\nprintf(\"%d\\n\", *(p+2));   // 30\n// p+1 advances by sizeof(int) = 4 bytes</pre>"},
            {"title":"Pointers & Arrays","content":"<p>An array name is a constant pointer to its first element: <code>arr == &arr[0]</code>. This means <code>arr[i]</code> is equivalent to <code>*(arr + i)</code>.</p>"},
        ],
        key_concepts="<ul><li><code>&x</code> gives the address of x. <code>*p</code> gives the value at the address p holds.</li><li>Pointer arithmetic: <code>p+1</code> advances by the size of the pointed-to type (not 1 byte).</li><li><code>NULL</code> pointer — convention for 'points to nothing'. Always check before dereferencing.</li><li>Dangling pointer — points to freed memory. Set to NULL after <code>free()</code>.</li><li>Double pointer (<code>int **pp</code>) — a pointer to a pointer. Used in dynamic 2D arrays.</li></ul>",
        examples=[
            {"title":"Pointer Basics Demo","code":"#include <stdio.h>\n\nint main() {\n    int num = 42;\n    int *ptr = &num;\n    \n    printf(\"Value: %d\\n\", num);\n    printf(\"Address: %p\\n\", (void*)&num);\n    printf(\"Pointer value: %p\\n\", (void*)ptr);\n    printf(\"Dereferenced: %d\\n\", *ptr);\n    \n    *ptr = 99;  // modify num through pointer\n    printf(\"Modified: %d\\n\", num);\n    return 0;\n}","output":"Value: 42\nAddress: 0x7ffe...\nPointer value: 0x7ffe...\nDereferenced: 42\nModified: 99","explanation":"<p><code>*ptr = 99</code> writes to the address stored in ptr — effectively modifying <code>num</code> indirectly.</p>"},
            {"title":"Array Traversal with Pointers","code":"#include <stdio.h>\n\nint main() {\n    int arr[] = {10, 20, 30, 40, 50};\n    int *p = arr;\n    int n = 5;\n    \n    printf(\"Using pointer arithmetic:\\n\");\n    for (int i = 0; i < n; i++) {\n        printf(\"arr[%d] = %d (addr: %p)\\n\", i, *(p+i), (void*)(p+i));\n    }\n    return 0;\n}","output":"Using pointer arithmetic:\narr[0] = 10 (addr: 0x...)\narr[1] = 20 (addr: 0x...)\narr[2] = 30 (addr: 0x...)\narr[3] = 40 (addr: 0x...)\narr[4] = 50 (addr: 0x...)","explanation":"<p><code>*(p+i)</code> is equivalent to <code>arr[i]</code>. Notice addresses increment by 4 bytes (sizeof int).</p>"},
            {"title":"Swap via Pointers","code":"#include <stdio.h>\n\nvoid swap(int *a, int *b) {\n    int temp = *a;\n    *a = *b;\n    *b = temp;\n}\n\nint main() {\n    int x = 5, y = 10;\n    printf(\"Before: x=%d, y=%d\\n\", x, y);\n    swap(&x, &y);\n    printf(\"After:  x=%d, y=%d\\n\", x, y);\n    return 0;\n}","output":"Before: x=5, y=10\nAfter:  x=10, y=5","explanation":"<p>Without pointers, swap would only modify local copies. Pointers give the function access to the original variables.</p>"},
        ],
        quiz=[
            {"q":"What does * do in front of a pointer variable?","options":["Gets the address","Multiplies","Dereferences (gets the value at that address)","Declares a pointer"],"answer":"Dereferences (gets the value at that address)"},
            {"q":"What does & do in front of a variable?","options":["Bitwise AND","Gets the memory address","Logical AND","Creates a reference"],"answer":"Gets the memory address"},
        ],
    ),
    "c_memory": make_topic(
        intro="<p><strong>Dynamic memory management</strong> is at the heart of C programming. C gives you direct control over memory allocation and deallocation using <code>malloc()</code>, <code>calloc()</code>, <code>realloc()</code>, and <code>free()</code> from <code>&lt;stdlib.h&gt;</code>. This power enables flexible data structures (linked lists, trees, dynamic arrays) but demands responsibility — forgetting to <code>free()</code> causes <strong>memory leaks</strong>, and accessing freed memory causes <strong>use-after-free</strong> bugs (undefined behaviour, security vulnerabilities).</p>",
        subtopics=[
            {"title":"malloc, calloc, realloc, free","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>// malloc: allocate uninitialized memory\nint *arr = (int*)malloc(5 * sizeof(int));\n\n// calloc: allocate zero-initialized memory\nint *arr2 = (int*)calloc(5, sizeof(int));\n\n// realloc: resize allocated memory\narr = (int*)realloc(arr, 10 * sizeof(int));\n\nfree(arr);   // release memory\nfree(arr2);\narr = NULL;  // prevent dangling pointer</pre>"},
            {"title":"Memory Layout","content":"<p>A C program's memory has 4 regions: <strong>Stack</strong> (local variables, function calls — auto-managed), <strong>Heap</strong> (dynamic allocations via malloc — manually managed), <strong>Data</strong> (global/static variables), <strong>Code/Text</strong> (compiled instructions).</p>"},
        ],
        key_concepts="<ul><li>Always check if <code>malloc</code> returns <code>NULL</code> — allocation can fail.</li><li>Every <code>malloc</code> must have a matching <code>free</code> — no garbage collector in C.</li><li>Common errors: memory leak (forget to free), dangling pointer (use after free), double free.</li><li>Use <code>valgrind</code> to detect memory leaks and errors.</li></ul>",
        examples=[
            {"title":"Dynamic Array","code":"#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int n = 5;\n    int *arr = (int*)malloc(n * sizeof(int));\n    \n    if (arr == NULL) {\n        printf(\"Memory allocation failed!\\n\");\n        return 1;\n    }\n    \n    for (int i = 0; i < n; i++)\n        arr[i] = (i + 1) * 10;\n    \n    printf(\"Dynamic array: \");\n    for (int i = 0; i < n; i++)\n        printf(\"%d \", arr[i]);\n    printf(\"\\n\");\n    \n    free(arr);\n    arr = NULL;\n    return 0;\n}","output":"Dynamic array: 10 20 30 40 50","explanation":"<p><code>malloc</code> allocates heap memory. Always check for NULL and free when done.</p>"},
            {"title":"Resizing with realloc","code":"#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int *arr = (int*)malloc(3 * sizeof(int));\n    arr[0]=1; arr[1]=2; arr[2]=3;\n    \n    // Resize from 3 to 6 elements\n    arr = (int*)realloc(arr, 6 * sizeof(int));\n    arr[3]=4; arr[4]=5; arr[5]=6;\n    \n    for (int i = 0; i < 6; i++)\n        printf(\"%d \", arr[i]);\n    printf(\"\\n\");\n    \n    free(arr);\n    return 0;\n}","output":"1 2 3 4 5 6","explanation":"<p><code>realloc</code> grows (or shrinks) the allocated block, preserving existing data. May relocate to a new address.</p>"},
            {"title":"calloc vs malloc","code":"#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int *a = (int*)malloc(5 * sizeof(int));\n    int *b = (int*)calloc(5, sizeof(int));\n    \n    printf(\"malloc (uninitialized): \");\n    for (int i = 0; i < 5; i++) printf(\"%d \", a[i]);\n    \n    printf(\"\\ncalloc (zero-init):     \");\n    for (int i = 0; i < 5; i++) printf(\"%d \", b[i]);\n    printf(\"\\n\");\n    \n    free(a); free(b);\n    return 0;\n}","output":"malloc (uninitialized): [garbage values]\ncalloc (zero-init):     0 0 0 0 0","explanation":"<p><code>calloc</code> initializes all bytes to zero; <code>malloc</code> leaves memory uninitialized (contains old values from previous allocations).</p>"},
        ],
        quiz=[
            {"q":"What does calloc do differently from malloc?","options":["Allocates more memory","Initializes memory to zero","Is faster","Doesn't need free()"],"answer":"Initializes memory to zero"},
            {"q":"What happens if you forget to free() allocated memory?","options":["Nothing","Memory leak","Compile error","Crash"],"answer":"Memory leak"},
        ],
    ),
    "c_structures": make_topic(
        intro="<p>A <strong>struct</strong> (structure) in C is a user-defined data type that groups related variables of different types under a single name. Structures are C's version of classes (without methods or access control). They enable you to model real-world entities — a student has a name, age, and GPA; a point has x and y coordinates. Combined with pointers, structures build complex data structures: linked lists, trees, and graphs.</p>",
        subtopics=[
            {"title":"Defining & Using Structs","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>struct Student {\n    char name[50];\n    int age;\n    float gpa;\n};\n\nstruct Student s1 = {\"Alice\", 20, 3.8};\nprintf(\"%s, age %d, GPA %.1f\\n\", s1.name, s1.age, s1.gpa);</pre>"},
            {"title":"typedef — Type Aliases","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>typedef struct {\n    float x, y;\n} Point;\n\nPoint p = {3.0, 4.0};\nprintf(\"(%.0f, %.0f)\\n\", p.x, p.y); // (3, 4)</pre>"},
            {"title":"Pointers to Structs","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>struct Student *ptr = &s1;\nprintf(\"%s\\n\", ptr->name);  // -> operator for pointer access\nptr->age = 21;  // modify through pointer</pre>"},
        ],
        key_concepts="<ul><li>Access members with <code>.</code> (dot) for values, <code>-></code> (arrow) for pointers.</li><li><code>typedef</code> creates shorter names: avoid writing <code>struct</code> keyword every time.</li><li>Structs are passed by value (copies) — use pointers for efficiency.</li><li>Nested structs: a struct can contain another struct as a member.</li><li>Bit fields: <code>unsigned int flag : 1;</code> for compact memory usage.</li></ul>",
        examples=[
            {"title":"Student Record","code":"#include <stdio.h>\n#include <string.h>\n\ntypedef struct {\n    char name[50];\n    int age;\n    float gpa;\n} Student;\n\nvoid printStudent(Student s) {\n    printf(\"%s | Age: %d | GPA: %.2f\\n\", s.name, s.age, s.gpa);\n}\n\nint main() {\n    Student s1 = {\"Alice\", 20, 3.85};\n    Student s2;\n    strcpy(s2.name, \"Bob\");\n    s2.age = 22;\n    s2.gpa = 3.50;\n    \n    printStudent(s1);\n    printStudent(s2);\n    return 0;\n}","output":"Alice | Age: 20 | GPA: 3.85\nBob | Age: 22 | GPA: 3.50","explanation":"<p>Structs bundle related data. <code>typedef</code> lets us write <code>Student</code> instead of <code>struct Student</code>.</p>"},
            {"title":"Array of Structs","code":"#include <stdio.h>\n\ntypedef struct {\n    char name[30];\n    int score;\n} Player;\n\nint main() {\n    Player team[] = {\n        {\"Alice\", 95}, {\"Bob\", 87}, {\"Charlie\", 92}\n    };\n    int n = sizeof(team) / sizeof(team[0]);\n    \n    int best = 0;\n    for (int i = 1; i < n; i++)\n        if (team[i].score > team[best].score) best = i;\n    \n    printf(\"Winner: %s with score %d\\n\", team[best].name, team[best].score);\n    return 0;\n}","output":"Winner: Alice with score 95","explanation":"<p>An array of structs combined with a max-finding loop — a common pattern for database-like record processing.</p>"},
            {"title":"Distance Between Points","code":"#include <stdio.h>\n#include <math.h>\n\ntypedef struct { double x, y; } Point;\n\ndouble distance(Point a, Point b) {\n    return sqrt(pow(a.x-b.x, 2) + pow(a.y-b.y, 2));\n}\n\nint main() {\n    Point p1 = {0, 0};\n    Point p2 = {3, 4};\n    printf(\"Distance: %.2f\\n\", distance(p1, p2));\n    return 0;\n}","output":"Distance: 5.00","explanation":"<p>Structs model geometric points cleanly. The distance function uses the Pythagorean theorem.</p>"},
        ],
        quiz=[
            {"q":"Which operator accesses a struct member through a pointer?","options":[".","::","->"," []"],"answer":"->"},
            {"q":"What does typedef do for structs?","options":["Creates a new struct","Creates a type alias (shorthand)","Allocates memory","Inherits from another struct"],"answer":"Creates a type alias (shorthand)"},
        ],
    ),
    "c_file_io": make_topic(
        intro="<p><strong>File I/O</strong> in C uses the <code>FILE*</code> pointer type and functions from <code>&lt;stdio.h&gt;</code>. Files are opened with <code>fopen()</code>, read/written with <code>fprintf</code>, <code>fscanf</code>, <code>fgets</code>, <code>fread</code>/<code>fwrite</code>, and closed with <code>fclose()</code>. Always check if <code>fopen</code> returns NULL (file not found, permissions) and always <code>fclose</code> to flush buffers and free resources. C file I/O operates in text mode ('r', 'w', 'a') or binary mode ('rb', 'wb').</p>",
        subtopics=[
            {"title":"Opening & Closing Files","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>FILE *fp = fopen(\"data.txt\", \"w\"); // write mode\nif (fp == NULL) {\n    perror(\"Error opening file\");\n    return 1;\n}\nfprintf(fp, \"Hello, File!\\n\");\nfclose(fp);</pre>"},
            {"title":"File Modes","content":"<ul><li><code>\"r\"</code> — read (file must exist)</li><li><code>\"w\"</code> — write (creates/truncates)</li><li><code>\"a\"</code> — append (creates if needed)</li><li><code>\"r+\"</code> — read+write</li><li><code>\"rb\"</code>/<code>\"wb\"</code> — binary mode</li></ul>"},
        ],
        key_concepts="<ul><li>Always check <code>fopen</code> return value — NULL means failure.</li><li>Always <code>fclose</code> — unflushed data may be lost.</li><li><code>fgets</code> reads a line (safer than <code>fscanf</code> for strings).</li><li><code>feof(fp)</code> checks end-of-file; <code>ferror(fp)</code> checks for errors.</li></ul>",
        examples=[
            {"title":"Write to File","code":"#include <stdio.h>\n\nint main() {\n    FILE *fp = fopen(\"test.txt\", \"w\");\n    if (!fp) { perror(\"fopen\"); return 1; }\n    \n    fprintf(fp, \"Name: Alice\\n\");\n    fprintf(fp, \"Score: %d\\n\", 95);\n    fclose(fp);\n    printf(\"File written successfully\\n\");\n    return 0;\n}","output":"File written successfully","explanation":"<p><code>fprintf</code> works like <code>printf</code> but writes to a file instead of the console.</p>"},
            {"title":"Read from File","code":"#include <stdio.h>\n\nint main() {\n    FILE *fp = fopen(\"test.txt\", \"r\");\n    if (!fp) { perror(\"fopen\"); return 1; }\n    \n    char line[100];\n    while (fgets(line, sizeof(line), fp)) {\n        printf(\"Read: %s\", line);\n    }\n    fclose(fp);\n    return 0;\n}","output":"Read: Name: Alice\nRead: Score: 95","explanation":"<p><code>fgets</code> reads one line at a time. The loop continues until end-of-file (fgets returns NULL).</p>"},
            {"title":"Copy File","code":"#include <stdio.h>\n\nint main() {\n    FILE *src = fopen(\"test.txt\", \"r\");\n    FILE *dst = fopen(\"copy.txt\", \"w\");\n    if (!src || !dst) { perror(\"fopen\"); return 1; }\n    \n    char ch;\n    while ((ch = fgetc(src)) != EOF)\n        fputc(ch, dst);\n    \n    fclose(src);\n    fclose(dst);\n    printf(\"File copied successfully\\n\");\n    return 0;\n}","output":"File copied successfully","explanation":"<p><code>fgetc</code>/<code>fputc</code> copy one character at a time. For large files, use <code>fread</code>/<code>fwrite</code> with buffers.</p>"},
        ],
        quiz=[
            {"q":"What does fopen return if the file cannot be opened?","options":["0","EOF","-1","NULL"],"answer":"NULL"},
            {"q":"Which mode opens a file for appending?","options":["\"r\"","\"w\"","\"a\"","\"r+\""],"answer":"\"a\""},
        ],
    ),
    "c_preprocessor": make_topic(
        intro="<p>The <strong>C preprocessor</strong> processes source code <em>before</em> compilation. It handles: <code>#include</code> (file inclusion), <code>#define</code> (macros and constants), <code>#ifdef</code>/<code>#ifndef</code> (conditional compilation), and <code>#pragma</code> (compiler instructions). Preprocessor directives start with <code>#</code> and are not C statements — they're text transformations. Understanding the preprocessor is essential for header file management, platform-specific compilation, and macro-based code generation.</p>",
        subtopics=[
            {"title":"#define Macros","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>#define PI 3.14159\n#define MAX(a,b) ((a) > (b) ? (a) : (b))\n#define SQUARE(x) ((x) * (x))\n\nprintf(\"%.2f\\n\", PI);           // 3.14\nprintf(\"%d\\n\", MAX(10, 20));    // 20\nprintf(\"%d\\n\", SQUARE(5));      // 25</pre>"},
            {"title":"Conditional Compilation","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>#ifdef DEBUG\n    printf(\"Debug: x = %d\\n\", x);\n#endif\n\n// Header guard pattern:\n#ifndef MYHEADER_H\n#define MYHEADER_H\n// declarations...\n#endif</pre>"},
        ],
        key_concepts="<ul><li>Macros are text substitution — no type checking. Wrap args in parentheses to avoid operator precedence bugs.</li><li>Header guards (<code>#ifndef</code>) prevent double-inclusion of header files.</li><li><code>#pragma once</code> is a modern alternative to header guards.</li><li>Predefined macros: <code>__FILE__</code>, <code>__LINE__</code>, <code>__DATE__</code>, <code>__TIME__</code>.</li></ul>",
        examples=[
            {"title":"Macros & Constants","code":"#include <stdio.h>\n\n#define PI 3.14159\n#define AREA(r) (PI * (r) * (r))\n#define MAX(a, b) ((a) > (b) ? (a) : (b))\n\nint main() {\n    printf(\"Area (r=5): %.2f\\n\", AREA(5));\n    printf(\"Max(10,20): %d\\n\", MAX(10, 20));\n    printf(\"File: %s, Line: %d\\n\", __FILE__, __LINE__);\n    return 0;\n}","output":"Area (r=5): 78.54\nMax(10,20): 20\nFile: macros.c, Line: 9","explanation":"<p>Macros perform compile-time text substitution — fast but without type safety. Always wrap macro parameters in parentheses.</p>"},
            {"title":"Conditional Compilation","code":"#include <stdio.h>\n\n#define DEBUG 1\n\nint main() {\n    int x = 42;\n    \n    #if DEBUG\n        printf(\"[DEBUG] x = %d\\n\", x);\n    #endif\n    \n    printf(\"Result: %d\\n\", x * 2);\n    return 0;\n}","output":"[DEBUG] x = 42\nResult: 84","explanation":"<p>Set <code>#define DEBUG 0</code> to remove all debug prints at compile time — zero runtime overhead.</p>"},
            {"title":"Header Guard Pattern","code":"// mymath.h\n#ifndef MYMATH_H\n#define MYMATH_H\n\nint add(int a, int b);\nint multiply(int a, int b);\n\n#endif // MYMATH_H\n\n// mymath.c\n#include \"mymath.h\"\nint add(int a, int b) { return a + b; }\nint multiply(int a, int b) { return a * b; }\n\n// main.c\n#include <stdio.h>\n#include \"mymath.h\"\n// Can include mymath.h multiple times safely","output":"Compiles without errors even with multiple includes","explanation":"<p>Header guards ensure the header's contents are processed only once per compilation unit, preventing duplicate declaration errors.</p>"},
        ],
        quiz=[
            {"q":"When does the preprocessor run?","options":["After compilation","Before compilation","At runtime","During linking"],"answer":"Before compilation"},
            {"q":"What prevents double-inclusion of header files?","options":["#include once","#pragma link","#ifndef / #define guards","extern keyword"],"answer":"#ifndef / #define guards"},
        ],
    ),
    "c_bitwise": make_topic(
        intro="<p><strong>Bitwise operators</strong> manipulate individual bits of integer values — the lowest level of data representation. They are essential in systems programming, embedded development, network protocols, cryptography, and performance optimization. C provides: AND (<code>&</code>), OR (<code>|</code>), XOR (<code>^</code>), NOT (<code>~</code>), left shift (<code>&lt;&lt;</code>), and right shift (<code>&gt;&gt;</code>). Understanding binary representation and bit manipulation is fundamental for any systems or embedded C developer.</p>",
        subtopics=[
            {"title":"Bitwise Operators","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>// a = 5  →  0101\n// b = 3  →  0011\nint a = 5, b = 3;\nprintf(\"a & b = %d\\n\", a & b);   // 1 (0001) AND\nprintf(\"a | b = %d\\n\", a | b);   // 7 (0111) OR\nprintf(\"a ^ b = %d\\n\", a ^ b);   // 6 (0110) XOR\nprintf(\"~a = %d\\n\", ~a);         // -6 (NOT)\nprintf(\"a << 1 = %d\\n\", a << 1); // 10 (1010) left shift\nprintf(\"a >> 1 = %d\\n\", a >> 1); // 2 (0010) right shift</pre>"},
            {"title":"Bit Manipulation Tricks","content":"<ul><li>Check if even: <code>(n & 1) == 0</code></li><li>Multiply by 2: <code>n << 1</code></li><li>Divide by 2: <code>n >> 1</code></li><li>Set bit k: <code>n |= (1 << k)</code></li><li>Clear bit k: <code>n &= ~(1 << k)</code></li><li>Toggle bit k: <code>n ^= (1 << k)</code></li><li>Check bit k: <code>(n >> k) & 1</code></li></ul>"},
        ],
        key_concepts="<ul><li>Left shift by n = multiply by 2ⁿ. Right shift by n = divide by 2ⁿ.</li><li>XOR swap: <code>a ^= b; b ^= a; a ^= b;</code> — swaps without a temporary variable.</li><li>Bit masking: use AND with a mask to extract specific bits.</li><li>Embedded systems use bitwise ops for hardware register manipulation.</li></ul>",
        examples=[
            {"title":"Bitwise Operations","code":"#include <stdio.h>\n\nint main() {\n    unsigned int a = 12; // 1100\n    unsigned int b = 10; // 1010\n    \n    printf(\"a & b = %u\\n\", a & b);   // 8  (1000)\n    printf(\"a | b = %u\\n\", a | b);   // 14 (1110)\n    printf(\"a ^ b = %u\\n\", a ^ b);   // 6  (0110)\n    printf(\"a << 2 = %u\\n\", a << 2); // 48 (110000)\n    printf(\"a >> 2 = %u\\n\", a >> 2); // 3  (11)\n    return 0;\n}","output":"a & b = 8\na | b = 14\na ^ b = 6\na << 2 = 48\na >> 2 = 3","explanation":"<p>AND extracts common bits, OR combines, XOR finds differences. Shifts multiply/divide by powers of 2.</p>"},
            {"title":"Check Even/Odd with Bits","code":"#include <stdio.h>\n\nint main() {\n    for (int i = 1; i <= 6; i++) {\n        if (i & 1)\n            printf(\"%d is odd\\n\", i);\n        else\n            printf(\"%d is even\\n\", i);\n    }\n    return 0;\n}","output":"1 is odd\n2 is even\n3 is odd\n4 is even\n5 is odd\n6 is even","explanation":"<p>The least significant bit determines parity: <code>n & 1</code> is 1 for odd, 0 for even. Faster than <code>n % 2</code>.</p>"},
            {"title":"Count Set Bits","code":"#include <stdio.h>\n\nint countBits(unsigned int n) {\n    int count = 0;\n    while (n) {\n        count += n & 1;\n        n >>= 1;\n    }\n    return count;\n}\n\nint main() {\n    printf(\"Bits in 13: %d\\n\", countBits(13)); // 1101 -> 3\n    printf(\"Bits in 255: %d\\n\", countBits(255)); // 11111111 -> 8\n    return 0;\n}","output":"Bits in 13: 3\nBits in 255: 8","explanation":"<p>Check the last bit, shift right, repeat. Brian Kernighan's method (<code>n &= (n-1)</code>) is faster but this is more intuitive.</p>"},
        ],
        quiz=[
            {"q":"What does a << 2 do?","options":["Adds 2 to a","Multiplies a by 4","Divides a by 4","Subtracts 2"],"answer":"Multiplies a by 4"},
            {"q":"How to check if n is even using bitwise ops?","options":["n & 2 == 0","n ^ 1 == 0","n & 1 == 0","n | 1 == 0"],"answer":"n & 1 == 0"},
        ],
    ),
    "c_advanced": make_topic(
        intro="<p>Advanced C programming covers topics critical for professional systems development: <strong>function pointers</strong> (callbacks, plugin architectures), <strong>unions</strong> (shared memory), <strong>enums</strong> (named integer constants), <strong>void pointers</strong> (generic programming), <strong>variadic functions</strong>, and <strong>volatile</strong>/<strong>restrict</strong> qualifiers. These features are heavily used in operating system kernels, database engines, network stacks, and embedded firmware.</p>",
        subtopics=[
            {"title":"Function Pointers","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>int add(int a, int b) { return a + b; }\nint sub(int a, int b) { return a - b; }\n\nint (*op)(int, int);  // function pointer\nop = add;\nprintf(\"%d\\n\", op(5, 3));  // 8\nop = sub;\nprintf(\"%d\\n\", op(5, 3));  // 2</pre>"},
            {"title":"Enums & Unions","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>enum Color { RED, GREEN, BLUE };\nenum Color c = GREEN;\nprintf(\"%d\\n\", c);  // 1\n\nunion Data {\n    int i;\n    float f;\n    char c;\n};  // All members share the same memory</pre>"},
            {"title":"void Pointers (Generic)","content":"<p>A <code>void*</code> can point to any type — C's mechanism for generic programming. Must cast before dereferencing. Used by <code>malloc</code>, <code>qsort</code>, and generic data structures.</p>"},
        ],
        key_concepts="<ul><li>Function pointers enable callbacks, strategy pattern, and plugin systems in C.</li><li><code>qsort()</code> takes a function pointer comparator — the classic C generic sort.</li><li>Unions: all members share one memory location — size = largest member. Used for type-punning.</li><li>Enums provide named integer constants — better than <code>#define</code> for sets of related values.</li></ul>",
        examples=[
            {"title":"Callback with Function Pointer","code":"#include <stdio.h>\n\nint add(int a, int b) { return a + b; }\nint mul(int a, int b) { return a * b; }\n\nint apply(int x, int y, int (*func)(int, int)) {\n    return func(x, y);\n}\n\nint main() {\n    printf(\"add: %d\\n\", apply(3, 4, add));\n    printf(\"mul: %d\\n\", apply(3, 4, mul));\n    return 0;\n}","output":"add: 7\nmul: 12","explanation":"<p><code>apply</code> accepts any function matching the <code>(int, int) -> int</code> signature — this is C's version of higher-order functions.</p>"},
            {"title":"Generic Sort with qsort","code":"#include <stdio.h>\n#include <stdlib.h>\n\nint compare(const void *a, const void *b) {\n    return (*(int*)a - *(int*)b);\n}\n\nint main() {\n    int arr[] = {42, 17, 93, 55, 8};\n    int n = sizeof(arr) / sizeof(arr[0]);\n    \n    qsort(arr, n, sizeof(int), compare);\n    \n    for (int i = 0; i < n; i++)\n        printf(\"%d \", arr[i]);\n    printf(\"\\n\");\n    return 0;\n}","output":"8 17 42 55 93","explanation":"<p><code>qsort</code> uses void pointers and a function pointer comparator — C's standard generic sorting mechanism.</p>"},
            {"title":"Enum for State Machine","code":"#include <stdio.h>\n\ntypedef enum { IDLE, RUNNING, PAUSED, STOPPED } State;\n\nconst char* stateNames[] = {\"IDLE\", \"RUNNING\", \"PAUSED\", \"STOPPED\"};\n\nint main() {\n    State s = IDLE;\n    printf(\"State: %s\\n\", stateNames[s]);\n    s = RUNNING;\n    printf(\"State: %s\\n\", stateNames[s]);\n    s = STOPPED;\n    printf(\"State: %s\\n\", stateNames[s]);\n    return 0;\n}","output":"State: IDLE\nState: RUNNING\nState: STOPPED","explanation":"<p>Enums make state machines readable and type-safe — much clearer than raw integers.</p>"},
        ],
        quiz=[
            {"q":"A function pointer stores:","options":["A variable's value","The address of a function","A string","A struct member"],"answer":"The address of a function"},
            {"q":"In a union, all members:","options":["Have separate memory","Share the same memory location","Must be the same type","Are read-only"],"answer":"Share the same memory location"},
        ],
    ),
    "c_algorithms": make_topic(
        intro="<p>Implementing <strong>algorithms in C</strong> teaches both algorithmic thinking and low-level C mechanics: manual memory management, pointer manipulation, and efficient data handling. C's lack of built-in data structures (no lists, sets, or maps) means you build everything from scratch — deepening your understanding of how these structures work internally. This section covers essential algorithms implemented in pure C: searching, sorting, and recursion.</p>",
        subtopics=[
            {"title":"Binary Search","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>int binarySearch(int arr[], int n, int target) {\n    int lo = 0, hi = n - 1;\n    while (lo <= hi) {\n        int mid = lo + (hi - lo) / 2;\n        if (arr[mid] == target) return mid;\n        else if (arr[mid] < target) lo = mid + 1;\n        else hi = mid - 1;\n    }\n    return -1;  // not found\n}</pre>"},
            {"title":"Sorting Algorithms","content":"<p>Bubble Sort (O(n<sup>2</sup>)) for learning; qsort for production. Understanding how sorting works at the swap-and-compare level is foundational.</p>"},
        ],
        key_concepts="<ul><li>Binary search requires a sorted array — O(log n) vs linear search O(n).</li><li>Selection sort: find minimum, swap to front. O(n<sup>2</sup>) but simple and in-place.</li><li>Use <code>qsort()</code> from <code>&lt;stdlib.h&gt;</code> for production sorting — optimized by the C library.</li></ul>",
        examples=[
            {"title":"Binary Search","code":"#include <stdio.h>\n\nint binarySearch(int arr[], int n, int target) {\n    int lo = 0, hi = n - 1;\n    while (lo <= hi) {\n        int mid = lo + (hi - lo) / 2;\n        if (arr[mid] == target) return mid;\n        else if (arr[mid] < target) lo = mid + 1;\n        else hi = mid - 1;\n    }\n    return -1;\n}\n\nint main() {\n    int arr[] = {2, 5, 8, 12, 16, 23, 38, 56, 72, 91};\n    int n = 10;\n    int idx = binarySearch(arr, n, 23);\n    printf(\"Found 23 at index: %d\\n\", idx);\n    idx = binarySearch(arr, n, 50);\n    printf(\"Found 50 at index: %d\\n\", idx);\n    return 0;\n}","output":"Found 23 at index: 5\nFound 50 at index: -1","explanation":"<p>Binary search halves the search space each step — only 4 comparisons for 10 elements vs 10 for linear search.</p>"},
            {"title":"Bubble Sort","code":"#include <stdio.h>\n\nvoid bubbleSort(int arr[], int n) {\n    for (int i = 0; i < n-1; i++)\n        for (int j = 0; j < n-i-1; j++)\n            if (arr[j] > arr[j+1]) {\n                int temp = arr[j];\n                arr[j] = arr[j+1];\n                arr[j+1] = temp;\n            }\n}\n\nint main() {\n    int arr[] = {64, 34, 25, 12, 22, 11, 90};\n    int n = 7;\n    bubbleSort(arr, n);\n    for (int i = 0; i < n; i++)\n        printf(\"%d \", arr[i]);\n    printf(\"\\n\");\n    return 0;\n}","output":"11 12 22 25 34 64 90","explanation":"<p>Bubble sort compares adjacent elements and swaps if out of order. Simple but O(n<sup>2</sup>) — use <code>qsort</code> for real applications.</p>"},
            {"title":"Power (Recursive)","code":"#include <stdio.h>\n\ndouble power(double base, int exp) {\n    if (exp == 0) return 1;\n    if (exp < 0) return 1.0 / power(base, -exp);\n    double half = power(base, exp / 2);\n    if (exp % 2 == 0) return half * half;\n    return half * half * base;\n}\n\nint main() {\n    printf(\"2^10 = %.0f\\n\", power(2, 10));\n    printf(\"3^5  = %.0f\\n\", power(3, 5));\n    printf(\"2^-3 = %.4f\\n\", power(2, -3));\n    return 0;\n}","output":"2^10 = 1024\n3^5  = 243\n2^-3 = 0.1250","explanation":"<p>Fast exponentiation using divide-and-conquer: O(log n) multiplications instead of O(n).</p>"},
        ],
        quiz=[
            {"q":"Binary search requires the array to be:","options":["Unique","Sorted","Of even length","Dynamically allocated"],"answer":"Sorted"},
            {"q":"Time complexity of bubble sort:","options":["O(n)","O(n log n)","O(n^2)","O(log n)"],"answer":"O(n^2)"},
        ],
    ),
    "c_data_struct": make_topic(
        intro="<p>Building <strong>data structures from scratch in C</strong> is the ultimate exercise in understanding how software works at the lowest level. Without built-in lists, maps, or sets, C programmers construct <strong>linked lists</strong>, <strong>stacks</strong>, <strong>queues</strong>, and <strong>hash tables</strong> using structs and pointers. This is exactly how Python's lists, Java's ArrayLists, and JavaScript's objects are implemented internally — in C.</p>",
        subtopics=[
            {"title":"Linked List","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>typedef struct Node {\n    int data;\n    struct Node *next;\n} Node;\n\nNode* createNode(int data) {\n    Node *n = (Node*)malloc(sizeof(Node));\n    n->data = data;\n    n->next = NULL;\n    return n;\n}</pre>"},
            {"title":"Stack (Array-based)","content":"<pre style='background:#1e1e2f;color:#e2e8f0;padding:15px;border-radius:8px;'>typedef struct {\n    int items[100];\n    int top;\n} Stack;\n\nvoid push(Stack *s, int val) { s->items[++(s->top)] = val; }\nint pop(Stack *s) { return s->items[(s->top)--]; }\nint peek(Stack *s) { return s->items[s->top]; }</pre>"},
        ],
        key_concepts="<ul><li>Linked lists: O(1) insert/delete at head; O(n) search. Dynamic size.</li><li>Stack: LIFO. Push/pop at top. Array or linked list implementation.</li><li>Queue: FIFO. Enqueue at rear, dequeue from front.</li><li>Self-referential structs: <code>struct Node { int data; struct Node *next; };</code></li></ul>",
        examples=[
            {"title":"Linked List — Insert & Print","code":"#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct Node {\n    int data;\n    struct Node *next;\n} Node;\n\nvoid pushFront(Node **head, int data) {\n    Node *n = (Node*)malloc(sizeof(Node));\n    n->data = data;\n    n->next = *head;\n    *head = n;\n}\n\nvoid printList(Node *head) {\n    while (head) {\n        printf(\"%d -> \", head->data);\n        head = head->next;\n    }\n    printf(\"NULL\\n\");\n}\n\nint main() {\n    Node *head = NULL;\n    pushFront(&head, 30);\n    pushFront(&head, 20);\n    pushFront(&head, 10);\n    printList(head);\n    return 0;\n}","output":"10 -> 20 -> 30 -> NULL","explanation":"<p><code>pushFront</code> takes a double pointer (<code>Node **</code>) to modify the head pointer itself. New nodes are inserted at the front in O(1).</p>"},
            {"title":"Stack Implementation","code":"#include <stdio.h>\n\n#define MAX 100\n\ntypedef struct {\n    int items[MAX];\n    int top;\n} Stack;\n\nvoid init(Stack *s) { s->top = -1; }\nint isEmpty(Stack *s) { return s->top == -1; }\nvoid push(Stack *s, int val) { s->items[++(s->top)] = val; }\nint pop(Stack *s) { return s->items[(s->top)--]; }\n\nint main() {\n    Stack s;\n    init(&s);\n    push(&s, 10);\n    push(&s, 20);\n    push(&s, 30);\n    printf(\"Popped: %d\\n\", pop(&s));\n    printf(\"Popped: %d\\n\", pop(&s));\n    return 0;\n}","output":"Popped: 30\nPopped: 20","explanation":"<p>LIFO: last pushed (30) is popped first. The stack is implemented as an array with a top index.</p>"},
            {"title":"Queue with Circular Array","code":"#include <stdio.h>\n\n#define MAX 5\ntypedef struct {\n    int items[MAX];\n    int front, rear, count;\n} Queue;\n\nvoid init(Queue *q) { q->front=0; q->rear=-1; q->count=0; }\nvoid enqueue(Queue *q, int val) {\n    q->rear = (q->rear + 1) % MAX;\n    q->items[q->rear] = val;\n    q->count++;\n}\nint dequeue(Queue *q) {\n    int val = q->items[q->front];\n    q->front = (q->front + 1) % MAX;\n    q->count--;\n    return val;\n}\n\nint main() {\n    Queue q;\n    init(&q);\n    enqueue(&q, 10); enqueue(&q, 20); enqueue(&q, 30);\n    printf(\"Dequeue: %d\\n\", dequeue(&q));\n    printf(\"Dequeue: %d\\n\", dequeue(&q));\n    return 0;\n}","output":"Dequeue: 10\nDequeue: 20","explanation":"<p>FIFO: first enqueued (10) is dequeued first. Circular array wraps around with modulo to reuse space.</p>"},
        ],
        quiz=[
            {"q":"A self-referential struct in C contains:","options":["A function","A pointer to itself (same struct type)","A union","An enum"],"answer":"A pointer to itself (same struct type)"},
            {"q":"Stack follows which order?","options":["FIFO","LIFO","Random","Sorted"],"answer":"LIFO"},
        ],
    ),
    "c_interview": make_topic(
        intro="<p>C interview questions test deep understanding of memory management, pointers, low-level system concepts, and algorithmic thinking. Senior C developer interviews at companies like NVIDIA, Qualcomm, Intel, and embedded systems firms probe: pointer arithmetic, memory layout (stack vs heap), undefined behavior, volatile/restrict, function pointers, and manual data structure implementation. This section covers the most frequently asked C interview questions.</p>",
        subtopics=[
            {"title":"Core C Interview Questions","content":"<ul><li><strong>Q: What is undefined behavior?</strong><br>A: Code whose result is unpredictable per the C standard — e.g., buffer overflow, use-after-free, null pointer dereference. The compiler may optimize it away or crash.</li><li><strong>Q: What's the difference between stack and heap?</strong><br>A: Stack: auto-managed, local variables, fast, fixed size. Heap: manually managed (malloc/free), dynamic size, slower, fragmentation risk.</li><li><strong>Q: What is a memory leak?</strong><br>A: Allocated memory (malloc) that is never freed — accumulates over time, exhausts available memory.</li><li><strong>Q: sizeof(char) is always?</strong><br>A: 1 byte — by definition in the C standard.</li></ul>"},
            {"title":"Pointer Interview Questions","content":"<ul><li><strong>Q: Difference between <code>int *p</code>, <code>int **p</code>, <code>int (*p)[10]</code>?</strong><br>A: Pointer to int, pointer to pointer to int, pointer to array of 10 ints.</li><li><strong>Q: What is a dangling pointer?</strong><br>A: A pointer that references freed memory. Set to NULL after free() to prevent use.</li><li><strong>Q: What does volatile do?</strong><br>A: Tells the compiler the variable may change outside program control (hardware registers, ISRs) — prevents optimization.</li></ul>"},
        ],
        key_concepts="<ul><li>Know memory layout: code, data, BSS, heap, stack.</li><li>Understand pointer aliasing and strict aliasing rules.</li><li>Know common vulnerabilities: buffer overflow, format string attack, use-after-free.</li><li>Understand <code>const int *p</code> (pointer to const) vs <code>int *const p</code> (const pointer).</li></ul>",
        examples=[
            {"title":"Reverse a String In-Place","code":"#include <stdio.h>\n#include <string.h>\n\nvoid reverse(char *str) {\n    int len = strlen(str);\n    for (int i = 0; i < len / 2; i++) {\n        char temp = str[i];\n        str[i] = str[len-1-i];\n        str[len-1-i] = temp;\n    }\n}\n\nint main() {\n    char s[] = \"Hello\";\n    reverse(s);\n    printf(\"%s\\n\", s);\n    return 0;\n}","output":"olleH","explanation":"<p>Classic pointer/array interview question — swap characters from both ends moving inward. O(n) time, O(1) space.</p>"},
            {"title":"Check if String is Palindrome","code":"#include <stdio.h>\n#include <string.h>\n#include <stdbool.h>\n\nbool isPalindrome(const char *s) {\n    int l = 0, r = strlen(s) - 1;\n    while (l < r) {\n        if (s[l] != s[r]) return false;\n        l++; r--;\n    }\n    return true;\n}\n\nint main() {\n    printf(\"racecar: %s\\n\", isPalindrome(\"racecar\") ? \"yes\" : \"no\");\n    printf(\"hello:   %s\\n\", isPalindrome(\"hello\") ? \"yes\" : \"no\");\n    return 0;\n}","output":"racecar: yes\nhello:   no","explanation":"<p>Two-pointer technique: compare characters from both ends. <code>const char *</code> signals the function doesn't modify the string.</p>"},
            {"title":"Memory Layout Demo","code":"#include <stdio.h>\n#include <stdlib.h>\n\nint global_var = 10;      // Data segment\nstatic int static_var = 20; // Data segment\n\nint main() {\n    int local_var = 30;    // Stack\n    int *heap_var = (int*)malloc(sizeof(int)); // Heap\n    *heap_var = 40;\n    \n    printf(\"Global (data): %p\\n\", (void*)&global_var);\n    printf(\"Static (data): %p\\n\", (void*)&static_var);\n    printf(\"Local (stack): %p\\n\", (void*)&local_var);\n    printf(\"Heap:          %p\\n\", (void*)heap_var);\n    \n    free(heap_var);\n    return 0;\n}","output":"Global (data): 0x601xxx\nStatic (data): 0x601xxx\nLocal (stack): 0x7fffxxx\nHeap:          0x1xxxxxx","explanation":"<p>Stack addresses are high (0x7fff...), heap addresses are low (0x1...), global/static are in between — visualizing C memory layout.</p>"},
        ],
        quiz=[
            {"q":"What is a dangling pointer?","options":["A pointer to NULL","A pointer to freed memory","An uninitialized pointer","A function pointer"],"answer":"A pointer to freed memory"},
            {"q":"Stack memory is managed:","options":["Manually with malloc/free","Automatically by the compiler","By the OS kernel","By garbage collection"],"answer":"Automatically by the compiler"},
        ],
    ),
}

# C# placeholder — we need these but they're too long for one file
# I'll do the same quality for C# in batch_csharp_extra.py
CSHARP_FIXES = {}

def load_data():
    with open(FILEPATH, 'r', encoding='utf-8') as f:
        content = f.read()
    prefix = 'window.tracksData = '
    idx = content.find(prefix)
    raw_json = content[idx + len(prefix):]
    suffix = ''
    if raw_json.strip().endswith(';'):
        raw_json = raw_json.strip()[:-1]
        suffix = ';'
    return content[:idx + len(prefix)], json.loads(raw_json), suffix

def save_data(prefix_content, data, suffix):
    with open(FILEPATH, 'w', encoding='utf-8') as f:
        f.write(prefix_content)
        f.write(json.dumps(data, ensure_ascii=False, separators=(',', ':')))
        f.write(suffix)

def apply_fixes(data, lang_key, fixes):
    fixed = 0
    for topic_key, new_content in fixes.items():
        if topic_key in data.get(lang_key, {}).get('content', {}):
            existing = data[lang_key]['content'][topic_key]
            new_content['title'] = existing.get('title', topic_key)
            new_content['phase'] = existing.get('phase', 1)
            data[lang_key]['content'][topic_key] = new_content
            fixed += 1
            print('  OK %s/%s' % (lang_key, topic_key))
        else:
            print('  MISS %s/%s' % (lang_key, topic_key))
    return fixed

if __name__ == '__main__':
    print('Loading tracks_data.js...')
    prefix_content, data, suffix = load_data()
    total = 0
    print('\n--- Fixing C ---')
    total += apply_fixes(data, 'c', C_FIXES)
    if CSHARP_FIXES:
        print('\n--- Fixing C# ---')
        total += apply_fixes(data, 'csharp', CSHARP_FIXES)
    print('\nSaving %d fixes...' % total)
    save_data(prefix_content, data, suffix)
    print('Done!')
